import { fase, tema, type QuizTema } from "./tipos";

// Categoría: Backend. Temas: Node.js, APIs REST, Autenticación y seguridad, Arquitectura backend, Express.

const nodejs: QuizTema = tema(
  "nodejs",
  "Node.js",
  "Runtime de JavaScript en el servidor: módulos, event loop, streams y asincronía.",
  [
    fase(1, [
      ["¿Qué es Node.js?", ["Un navegador", "Un runtime para ejecutar JavaScript fuera del navegador", "Un lenguaje", "Una base de datos"], 1, "Node ejecuta JS en el servidor usando V8."],
      ["¿Qué comando ejecuta un archivo?", ["run app.js", "node app.js", "js app.js", "exec app.js"], 1, "node app.js corre el archivo."],
      ["¿Qué gestor de paquetes viene con Node?", ["pip", "npm", "cargo", "maven"], 1, "npm gestiona dependencias."],
      ["¿Qué archivo describe un proyecto Node?", ["package.json", "config.js", "node.json", "app.config"], 0, "package.json define scripts y dependencias."],
      ["¿Qué objeto global da acceso a variables de entorno?", ["window", "process.env", "global.vars", "env()"], 1, "process.env expone las variables de entorno."],
    ]),
    fase(2, [
      ["¿Qué sistema de módulos usa require()?", ["ESM", "CommonJS", "AMD", "UMD"], 1, "require es de CommonJS."],
      ["¿Cómo se importa con ESM?", ["require", "import ... from", "include", "using"], 1, "import es la sintaxis de ES Modules."],
      ["¿Qué módulo maneja rutas de archivos?", ["fs", "path", "os", "url"], 1, "path normaliza y une rutas."],
      ["¿Qué módulo lee/escribe archivos?", ["path", "fs", "http", "crypto"], 1, "fs (file system) opera con archivos."],
      ["¿Node es single-thread para el JS del usuario?", ["No, multihilo", "Sí, un hilo principal con event loop", "Depende del SO", "Solo en Windows"], 1, "El JS corre en un hilo con event loop no bloqueante."],
    ]),
    fase(3, [
      ["¿Qué representa un callback?", ["Una función que se ejecuta al completar una tarea async", "Un módulo", "Un stream", "Un buffer"], 0, "El callback se invoca cuando la operación termina."],
      ["¿Qué patrón moderno reemplaza a los callbacks anidados?", ["var", "Promesas / async-await", "eval", "sync"], 1, "Async/await aplana el código asíncrono."],
      ["¿Qué es un módulo de eventos (EventEmitter)?", ["Permite emitir y escuchar eventos personalizados", "Un stream", "Un buffer", "Un ORM"], 0, "EventEmitter implementa pub/sub."],
      ["¿Qué es un Buffer?", ["Datos binarios crudos en memoria", "Un stream de texto", "Un módulo HTTP", "Un timer"], 0, "Buffer maneja bytes binarios."],
      ["¿Qué hace fs.readFile de forma asíncrona?", ["Bloquea hasta leer", "Lee sin bloquear y usa callback/promesa", "Escribe", "Borra"], 1, "La versión async no bloquea el event loop."],
    ]),
    fase(4, [
      ["¿Qué es un stream?", ["Procesa datos por fragmentos sin cargar todo en memoria", "Un buffer completo", "Un timer", "Un módulo"], 0, "Los streams manejan datos de forma incremental."],
      ["¿Qué método crea un servidor HTTP básico?", ["http.createServer()", "net.serve()", "server.new()", "http.listen()"], 0, "http.createServer devuelve un servidor."],
      ["¿Qué es npm scripts?", ["Comandos definidos en package.json", "Un módulo core", "Un stream", "Un ORM"], 0, "Se ejecutan con npm run <nombre>."],
      ["¿Qué diferencia hay entre dependencies y devDependencies?", ["devDependencies solo se usan en desarrollo", "Son iguales", "dependencies son solo dev", "Ninguna se instala"], 0, "Las dev no se necesitan en producción."],
      ["¿Qué hace __dirname?", ["La ruta del directorio del módulo actual", "El home del usuario", "Un stream", "El CWD siempre"], 0, "__dirname es la carpeta del archivo (en CommonJS)."],
    ]),
    fase(5, [
      ["¿Qué son los microtasks vs. la fase timers del event loop?", ["Las promesas se resuelven antes que los timers en cada vuelta", "Los timers primero", "Son lo mismo", "No hay orden"], 0, "process.nextTick/promesas tienen prioridad."],
      ["¿Qué hace process.nextTick?", ["Encola un callback antes de continuar el event loop", "Detiene el proceso", "Crea un hilo", "Lee un archivo"], 0, "Se ejecuta antes de las siguientes fases."],
      ["¿Qué módulo cifra datos y hashea?", ["crypto", "fs", "path", "os"], 0, "crypto ofrece hashing y cifrado."],
      ["¿Qué hace worker_threads?", ["Ejecuta JS en hilos paralelos reales", "Crea procesos hijos", "Un stream", "Un timer"], 0, "worker_threads permite paralelismo de CPU."],
      ["¿Qué es un readable stream con backpressure?", ["Controla el ritmo cuando el consumidor es más lento", "Un buffer fijo", "Un timer", "Un ORM"], 0, "El backpressure evita saturar memoria."],
    ]),
    fase(6, [
      ["¿Qué diferencia hay entre worker_threads y child_process?", ["worker_threads comparte memoria; child_process crea procesos separados", "Son iguales", "child_process comparte memoria", "worker_threads es más lento siempre"], 0, "Los procesos hijos no comparten memoria por defecto."],
      ["¿Qué es el cluster module?", ["Crea varios procesos que comparten el mismo puerto para usar todos los núcleos", "Un stream", "Un ORM", "Un timer"], 0, "cluster escala a múltiples CPUs."],
      ["¿Qué es pipe() en streams?", ["Conecta la salida de un stream a la entrada de otro", "Cierra un stream", "Un buffer", "Un timer"], 0, "pipe encadena streams manejando backpressure."],
      ["¿Qué hace fs.promises?", ["Ofrece la API de archivos basada en promesas", "Solo callbacks", "Streams", "Cifrado"], 0, "Permite usar await con operaciones de archivo."],
      ["¿Por qué evitar operaciones síncronas (readFileSync) en un servidor?", ["Bloquean el event loop y frenan todas las peticiones", "Son inseguras", "No existen", "Consumen red"], 0, "El bloqueo degrada la concurrencia."],
    ]),
    fase(7, [
      ["¿Qué garantiza libuv en Node?", ["El event loop y un thread pool para I/O y tareas costosas", "El motor V8", "El ORM", "El HTTP"], 0, "libuv provee I/O asíncrona y el pool de hilos."],
      ["¿Qué operaciones usan el thread pool de libuv?", ["fs, crypto, dns (algunas), zlib", "Todo el JS", "Solo timers", "Ninguna"], 0, "Ciertas tareas se delegan al pool (por defecto 4 hilos)."],
      ["¿Qué es un memory leak típico en Node?", ["Listeners o referencias que crecen sin liberarse", "Punteros colgantes", "Overflow de pila", "Falta de free()"], 0, "Acumular listeners o cachés sin límite fuga memoria."],
      ["¿Qué hace AbortController en fetch/streams?", ["Permite cancelar operaciones asíncronas", "Crea hilos", "Cifra", "Un buffer"], 0, "AbortSignal cancela peticiones en curso."],
      ["¿Qué es un Transform stream?", ["Un stream que lee, transforma y escribe datos", "Solo lectura", "Solo escritura", "Un timer"], 0, "Transform modifica los datos al pasar (p.ej. gzip)."],
    ]),
    fase(8, [
      ["¿Por qué CPU-bound tasks perjudican a Node?", ["Bloquean el hilo único; se deben mover a workers/procesos", "Usan mucha red", "No compilan", "Fugan memoria siempre"], 0, "El cómputo pesado congela el event loop."],
      ["¿Qué es el heap snapshot y para qué sirve?", ["Captura del uso de memoria para diagnosticar fugas", "Un backup de disco", "Un stream", "Un timer"], 0, "Permite analizar objetos retenidos."],
      ["¿Qué hace --max-old-space-size?", ["Ajusta el límite de memoria del heap de V8", "Crea hilos", "Cifra", "Un stream"], 0, "Controla cuánta memoria puede usar V8."],
      ["¿Qué ventaja da streaming una respuesta HTTP grande?", ["Menor uso de memoria y TTFB más bajo", "Más memoria", "Más lento siempre", "Nada"], 0, "Se envían datos a medida que se generan."],
      ["¿Qué es la propagación de contexto con AsyncLocalStorage?", ["Mantener contexto (p.ej. requestId) a través de llamadas async", "Un cache global", "Un stream", "Un timer"], 0, "Asocia estado a una cadena asíncrona sin pasar args."],
    ]),
    fase(9, [
      ["¿Qué problema resuelve el patrón de graceful shutdown?", ["Cerrar conexiones y terminar tareas antes de salir del proceso", "Reiniciar más rápido", "Fugar memoria", "Nada"], 0, "Evita cortar peticiones en curso al desplegar."],
      ["¿Por qué unhandledRejection debe manejarse?", ["Una promesa rechazada sin catch puede tumbar el proceso", "Mejora el rendimiento", "Es cosmético", "No aplica"], 0, "Node puede terminar ante rechazos no manejados."],
      ["¿Qué es el 'event loop lag' y cómo se mide?", ["Retraso en procesar la cola; se mide con temporizadores/monitorPerformance", "Latencia de red", "Uso de disco", "Un stream"], 0, "El lag indica bloqueo del hilo principal."],
      ["¿Qué ventaja da un pool de conexiones a la DB?", ["Reutiliza conexiones y evita el costo de abrir una por request", "Más memoria", "Menos seguridad", "Nada"], 0, "El pooling mejora latencia y throughput."],
      ["¿Qué es el patrón de circuit breaker?", ["Cortar llamadas a un servicio que falla para no propagar fallos", "Un cache", "Un stream", "Un timer"], 0, "Protege el sistema ante dependencias caídas."],
    ]),
    fase(10, [
      ["¿Por qué worker_threads no elimina la necesidad de arquitecturas distribuidas?", ["Escala a los núcleos de una máquina, no entre máquinas", "Es más lento", "No comparte memoria", "Fuga memoria"], 0, "Para escalar horizontalmente hacen falta varios procesos/hosts."],
      ["¿Qué garantiza SharedArrayBuffer entre workers?", ["Compartir memoria binaria entre hilos (con sincronización via Atomics)", "Copiar datos", "Cifrar", "Nada"], 0, "Permite memoria compartida real entre workers."],
      ["¿Qué trade-off tiene aumentar el thread pool de libuv (UV_THREADPOOL_SIZE)?", ["Más paralelismo de I/O a costa de más memoria/contexto", "Siempre mejora", "No cambia nada", "Rompe el event loop"], 0, "Hay que dimensionarlo según la carga."],
      ["¿Por qué medir con clinic/perf en vez de suposiciones?", ["Identifica el cuello real (event loop, GC, I/O) antes de optimizar", "Es opcional", "No aplica a Node", "Solo para tests"], 0, "El profiling guía optimizaciones efectivas."],
      ["¿Qué implica que las promesas usen la microtask queue para la latencia?", ["Se resuelven antes de I/O/timers, pero muchas pueden postergar otras tareas", "No afecta", "Son macrotasks", "Bloquean el SO"], 0, "Encolar demasiadas microtasks retrasa timers/I/O."],
    ]),
  ],
);

const apisRest: QuizTema = tema(
  "apis-rest",
  "APIs REST",
  "Verbos HTTP, códigos de estado, recursos, idempotencia y buenas prácticas.",
  [
    fase(1, [
      ["¿Qué significa API?", ["Interfaz de Programación de Aplicaciones", "Un lenguaje", "Una base de datos", "Un servidor"], 0, "La API define cómo interactúan los sistemas."],
      ["¿Qué verbo HTTP consulta datos?", ["POST", "GET", "DELETE", "PUT"], 1, "GET recupera un recurso."],
      ["¿Qué verbo crea un recurso?", ["GET", "POST", "PATCH", "HEAD"], 1, "POST envía datos para crear."],
      ["¿Qué verbo elimina un recurso?", ["REMOVE", "DELETE", "DROP", "CLEAR"], 1, "DELETE solicita eliminar el recurso."],
      ["¿Qué formato de datos es común en APIs modernas?", ["XML solamente", "JSON", "CSV", "YAML"], 1, "JSON es el estándar de intercambio."],
    ]),
    fase(2, [
      ["¿Qué código indica éxito general?", ["200 OK", "404", "500", "301"], 0, "200 significa petición exitosa."],
      ["¿Qué código indica recurso creado?", ["200", "201 Created", "204", "202"], 1, "201 confirma la creación."],
      ["¿Qué código indica 'no encontrado'?", ["400", "401", "404 Not Found", "500"], 2, "404 indica que el recurso no existe."],
      ["¿Qué verbo reemplaza por completo un recurso?", ["PATCH", "PUT", "GET", "POST"], 1, "PUT sustituye la representación completa."],
      ["¿Qué verbo actualiza parcialmente?", ["PUT", "PATCH", "GET", "DELETE"], 1, "PATCH modifica solo algunos campos."],
    ]),
    fase(3, [
      ["¿Qué es un endpoint?", ["Una URL que expone un recurso u operación", "Un método de array", "Un token", "Una cookie"], 0, "El endpoint es el punto de acceso de la API."],
      ["¿Qué código indica error del cliente por datos inválidos?", ["500", "400 Bad Request", "200", "302"], 1, "400 señala una petición mal formada."],
      ["¿Qué es un query parameter?", ["Datos en la URL tras ? para filtrar/paginar", "El body", "Un header de auth", "Una cookie"], 0, "?page=2&limit=10 son query params."],
      ["¿Dónde suelen ir los datos de un POST?", ["En la URL", "En el body de la petición", "En un header X-Data", "En una cookie"], 1, "El cuerpo transporta el payload."],
      ["¿Qué representa un recurso en REST?", ["Una entidad direccionable por URL (ej. /usuarios/1)", "Un método", "Un token", "Un puerto"], 0, "Los recursos se identifican con URIs."],
    ]),
    fase(4, [
      ["¿Qué código indica 'no autenticado'?", ["403", "401 Unauthorized", "404", "400"], 1, "401 pide credenciales válidas."],
      ["¿Qué código indica 'autenticado pero sin permiso'?", ["401", "403 Forbidden", "404", "409"], 1, "403 niega el acceso al recurso."],
      ["¿Qué es la idempotencia?", ["Repetir la misma petición produce el mismo efecto", "Ejecutar en paralelo", "Cachear datos", "Cifrar"], 0, "GET, PUT y DELETE son idempotentes."],
      ["¿Es POST idempotente?", ["Sí siempre", "No, puede crear múltiples recursos", "Solo con cache", "Solo con 200"], 1, "Repetir POST puede duplicar recursos."],
      ["¿Qué header indica el tipo de contenido del body?", ["Accept", "Content-Type", "Authorization", "Host"], 1, "Content-Type: application/json describe el payload."],
    ]),
    fase(5, [
      ["¿Qué es CORS?", ["Política del navegador para peticiones entre orígenes distintos", "Un verbo HTTP", "Un token", "Un ORM"], 0, "CORS controla el acceso cross-origin."],
      ["¿Qué es la paginación en una API?", ["Dividir resultados grandes en páginas", "Cifrar datos", "Un verbo", "Un header"], 0, "Evita respuestas enormes con limit/offset o cursores."],
      ["¿Qué código indica conflicto (p.ej. recurso duplicado)?", ["409 Conflict", "404", "500", "201"], 0, "409 señala un conflicto con el estado actual."],
      ["¿Qué header transporta un token de autenticación?", ["Content-Type", "Authorization", "Host", "Accept"], 1, "Authorization: Bearer <token>."],
      ["¿Qué es el versionado de API?", ["Mantener versiones (p.ej. /v1) para no romper clientes", "Cachear", "Cifrar", "Paginar"], 0, "El versionado protege compatibilidad."],
    ]),
    fase(6, [
      ["¿Qué es HATEOAS?", ["Respuestas que incluyen enlaces a acciones/recursos relacionados", "Un verbo", "Un token", "Un header"], 0, "Es un nivel del modelo de madurez REST."],
      ["¿Qué código indica 'demasiadas peticiones'?", ["429 Too Many Requests", "409", "404", "500"], 0, "429 se usa con rate limiting."],
      ["¿Qué es rate limiting?", ["Limitar cuántas peticiones puede hacer un cliente en un tiempo", "Cachear", "Cifrar", "Paginar"], 0, "Protege la API de abuso y sobrecarga."],
      ["¿Qué es un cursor pagination frente a offset?", ["Usa un puntero estable; evita saltos/duplicados en datos que cambian", "Es más lento", "No pagina", "Cifra"], 0, "El cursor es más robusto en datasets dinámicos."],
      ["¿Qué código indica 'contenido sin cuerpo' (p.ej. DELETE exitoso)?", ["204 No Content", "200", "201", "202"], 0, "204 confirma éxito sin devolver body."],
    ]),
    fase(7, [
      ["¿Qué ventaja da ETag / If-None-Match?", ["Caché condicional: 304 si no cambió, ahorrando ancho de banda", "Cifrado", "Rate limiting", "Paginación"], 0, "Permite validación de caché eficiente."],
      ["¿Qué es idempotency key en pagos/creación?", ["Un identificador para que reintentos no dupliquen la operación", "Un token de auth", "Un header de cache", "Un cursor"], 0, "Evita crear el mismo recurso dos veces en reintentos."],
      ["¿Qué es una API idempotente ante reintentos de red?", ["Reintentar es seguro porque no cambia el estado más de una vez", "Duplica datos", "Falla siempre", "Cachea"], 0, "Clave para resiliencia ante fallos transitorios."],
      ["¿Qué diferencia hay entre 401 y 403 en la práctica?", ["401: no sé quién eres; 403: sé quién eres pero no puedes", "Son iguales", "403 pide login", "401 es de servidor"], 0, "Uno es autenticación; el otro, autorización."],
      ["¿Qué es content negotiation?", ["El cliente y servidor acuerdan formato vía Accept/Content-Type", "Cifrar", "Paginar", "Rate limit"], 0, "Permite servir JSON, XML, etc. según Accept."],
    ]),
    fase(8, [
      ["¿Por qué evitar exponer errores internos en la respuesta?", ["Filtran detalles sensibles (stack, SQL) a atacantes", "Es más lento", "No aplica", "Rompe el cache"], 0, "Se devuelven mensajes genéricos y se loguea internamente."],
      ["¿Qué es un webhook?", ["Un callback HTTP que el servidor envía ante un evento", "Un cursor", "Un token", "Un ETag"], 0, "Invierte el flujo: el servidor notifica al cliente."],
      ["¿Cómo se asegura la autenticidad de un webhook?", ["Firmando el payload (HMAC) y verificando la firma", "Con CORS", "Con paginación", "Con 204"], 0, "La firma evita webhooks falsificados."],
      ["¿Qué es backward compatibility en una API?", ["Cambios que no rompen clientes existentes (agregar sin quitar)", "Cifrado", "Paginación", "Rate limit"], 0, "Añadir campos opcionales mantiene compatibilidad."],
      ["¿Qué código usar si el servidor está temporalmente saturado?", ["503 Service Unavailable", "404", "400", "201"], 0, "503 indica indisponibilidad temporal (con Retry-After)."],
    ]),
    fase(9, [
      ["¿Qué problema resuelve el patrón BFF (Backend for Frontend)?", ["Adaptar/agrupar APIs a las necesidades de cada cliente", "Cifrar", "Paginar", "Rate limit"], 0, "Reduce over/under-fetching por tipo de cliente."],
      ["¿Cuándo conviene GraphQL frente a REST?", ["Cuando el cliente necesita seleccionar campos y evitar múltiples round-trips", "Siempre", "Nunca", "Solo para archivos"], 0, "GraphQL flexibiliza la forma de la respuesta."],
      ["¿Qué es el problema de over-fetching?", ["Recibir más datos de los necesarios en un endpoint fijo", "Recibir de menos", "Cifrar de más", "Paginar mal"], 0, "REST rígido puede devolver campos innecesarios."],
      ["¿Qué garantiza diseñar operaciones idempotentes en sistemas distribuidos?", ["Reintentos seguros ante entregas duplicadas o fallos parciales", "Menos latencia siempre", "Cifrado", "Nada"], 0, "La idempotencia es clave para resiliencia."],
      ["¿Qué es un dead letter queue en integraciones asíncronas?", ["Cola para mensajes que no se pudieron procesar tras varios intentos", "Un cache", "Un cursor", "Un ETag"], 0, "Aísla mensajes fallidos para inspección posterior."],
    ]),
    fase(10, [
      ["¿Qué trade-off introduce la consistencia eventual en APIs a escala?", ["Mayor disponibilidad/rendimiento a costa de lecturas momentáneamente desactualizadas", "Menos disponibilidad", "Cifrado", "Nada"], 0, "Se relaja la consistencia inmediata por escalabilidad."],
      ["¿Por qué versionar por contrato (schema) además de por URL?", ["Detecta cambios incompatibles automáticamente entre productor y consumidor", "Es cosmético", "Reduce latencia", "Cifra"], 0, "El contrato formaliza compatibilidad (p.ej. OpenAPI)."],
      ["¿Qué es el patrón saga en operaciones distribuidas?", ["Coordinar transacciones largas con compensaciones ante fallos", "Un cache", "Un token", "Un ETag"], 0, "Reemplaza transacciones ACID distribuidas con pasos compensables."],
      ["¿Qué riesgo tiene exponer IDs secuenciales en URLs?", ["Enumeración/scraping de recursos (IDOR); mejor UUID + autorización", "Más lento", "Rompe cache", "Nada"], 0, "Los IDs predecibles facilitan ataques de enumeración."],
      ["¿Qué garantiza un buen diseño de errores (RFC 7807 problem+json)?", ["Errores estructurados y consistentes para los clientes", "Cifrado", "Paginación", "Rate limit"], 0, "Estandariza el cuerpo de los errores."],
    ]),
  ],
);

const autenticacion: QuizTema = tema(
  "autenticacion",
  "Autenticación y seguridad",
  "Hashing, sesiones, JWT, OWASP, cifrado y control de acceso.",
  [
    fase(1, [
      ["¿Qué es autenticación?", ["Verificar la identidad de un usuario", "Asignar permisos", "Cifrar datos", "Cachear"], 0, "Responde a '¿quién eres?'."],
      ["¿Qué es autorización?", ["Determinar qué puede hacer un usuario", "Verificar identidad", "Cifrar", "Paginar"], 0, "Responde a '¿qué puedes hacer?'."],
      ["¿Se deben guardar contraseñas en texto plano?", ["Sí", "No, nunca", "Solo en dev", "Solo cortas"], 1, "Siempre se hashean."],
      ["¿Qué protocolo cifra el tráfico web?", ["HTTP", "HTTPS (TLS)", "FTP", "SMTP"], 1, "HTTPS protege datos en tránsito."],
      ["¿Qué es un token?", ["Una credencial que prueba una sesión/identidad", "Una cookie de estilo", "Un verbo HTTP", "Un ORM"], 0, "El token acredita al portador."],
    ]),
    fase(2, [
      ["¿Qué es hashing de contraseñas?", ["Transformarlas de forma irreversible antes de guardarlas", "Cifrarlas reversiblemente", "Comprimirlas", "Codificarlas en base64"], 0, "El hash no se puede revertir a la original."],
      ["¿Qué algoritmo es adecuado para contraseñas?", ["MD5", "bcrypt/argon2", "base64", "SHA-1"], 1, "bcrypt/argon2 son lentos y salados a propósito."],
      ["¿Qué es un salt?", ["Valor aleatorio único por contraseña para evitar rainbow tables", "Una clave pública", "Un token", "Una cookie"], 0, "El salt hace únicos hashes de contraseñas iguales."],
      ["¿Es base64 un cifrado?", ["Sí", "No, es solo codificación (reversible sin clave)", "Sí, con clave", "Solo para imágenes"], 1, "base64 no protege nada; es codificación."],
      ["¿Qué es 2FA?", ["Segundo factor de autenticación además de la contraseña", "Un token JWT", "Un salt", "Un hash"], 0, "Añade una capa extra (p.ej. código OTP)."],
    ]),
    fase(3, [
      ["¿Qué es un JWT?", ["Un token JSON firmado que transporta claims", "Una cookie de sesión en DB", "Un salt", "Un ORM"], 0, "El JWT lleva datos firmados verificables."],
      ["¿Qué garantiza la firma de un JWT?", ["Integridad y autenticidad (no fue alterado)", "Confidencialidad total", "Compresión", "Caché"], 0, "La firma detecta manipulaciones; no oculta el contenido."],
      ["¿El payload de un JWT está cifrado por defecto?", ["Sí", "No, solo está codificado en base64 (legible)", "Solo el header", "Depende del salt"], 1, "Cualquiera puede leer el payload; no pongas secretos."],
      ["¿Qué es una sesión con cookie?", ["El servidor guarda estado y la cookie referencia la sesión", "Un token sin estado", "Un salt", "Un hash"], 0, "La cookie contiene el id de sesión."],
      ["¿Qué atributo de cookie impide acceso desde JavaScript?", ["Secure", "HttpOnly", "SameSite", "Path"], 1, "HttpOnly mitiga robo de cookie vía XSS."],
    ]),
    fase(4, [
      ["¿Qué es XSS?", ["Inyección de scripts maliciosos que se ejecutan en el navegador", "Inyección SQL", "Un token", "Un hash"], 0, "El XSS ejecuta código en el contexto de la víctima."],
      ["¿Cómo se mitiga principalmente el XSS?", ["Escapando/sanitizando la salida y con CSP", "Con más cookies", "Con base64", "Con GET"], 0, "Nunca inyectar HTML/JS sin escapar."],
      ["¿Qué es CSRF?", ["Forzar al navegador de la víctima a hacer una acción autenticada no deseada", "Robar la DB", "Un hash", "Un salt"], 0, "El CSRF abusa de la sesión activa del usuario."],
      ["¿Qué atributo de cookie mitiga CSRF?", ["HttpOnly", "SameSite", "Secure", "Domain"], 1, "SameSite limita el envío cross-site de la cookie."],
      ["¿Qué es inyección SQL?", ["Insertar SQL malicioso por entradas no saneadas", "Un XSS", "Un token", "Un salt"], 0, "Se previene con consultas parametrizadas."],
    ]),
    fase(5, [
      ["¿Cómo se previene la inyección SQL?", ["Consultas parametrizadas / ORM, nunca concatenar input", "Con más cookies", "Con base64", "Con GET"], 0, "Los parámetros separan datos de la consulta."],
      ["¿Qué es el principio de menor privilegio?", ["Dar solo los permisos estrictamente necesarios", "Dar todos los permisos", "Cifrar todo", "Cachear"], 0, "Reduce el impacto de una cuenta comprometida."],
      ["¿Qué atributo de cookie exige HTTPS?", ["HttpOnly", "Secure", "SameSite", "Path"], 1, "Secure impide enviarla por HTTP plano."],
      ["¿Qué es OAuth 2.0?", ["Un marco de autorización delegada (acceso sin compartir contraseña)", "Un algoritmo de hash", "Un ORM", "Un salt"], 0, "Permite a apps acceder a recursos con consentimiento."],
      ["¿Qué diferencia hay entre OAuth y OpenID Connect?", ["OAuth autoriza; OIDC añade capa de autenticación de identidad", "Son iguales", "OIDC autoriza", "OAuth cifra"], 0, "OIDC provee el 'quién eres' sobre OAuth."],
    ]),
    fase(6, [
      ["¿Por qué usar refresh tokens con access tokens de vida corta?", ["Limitar la ventana si el access token se filtra", "Para cifrar", "Para paginar", "Para cache"], 0, "El access corto reduce el riesgo; el refresh renueva."],
      ["¿Dónde NO conviene guardar un JWT sensible en el navegador?", ["En localStorage (accesible por XSS)", "En cookie HttpOnly", "En memoria efímera", "En el servidor"], 0, "localStorage es vulnerable a robo vía XSS."],
      ["¿Qué es CSP (Content Security Policy)?", ["Cabecera que restringe fuentes de scripts/recursos para mitigar XSS", "Un salt", "Un ORM", "Un token"], 0, "CSP limita qué código puede ejecutarse."],
      ["¿Qué es un ataque de fuerza bruta y cómo se mitiga?", ["Probar muchas contraseñas; se mitiga con rate limit/lockout/2FA", "Un XSS", "Un CSRF", "Un salt"], 0, "Limitar intentos frena el guessing."],
      ["¿Qué es RBAC?", ["Control de acceso basado en roles", "Un hash", "Un token", "Un salt"], 0, "Los permisos se asignan por rol."],
    ]),
    fase(7, [
      ["¿Qué garantiza el cifrado asimétrico (clave pública/privada)?", ["Cifrar con una clave y descifrar con la otra; firmas verificables", "Una sola clave para todo", "Solo hashing", "Compresión"], 0, "Base de TLS y firmas digitales."],
      ["¿Qué es un ataque de replay y cómo se mitiga?", ["Reenviar una petición válida capturada; se mitiga con nonces/timestamps", "Un XSS", "Un salt", "Un hash"], 0, "El nonce/expiración invalida reenvíos."],
      ["¿Por qué comparar hashes con comparación de tiempo constante?", ["Evita timing attacks que deducen el valor por el tiempo de respuesta", "Es más rápido", "Ahorra memoria", "No aplica"], 0, "La comparación variable filtra información."],
      ["¿Qué es token rotation en refresh tokens?", ["Emitir un nuevo refresh en cada uso e invalidar el anterior", "No cambiar el token", "Cifrar dos veces", "Cachear"], 0, "Detecta y limita el robo de refresh tokens."],
      ["¿Qué protege HSTS?", ["Fuerza HTTPS evitando downgrades a HTTP", "El XSS", "El CSRF", "El salt"], 0, "HSTS impide conexiones inseguras posteriores."],
    ]),
    fase(8, [
      ["¿Qué problema resuelve PKCE en OAuth para clientes públicos?", ["Evita interceptación del authorization code sin secreto de cliente", "Cifra el payload", "Reemplaza al hash", "Pagina"], 0, "PKCE protege el flujo en SPAs/móviles."],
      ["¿Por qué firmar JWT con algoritmos asimétricos (RS256) en microservicios?", ["Los servicios verifican con la clave pública sin conocer la privada", "Es más rápido", "Ocupa menos", "No firma"], 0, "Separa quién emite de quién verifica."],
      ["¿Qué riesgo tiene aceptar alg:none en un JWT?", ["Permite tokens sin firma, falsificables", "Es más seguro", "Solo cifra", "Nada"], 0, "Debe rechazarse alg:none siempre."],
      ["¿Qué es defense in depth?", ["Varias capas de seguridad para que un fallo no comprometa todo", "Una sola barrera fuerte", "Un hash", "Un token"], 0, "Redundancia de controles reduce el riesgo."],
      ["¿Qué es una política de rotación de secretos?", ["Cambiar claves/credenciales periódicamente y ante incidentes", "No cambiarlas nunca", "Cifrar dos veces", "Cachear"], 0, "Limita la vida útil de un secreto filtrado."],
    ]),
    fase(9, [
      ["¿Qué garantiza mTLS en comunicación entre servicios?", ["Ambas partes se autentican mutuamente con certificados", "Solo el servidor se autentica", "Cifra el payload de JWT", "Nada"], 0, "El TLS mutuo verifica cliente y servidor."],
      ["¿Por qué la revocación de JWT es un reto?", ["Son sin estado; hace falta lista de revocación o vida corta", "No se pueden revocar nunca", "Se revocan solos", "Requieren cookies"], 0, "La naturaleza stateless complica invalidarlos antes de expirar."],
      ["¿Qué es el patrón token binding / sender-constrained tokens?", ["Atar el token a un cliente/clave para que robarlo no baste", "Cifrar el token", "Firmarlo dos veces", "Cachearlo"], 0, "Evita el uso de tokens robados por terceros."],
      ["¿Qué mitiga una CSP estricta con nonces frente a XSS?", ["Solo ejecuta scripts con el nonce correcto, bloqueando inyecciones", "Cifra cookies", "Rate limit", "Pagina"], 0, "El nonce por request bloquea scripts no autorizados."],
      ["¿Qué es SSRF y por qué es peligroso?", ["El servidor hace peticiones a destinos controlados por el atacante (p.ej. metadata interna)", "Un XSS", "Un CSRF", "Un salt"], 0, "SSRF puede alcanzar recursos internos sensibles."],
    ]),
    fase(10, [
      ["¿Qué trade-off tiene sesiones stateful vs. JWT stateless a escala?", ["Stateful permite revocación fácil pero requiere almacenamiento compartido; stateless escala pero cuesta revocar", "Ninguno", "Stateless revoca fácil", "Stateful no escala nunca"], 0, "Cada modelo equilibra revocación vs. escalabilidad."],
      ["¿Por qué el modelo zero trust asume que la red no es confiable?", ["Autentica y autoriza cada petición sin confiar en el perímetro", "Confía en la LAN", "Elimina el login", "Cifra solo en tránsito"], 0, "Zero trust verifica siempre, en cualquier red."],
      ["¿Qué garantiza el cifrado en reposo además del de tránsito?", ["Proteger datos si el almacenamiento es comprometido físicamente/lógicamente", "Solo protege la red", "Reemplaza el hashing", "Nada"], 0, "At-rest y in-transit son capas complementarias."],
      ["¿Qué es el problema de secretos en el código/imágenes de contenedor?", ["Quedan expuestos en repos/registries; deben ir en gestores de secretos", "No hay problema", "Se cifran solos", "Son públicos por diseño"], 0, "Usar vaults/variables evita filtrar credenciales."],
      ["¿Por qué auditar y loguear eventos de seguridad sin datos sensibles?", ["Permite detectar/investigar incidentes sin filtrar credenciales en logs", "Es cosmético", "Reduce latencia", "Cifra la DB"], 0, "El logging balancea trazabilidad y privacidad."],
    ]),
  ],
);

const arquitectura: QuizTema = tema(
  "arquitectura",
  "Arquitectura backend",
  "Capas, patrones, escalabilidad, mensajería, caché y diseño de sistemas.",
  [
    fase(1, [
      ["¿Qué es una arquitectura en capas?", ["Separar responsabilidades (presentación, lógica, datos)", "Un ORM", "Un cache", "Un token"], 0, "Cada capa tiene una responsabilidad clara."],
      ["¿Qué hace la capa de datos (repository)?", ["Acceder a la base de datos", "Renderizar UI", "Autenticar", "Cachear en el navegador"], 0, "El repository encapsula las consultas."],
      ["¿Qué hace la capa de servicio?", ["Contiene la lógica de negocio", "Consulta el DOM", "Renderiza HTML", "Define estilos"], 0, "El service orquesta reglas de negocio."],
      ["¿Qué es una API monolítica?", ["Toda la app en un solo despliegue/código base", "Muchos servicios", "Un cache", "Un ORM"], 0, "El monolito agrupa todo en una unidad."],
      ["¿Qué es escalar verticalmente?", ["Dar más CPU/RAM a una misma máquina", "Agregar más máquinas", "Cachear", "Cifrar"], 0, "Scale-up aumenta los recursos de un nodo."],
    ]),
    fase(2, [
      ["¿Qué es escalar horizontalmente?", ["Agregar más instancias/máquinas", "Más RAM a un nodo", "Cifrar", "Cachear"], 0, "Scale-out reparte la carga entre nodos."],
      ["¿Qué hace un load balancer?", ["Distribuye peticiones entre varias instancias", "Cifra datos", "Consulta la DB", "Renderiza"], 0, "Balancea la carga y mejora disponibilidad."],
      ["¿Qué es una caché?", ["Almacenamiento rápido de datos frecuentes para reducir latencia", "Un ORM", "Un token", "Un load balancer"], 0, "La caché evita recomputar/reconsultar."],
      ["¿Qué es stateless en un servicio?", ["No guarda estado de sesión entre peticiones", "Guarda todo en memoria", "Cifra", "Pagina"], 0, "Facilita escalar horizontalmente."],
      ["¿Qué es una cola de mensajes?", ["Middleware que desacopla productores y consumidores async", "Un cache", "Un ORM", "Un token"], 0, "Las colas amortiguan y desacoplan la carga."],
    ]),
    fase(3, [
      ["¿Qué son los microservicios?", ["Servicios pequeños e independientes que colaboran", "Un solo despliegue grande", "Un cache", "Un ORM"], 0, "Cada servicio despliega y escala por separado."],
      ["¿Qué ventaja da desacoplar con una cola?", ["Absorber picos y tolerar fallos temporales del consumidor", "Más acoplamiento", "Menos disponibilidad", "Nada"], 0, "El productor no espera al consumidor."],
      ["¿Qué es un API Gateway?", ["Punto de entrada único que enruta y aplica políticas transversales", "Un ORM", "Un cache local", "Un token"], 0, "Centraliza auth, rate limit y enrutamiento."],
      ["¿Qué es idempotencia en el consumo de mensajes?", ["Procesar un mensaje repetido sin efectos duplicados", "Cifrar", "Paginar", "Cachear"], 0, "Clave ante entregas 'at least once'."],
      ["¿Qué patrón separa lecturas de escrituras?", ["CQRS", "MVC", "RBAC", "TLS"], 0, "CQRS usa modelos distintos para leer y escribir."],
    ]),
    fase(4, [
      ["¿Qué es el patrón repository?", ["Abstrae el acceso a datos tras una interfaz", "Renderiza UI", "Autentica", "Cachea en cliente"], 0, "Desacopla la lógica de la persistencia."],
      ["¿Qué es inyección de dependencias?", ["Proveer dependencias desde afuera en vez de crearlas dentro", "Un ORM", "Un cache", "Un token"], 0, "Mejora testabilidad y desacople."],
      ["¿Qué garantiza un servicio idempotente ante reintentos?", ["Reintentar es seguro y no corrompe el estado", "Duplica datos", "Cifra", "Pagina"], 0, "Esencial en sistemas distribuidos."],
      ["¿Qué es cache invalidation?", ["Mantener la caché coherente al cambiar los datos", "Cifrar la caché", "Paginar", "Balancear"], 0, "Es uno de los problemas difíciles de la caché."],
      ["¿Qué es un read replica en bases de datos?", ["Copia de solo lectura para escalar consultas", "Una cola", "Un cache local", "Un token"], 0, "Descarga lecturas del nodo primario."],
    ]),
    fase(5, [
      ["¿Qué es el teorema CAP?", ["En una partición debes elegir entre consistencia y disponibilidad", "Un patrón de UI", "Un ORM", "Un token"], 0, "CAP: consistencia, disponibilidad, tolerancia a particiones."],
      ["¿Qué es consistencia eventual?", ["Las réplicas convergen con el tiempo, no al instante", "Consistencia inmediata siempre", "Cifrado", "Cache"], 0, "Prioriza disponibilidad a costa de datos momentáneamente stale."],
      ["¿Qué es sharding?", ["Particionar datos horizontalmente entre nodos", "Replicar todo", "Cifrar", "Cachear"], 0, "Cada shard almacena un subconjunto de datos."],
      ["¿Qué es un circuit breaker?", ["Cortar llamadas a un servicio que falla para evitar cascadas", "Un cache", "Un token", "Un shard"], 0, "Protege ante dependencias inestables."],
      ["¿Qué es backpressure en un pipeline?", ["Señalizar al productor que reduzca el ritmo", "Cifrar", "Paginar", "Balancear"], 0, "Evita saturar consumidores más lentos."],
    ]),
    fase(6, [
      ["¿Qué es el patrón saga?", ["Coordinar una transacción distribuida con pasos compensables", "Un cache", "Un token", "Un shard"], 0, "Reemplaza transacciones ACID entre servicios."],
      ["¿Qué diferencia hay entre orquestación y coreografía en sagas?", ["Orquestación: un coordinador central; coreografía: eventos entre servicios", "Son iguales", "Coreografía es central", "Orquestación usa eventos sueltos"], 0, "Definen cómo se coordinan los pasos."],
      ["¿Qué es event sourcing?", ["Guardar el estado como una secuencia de eventos inmutables", "Guardar solo el último estado", "Cifrar", "Cachear"], 0, "El estado se reconstruye reproduciendo eventos."],
      ["¿Qué es idempotency + at-least-once en mensajería?", ["Garantiza entrega repetible sin duplicar efectos", "Entrega exactamente una vez siempre", "Cifrado", "Cache"], 0, "El consumidor idempotente tolera duplicados."],
      ["¿Qué es un outbox pattern?", ["Publicar eventos de forma atómica con la escritura en DB", "Un cache", "Un shard", "Un token"], 0, "Evita perder eventos entre DB y broker."],
    ]),
    fase(7, [
      ["¿Qué problema resuelve CQRS a escala?", ["Optimizar y escalar lecturas y escrituras por separado", "Menos código siempre", "Cifrado", "Cache"], 0, "Modelos separados permiten optimizaciones específicas."],
      ["¿Qué es la consistencia fuerte frente a la eventual en trade-offs?", ["Fuerte: correctitud inmediata con más latencia/menos disponibilidad", "Son iguales", "Eventual es más lenta", "Fuerte no existe"], 0, "Se elige según requisitos del negocio."],
      ["¿Qué garantiza el patrón bulkhead?", ["Aislar recursos para que un fallo no agote a todo el sistema", "Un cache", "Un token", "Un shard"], 0, "Compartimenta como los mamparos de un barco."],
      ["¿Qué es rate limiting distribuido?", ["Limitar peticiones de forma coordinada entre múltiples instancias", "Local a un nodo", "Cifrado", "Cache"], 0, "Usa un store compartido (p.ej. Redis) para el contador."],
      ["¿Qué es el problema del thundering herd en cachés?", ["Muchas peticiones recalculan a la vez al expirar una clave", "Un shard", "Un token", "Un outbox"], 0, "Se mitiga con locks o refresco anticipado."],
    ]),
    fase(8, [
      ["¿Qué es cache stampede y cómo mitigarlo?", ["Recalcular masivamente al invalidar; se usa lock/single-flight o TTL jitter", "Un shard", "Un token", "Un outbox"], 0, "Coordinar el recálculo evita la avalancha."],
      ["¿Qué garantiza exactly-once processing y por qué es difícil?", ["Cada mensaje afecta el estado una sola vez; requiere idempotencia + dedupe", "Es trivial", "No existe", "Solo cifrado"], 0, "En la práctica se logra con at-least-once + idempotencia."],
      ["¿Qué es un consistent hashing y para qué sirve?", ["Distribuir claves entre nodos minimizando remapeos al escalar", "Cifrar claves", "Paginar", "Balancear round-robin"], 0, "Reduce el movimiento de datos al agregar/quitar nodos."],
      ["¿Qué es el patrón CQRS con read models materializados?", ["Vistas precalculadas optimizadas para consultas específicas", "Un cache local", "Un token", "Un shard"], 0, "Los read models sirven consultas rápidas."],
      ["¿Qué trade-off tiene el two-phase commit distribuido?", ["Consistencia fuerte pero bloqueante y frágil ante fallos del coordinador", "Siempre disponible", "Sin latencia", "Nada"], 0, "Por eso se prefieren sagas en muchos casos."],
    ]),
    fase(9, [
      ["¿Por qué event sourcing complica los cambios de esquema de eventos?", ["Hay que versionar y hacer upcasting de eventos históricos", "No cambia nada", "Elimina eventos viejos", "Cifra"], 0, "Los eventos antiguos deben seguir siendo interpretables."],
      ["¿Qué garantiza el idempotency key + dedup store en pagos?", ["Que reintentos de red no cobren dos veces", "Menos latencia", "Cifrado", "Cache"], 0, "Deduplicar por clave evita efectos duplicados."],
      ["¿Qué problema aborda el patrón strangler fig al migrar un monolito?", ["Reemplazar gradualmente funciones enrutando a los nuevos servicios", "Reescribir todo de golpe", "Cifrar", "Cache"], 0, "Migración incremental de bajo riesgo."],
      ["¿Qué es la coherencia causal en sistemas distribuidos?", ["Preservar el orden de eventos con relación causa-efecto entre réplicas", "Orden total siempre", "Sin orden", "Cifrado"], 0, "Más débil que la fuerte, más fuerte que la eventual pura."],
      ["¿Qué riesgo tiene compartir una base de datos entre microservicios?", ["Acoplamiento fuerte que rompe la independencia de despliegue", "Mejor escalado", "Más seguridad", "Nada"], 0, "Cada servicio debería poseer sus datos."],
    ]),
    fase(10, [
      ["¿Qué trade-off central introducen los microservicios frente al monolito?", ["Escalabilidad/autonomía a cambio de complejidad operativa y de red", "Solo ventajas", "Solo desventajas", "Ninguno"], 0, "Distribuir agrega latencia, fallos parciales y observabilidad."],
      ["¿Por qué la observabilidad (logs, métricas, traces) es clave a escala?", ["Permite diagnosticar fallos distribuidos difíciles de reproducir", "Es cosmético", "Reduce el código", "Cifra"], 0, "Sin trazabilidad, depurar sistemas distribuidos es inviable."],
      ["¿Qué garantiza el diseño para fallos (design for failure)?", ["Asumir que todo puede fallar y degradar con gracia (timeouts, retries, fallbacks)", "Que nada falla", "Menos código", "Cifrado"], 0, "La resiliencia se diseña, no se improvisa."],
      ["¿Qué problema resuelve la idempotencia de extremo a extremo en pipelines?", ["Tolerar reprocesos/duplicados sin corromper el resultado final", "Menos latencia", "Cifrado", "Cache"], 0, "Es la base de la fiabilidad en flujos asíncronos."],
      ["¿Por qué preferir contratos y versionado en comunicación entre servicios?", ["Permite evolucionar servicios sin romper a sus consumidores", "Es cosmético", "Reduce latencia", "Cifra"], 0, "Los contratos desacoplan el ritmo de cambio de cada equipo."],
    ]),
  ],
);

const express: QuizTema = tema(
  "express",
  "Express",
  "Framework web minimalista de Node: rutas, middleware, manejo de errores y REST.",
  [
    fase(1, [
      ["¿Qué es Express?", ["Un framework web minimalista para Node.js", "Una base de datos", "Un ORM", "Un navegador"], 0, "Express facilita crear servidores y APIs."],
      ["¿Cómo se crea una app?", ["const app = express()", "new Server()", "express.start()", "app.create()"], 0, "express() devuelve la aplicación."],
      ["¿Qué método define una ruta GET?", ["app.get()", "app.route()", "app.fetch()", "app.on()"], 0, "app.get(path, handler) responde a GET."],
      ["¿Con qué se envía una respuesta?", ["res.send()", "res.print()", "res.write() solamente", "req.send()"], 0, "res.send envía la respuesta al cliente."],
      ["¿Qué método pone el servidor a escuchar?", ["app.listen(port)", "app.serve()", "app.open()", "app.run()"], 0, "listen inicia el servidor en un puerto."],
    ]),
    fase(2, [
      ["¿Qué es un middleware?", ["Una función con (req, res, next) que procesa la petición", "Un ORM", "Un token", "Una vista"], 0, "El middleware corre en la cadena de la petición."],
      ["¿Qué hace next()?", ["Pasa el control al siguiente middleware", "Termina el proceso", "Cifra", "Renderiza"], 0, "next() continúa la cadena."],
      ["¿Cómo se leen datos JSON del body?", ["Con express.json() middleware", "req.query", "res.body", "app.body()"], 0, "express.json() parsea el cuerpo JSON."],
      ["¿Dónde están los parámetros de ruta (:id)?", ["req.params", "req.query", "req.body", "res.params"], 0, "req.params contiene los segmentos dinámicos."],
      ["¿Dónde están los query params (?x=1)?", ["req.body", "req.query", "req.params", "res.query"], 1, "req.query contiene la query string."],
    ]),
    fase(3, [
      ["¿Qué método responde a POST?", ["app.post()", "app.get()", "app.put()", "app.send()"], 0, "app.post maneja creaciones."],
      ["¿Qué hace res.status(201)?", ["Fija el código de estado de la respuesta", "Envía el body", "Cierra el server", "Redirige"], 0, "status establece el código HTTP."],
      ["¿Qué es un Router de Express?", ["Un mini-app para agrupar rutas modularmente", "Un ORM", "Un token", "Una vista"], 0, "express.Router() modulariza rutas."],
      ["¿Cómo se sirven archivos estáticos?", ["express.static('public')", "app.files()", "res.static()", "app.assets()"], 0, "express.static expone una carpeta."],
      ["¿Qué método envía JSON?", ["res.json()", "res.xml()", "res.text()", "res.html()"], 0, "res.json serializa y fija Content-Type."],
    ]),
    fase(4, [
      ["¿Cómo se define un middleware de manejo de errores?", ["Con 4 args: (err, req, res, next)", "Con 2 args", "Con app.error()", "Con try global"], 0, "La firma de 4 parámetros marca el error handler."],
      ["¿Dónde debe ir el error handler?", ["Al final, tras las rutas", "Al inicio", "En cada ruta", "En listen"], 0, "Se registra el último para capturar errores previos."],
      ["¿Cómo se aplica un middleware a todas las rutas?", ["app.use(mw)", "app.all(mw)", "app.get(mw)", "app.route(mw)"], 0, "app.use monta middleware global."],
      ["¿Qué hace res.redirect('/login')?", ["Redirige al cliente a otra URL", "Renderiza login", "Cierra el server", "Cifra"], 0, "Envía una respuesta de redirección."],
      ["¿Cómo se encadenan middlewares en una ruta?", ["app.get(path, mw1, mw2, handler)", "Solo un handler", "app.chain()", "app.pipe()"], 0, "Se pasan varios handlers en orden."],
    ]),
    fase(5, [
      ["¿Cómo se maneja un error en un handler async correctamente?", ["Capturarlo y llamar next(err) o usar un wrapper", "Ignorarlo", "Con res.end()", "Con app.on('error')"], 0, "Express (v4) no captura rechazos async automáticamente."],
      ["¿Qué es CORS middleware?", ["Configura cabeceras para permitir orígenes cruzados", "Un ORM", "Un token", "Un router"], 0, "Habilita peticiones desde otros dominios."],
      ["¿Qué hace el middleware de logging (p.ej. morgan)?", ["Registra las peticiones entrantes", "Cifra", "Autentica", "Renderiza"], 0, "Loguea método, ruta y tiempos."],
      ["¿Cómo se protege una ruta con auth?", ["Con un middleware que verifica el token y llama next()", "Con res.json()", "Con app.listen()", "Con static"], 0, "El middleware corta o deja pasar según auth."],
      ["¿Qué representa el orden de los middlewares?", ["Se ejecutan en el orden en que se registran", "Aleatorio", "Alfabético", "Por método"], 0, "El orden importa en la cadena."],
    ]),
    fase(6, [
      ["¿Por qué usar express.Router por dominio (usuarios, ofertas)?", ["Modulariza y mantiene el código organizado y testeable", "Es obligatorio", "Mejora el cifrado", "Reduce latencia"], 0, "Separar rutas por recurso escala mejor."],
      ["¿Qué riesgo tiene no validar/sanitizar el body?", ["Inyecciones y datos corruptos; usar validadores (zod/joi)", "Ninguno", "Más lento", "Cache"], 0, "Nunca confiar en la entrada del cliente."],
      ["¿Qué hace helmet?", ["Ajusta cabeceras HTTP de seguridad", "Autentica", "Renderiza", "Un ORM"], 0, "helmet mitiga vulnerabilidades comunes por headers."],
      ["¿Qué es rate limiting en Express?", ["Middleware que limita peticiones por IP/ventana", "Un router", "Un ORM", "Un static"], 0, "Protege endpoints de abuso."],
      ["¿Por qué centralizar el manejo de errores?", ["Respuestas consistentes y sin filtrar internals", "Es cosmético", "Reduce rutas", "Cifra"], 0, "Un handler único estandariza los errores."],
    ]),
    fase(7, [
      ["¿Qué problema tiene el manejo async en Express 4 sin wrapper?", ["Un throw en async no llega al error handler por defecto", "Es más rápido", "No compila", "Cache"], 0, "Se usa un asyncHandler o try/catch + next(err)."],
      ["¿Qué mejora Express 5 respecto a errores async?", ["Propaga rechazos de handlers async al error handler", "Elimina middleware", "Quita routers", "Cifra"], 0, "Express 5 maneja promesas rechazadas."],
      ["¿Qué es el patrón de middleware de validación?", ["Validar/normalizar la entrada antes del controlador", "Renderizar", "Cifrar", "Un ORM"], 0, "Aísla la validación de la lógica de negocio."],
      ["¿Cómo se implementa paginación en un endpoint Express?", ["Leer limit/offset o cursor de req.query y aplicarlos a la consulta", "Con res.json solo", "Con static", "Con helmet"], 0, "La paginación evita respuestas enormes."],
      ["¿Por qué separar controladores, servicios y repositorios en Express?", ["Desacopla HTTP, negocio y datos para testear y mantener", "Es obligatorio", "Cifra", "Reduce latencia"], 0, "La arquitectura en capas mejora la mantenibilidad."],
    ]),
    fase(8, [
      ["¿Qué ventaja da mover la lógica fuera del handler HTTP?", ["El servicio es reutilizable y testeable sin req/res", "Es más lento", "Rompe rutas", "Cifra"], 0, "El controlador solo traduce HTTP a llamadas de servicio."],
      ["¿Qué riesgo tiene un middleware que no llama next() ni responde?", ["La petición queda colgada (timeout)", "Va más rápido", "Cifra", "Nada"], 0, "Cada middleware debe responder o pasar el control."],
      ["¿Cómo se maneja graceful shutdown en Express?", ["Cerrar el server y drenar conexiones antes de salir", "Matar el proceso directo", "Con res.end()", "Con static"], 0, "Evita cortar peticiones activas al desplegar."],
      ["¿Qué es un middleware de correlación (requestId)?", ["Asigna un id por request para trazar logs", "Cifra", "Autentica", "Un ORM"], 0, "Facilita seguir una petición por los logs."],
      ["¿Por qué no bloquear el event loop dentro de un handler?", ["Congela todas las peticiones del proceso", "Mejora el cache", "Es seguro", "Nada"], 0, "El trabajo pesado debe delegarse (workers/colas)."],
    ]),
    fase(9, [
      ["¿Qué trade-off tiene Express frente a frameworks opinados (NestJS)?", ["Flexibilidad mínima vs. estructura/DI/convenciones listas", "Ninguno", "Express es más opinado", "Nest no usa Node"], 0, "Express deja la arquitectura al equipo."],
      ["¿Cómo se compone un pipeline de middleware robusto para producción?", ["helmet, cors, logging, rate limit, parsers, rutas y error handler final", "Solo rutas", "Solo static", "Solo helmet"], 0, "Un orden claro de capas transversales."],
      ["¿Por qué validar en el borde (edge) además del servicio?", ["Rechazar entradas inválidas temprano reduce carga y superficie de ataque", "Es redundante inútil", "Cifra", "Cache"], 0, "La validación temprana protege capas internas."],
      ["¿Qué es streaming de respuestas grandes en Express?", ["Enviar datos por chunks (res.write/pipe) para bajar memoria y TTFB", "Cargar todo en memoria", "Cifrar", "Cache"], 0, "El streaming mejora respuestas voluminosas."],
      ["¿Qué garantiza registrar el error handler al final?", ["Captura errores de todos los middlewares/rutas anteriores", "Nada", "Va más lento", "Cifra"], 0, "Su posición al final es la que le da alcance."],
    ]),
    fase(10, [
      ["¿Por qué la arquitectura de este repo (repository → service → route) mejora la mantenibilidad?", ["Separa responsabilidades y hace cada capa testeable e intercambiable", "Es obligatorio por Node", "Cifra", "Reduce latencia"], 0, "Es el patrón en capas idiomático del proyecto."],
      ["¿Qué trade-off tiene meta-cachear respuestas de endpoints dinámicos?", ["Menos latencia a costa de posible obsolescencia; requiere invalidación", "Solo ventajas", "Solo desventajas", "Nada"], 0, "La caché exige estrategia de invalidación."],
      ["¿Cómo se logra observabilidad en una API Express?", ["Logs estructurados, métricas y trazas con requestId propagado", "Con console.log suelto", "Con static", "Con helmet"], 0, "La observabilidad es clave en producción."],
      ["¿Qué riesgo introduce confiar en headers como X-Forwarded-For sin proxy de confianza?", ["Pueden falsificarse; hay que configurar 'trust proxy' correctamente", "Ninguno", "Mejora seguridad", "Cifra"], 0, "Solo confiar en headers detrás de un proxy conocido."],
      ["¿Por qué separar configuración por entorno (env) en un backend?", ["Evita hardcodear secretos y permite distintos ajustes por entorno", "Es cosmético", "Reduce rutas", "Cifra la DB"], 0, "La config por entorno es una buena práctica esencial."],
    ]),
  ],
);

export const TEMAS_BACKEND: QuizTema[] = [nodejs, apisRest, autenticacion, arquitectura, express];
