import { fase, tema, type QuizTema } from "./tipos";

// Categoría: Bases de datos. Temas: SQL, PostgreSQL, MongoDB, Prisma ORM, Redis.

const sql: QuizTema = tema(
  "sql",
  "SQL",
  "Consultas, joins, agregaciones, índices, transacciones y normalización.",
  [
    fase(1, [
      ["¿Qué significa SQL?", ["Structured Query Language", "Simple Query Logic", "Standard Query Loop", "System Query Language"], 0, "SQL es el lenguaje de bases relacionales."],
      ["¿Qué sentencia recupera datos?", ["GET", "SELECT", "FETCH", "READ"], 1, "SELECT consulta filas de una tabla."],
      ["¿Qué cláusula filtra filas?", ["FILTER", "WHERE", "HAVING", "LIMIT"], 1, "WHERE aplica condiciones a las filas."],
      ["¿Qué sentencia inserta datos?", ["ADD", "INSERT", "PUT", "CREATE ROW"], 1, "INSERT INTO agrega filas."],
      ["¿Qué sentencia elimina filas?", ["DROP", "DELETE", "REMOVE", "CLEAR"], 1, "DELETE quita filas según la condición."],
    ]),
    fase(2, [
      ["¿Qué sentencia modifica filas existentes?", ["MODIFY", "UPDATE", "CHANGE", "SET"], 1, "UPDATE ... SET cambia valores."],
      ["¿Qué cláusula ordena resultados?", ["SORT BY", "ORDER BY", "GROUP BY", "ARRANGE"], 1, "ORDER BY ordena ASC/DESC."],
      ["¿Qué cláusula limita el número de filas?", ["TOP only", "LIMIT", "MAX", "COUNT"], 1, "LIMIT restringe la cantidad devuelta."],
      ["¿Qué comodín representa cualquier secuencia en LIKE?", ["?", "%", "*", "#"], 1, "% coincide con cualquier cantidad de caracteres."],
      ["¿Qué palabra evita filas duplicadas en un SELECT?", ["UNIQUE", "DISTINCT", "ONLY", "SINGLE"], 1, "DISTINCT elimina duplicados del resultado."],
    ]),
    fase(3, [
      ["¿Qué hace un INNER JOIN?", ["Devuelve filas con coincidencia en ambas tablas", "Todas las de la izquierda", "Todas las de la derecha", "El producto cartesiano"], 0, "INNER JOIN cruza filas relacionadas."],
      ["¿Qué es una PRIMARY KEY?", ["Identificador único de cada fila", "Una relación", "Un índice temporal", "Un tipo de dato"], 0, "La clave primaria identifica de forma única."],
      ["¿Qué es una FOREIGN KEY?", ["Referencia a la clave primaria de otra tabla", "Un índice", "Un tipo numérico", "Un JOIN"], 0, "La clave foránea garantiza integridad referencial."],
      ["¿Qué función cuenta filas?", ["SUM()", "COUNT()", "AVG()", "MAX()"], 1, "COUNT() cuenta registros."],
      ["¿Qué cláusula agrupa filas para agregaciones?", ["ORDER BY", "GROUP BY", "WHERE", "LIMIT"], 1, "GROUP BY agrupa para funciones agregadas."],
    ]),
    fase(4, [
      ["¿Qué diferencia hay entre WHERE y HAVING?", ["WHERE filtra filas; HAVING filtra grupos tras GROUP BY", "Son iguales", "HAVING filtra filas", "WHERE agrupa"], 0, "HAVING se aplica sobre resultados agregados."],
      ["¿Qué hace un LEFT JOIN?", ["Todas las filas de la izquierda + coincidencias de la derecha", "Solo coincidencias", "Todas las de la derecha", "El producto"], 0, "Conserva las filas izquierdas sin match (con NULL)."],
      ["¿Qué representa NULL?", ["Ausencia de valor", "Cero", "Cadena vacía", "Falso"], 0, "NULL indica que no hay valor."],
      ["¿Qué función suma valores?", ["COUNT()", "SUM()", "AVG()", "MIN()"], 1, "SUM() totaliza una columna numérica."],
      ["¿Qué es un alias (AS)?", ["Renombrar temporalmente una columna o tabla", "Un índice", "Una clave", "Un JOIN"], 0, "AS mejora la legibilidad del resultado."],
    ]),
    fase(5, [
      ["¿Qué es un índice?", ["Estructura que acelera búsquedas a costa de espacio/escritura", "Una clave foránea", "Un JOIN", "Un tipo de dato"], 0, "El índice agiliza consultas por ciertas columnas."],
      ["¿Qué es una transacción?", ["Conjunto de operaciones atómicas (todo o nada)", "Un índice", "Un JOIN", "Un alias"], 0, "La transacción mantiene la integridad."],
      ["¿Qué sentencia confirma una transacción?", ["SAVE", "COMMIT", "APPLY", "END"], 1, "COMMIT persiste los cambios."],
      ["¿Qué sentencia deshace una transacción?", ["UNDO", "ROLLBACK", "CANCEL", "REVERT"], 1, "ROLLBACK revierte al estado previo."],
      ["¿Qué es una subconsulta?", ["Una consulta dentro de otra", "Un índice", "Un JOIN", "Un alias"], 0, "La subconsulta alimenta a la consulta externa."],
    ]),
    fase(6, [
      ["¿Qué garantizan las propiedades ACID?", ["Atomicidad, Consistencia, Aislamiento, Durabilidad", "Solo velocidad", "Solo cifrado", "Solo backups"], 0, "ACID asegura transacciones fiables."],
      ["¿Qué es la normalización?", ["Organizar datos para reducir redundancia y anomalías", "Cifrar", "Indexar", "Cachear"], 0, "Divide datos en tablas relacionadas."],
      ["¿Qué hace una GROUP BY con HAVING COUNT(*) > 1?", ["Filtra grupos con más de una fila (p.ej. duplicados)", "Ordena", "Une tablas", "Indexa"], 0, "Detecta grupos que cumplen la condición agregada."],
      ["¿Qué es un self join?", ["Unir una tabla consigo misma", "Unir dos tablas", "Un índice", "Un alias"], 0, "Útil para jerarquías (empleado-jefe)."],
      ["¿Qué es una vista (VIEW)?", ["Una consulta guardada que se usa como tabla virtual", "Un índice", "Una transacción", "Una clave"], 0, "La vista encapsula una consulta reutilizable."],
    ]),
    fase(7, [
      ["¿Qué problema evita un índice compuesto bien ordenado?", ["Escaneos completos en consultas con varias columnas", "Duplicados", "Transacciones", "NULLs"], 0, "El orden de columnas debe seguir el patrón de consulta."],
      ["¿Qué es una window function?", ["Cálculos sobre un conjunto de filas relacionado sin colapsarlas", "Una vista", "Un índice", "Un JOIN"], 0, "OVER(PARTITION BY...) computa por ventana."],
      ["¿Qué hace ROW_NUMBER() OVER(...)?", ["Numera filas dentro de una partición ordenada", "Suma", "Une tablas", "Crea índices"], 0, "Asigna un número secuencial por partición."],
      ["¿Qué es un CTE (WITH ...)?", ["Una subconsulta nombrada y reutilizable en la consulta", "Un índice", "Una vista materializada", "Un trigger"], 0, "Los CTE mejoran legibilidad y permiten recursión."],
      ["¿Qué es un nivel de aislamiento de transacción?", ["Define qué fenómenos concurrentes (dirty/phantom reads) se permiten", "Un índice", "Una clave", "Un JOIN"], 0, "READ COMMITTED, SERIALIZABLE, etc."],
    ]),
    fase(8, [
      ["¿Qué fenómeno permite READ COMMITTED que evita SERIALIZABLE?", ["Non-repeatable/phantom reads", "Dirty reads", "Ninguno", "Deadlocks"], 0, "READ COMMITTED no evita lecturas no repetibles."],
      ["¿Qué es un deadlock?", ["Dos transacciones se bloquean mutuamente esperando recursos", "Un índice lento", "Una vista", "Un CTE"], 0, "El motor aborta una para romper el ciclo."],
      ["¿Qué es un índice cubriente (covering index)?", ["Contiene todas las columnas de la consulta, evitando ir a la tabla", "Un índice único", "Una vista", "Un trigger"], 0, "La consulta se resuelve solo con el índice."],
      ["¿Qué hace EXPLAIN/EXPLAIN ANALYZE?", ["Muestra el plan de ejecución de una consulta", "Crea índices", "Ejecuta backups", "Cifra"], 0, "Ayuda a diagnosticar consultas lentas."],
      ["¿Qué es una CTE recursiva?", ["Un CTE que se referencia a sí mismo para recorrer jerarquías/grafos", "Una vista", "Un índice", "Un trigger"], 0, "Permite consultas jerárquicas (árboles)."],
    ]),
    fase(9, [
      ["¿Por qué un índice puede degradar las escrituras?", ["Cada INSERT/UPDATE debe mantener también el índice", "No afecta", "Acelera escrituras", "Cifra"], 0, "Los índices tienen costo de mantenimiento."],
      ["¿Qué es el problema N+1 en acceso a datos?", ["Una consulta por cada fila en lugar de una sola con JOIN/IN", "Un deadlock", "Un índice", "Un trigger"], 0, "Se resuelve con joins o carga por lotes."],
      ["¿Qué garantiza un índice sobre la columna de un ORDER BY frecuente?", ["Evita ordenamientos costosos en memoria/disco", "Duplica filas", "Cifra", "Nada"], 0, "El índice ya provee el orden."],
      ["¿Qué es sargable en una consulta?", ["Que la condición puede usar índices (evita funciones sobre la columna)", "Que ordena rápido", "Que cifra", "Que agrupa"], 0, "WHERE fecha >= x es sargable; WHERE YEAR(fecha)=x no."],
      ["¿Qué es la desnormalización controlada?", ["Duplicar datos a propósito para acelerar lecturas críticas", "Un error", "Un índice", "Un CTE"], 0, "Se acepta redundancia por rendimiento."],
    ]),
    fase(10, [
      ["¿Qué trade-off central plantean los índices en un sistema OLTP?", ["Aceleran lecturas pero encarecen escrituras y ocupan espacio", "Solo ventajas", "Solo desventajas", "Ninguno"], 0, "Hay que indexar según los patrones de consulta reales."],
      ["¿Qué diferencia hay entre OLTP y OLAP en el diseño de esquema?", ["OLTP normaliza para transacciones; OLAP desnormaliza (estrella) para análisis", "Son iguales", "OLAP normaliza más", "OLTP es solo lectura"], 0, "Cada carga favorece un modelado distinto."],
      ["¿Qué problema resuelve MVCC?", ["Lecturas sin bloquear escrituras manteniendo versiones de fila", "Duplicados", "Índices lentos", "Cifrado"], 0, "MVCC ofrece concurrencia con snapshots consistentes."],
      ["¿Por qué SERIALIZABLE puede reducir el rendimiento?", ["Más bloqueos/aborts para garantizar la máxima consistencia", "Es más rápido", "No usa índices", "Cifra"], 0, "La máxima consistencia cuesta concurrencia."],
      ["¿Qué garantiza una consulta parametrizada frente a rendimiento y seguridad?", ["Reutiliza el plan y previene inyección SQL", "Solo seguridad", "Solo velocidad", "Nada"], 0, "Los parámetros aportan seguridad y cacheo de planes."],
    ]),
  ],
);

const postgresql: QuizTema = tema(
  "postgresql",
  "PostgreSQL",
  "Motor relacional avanzado: tipos, JSONB, índices, MVCC y extensiones.",
  [
    fase(1, [
      ["¿Qué tipo de base de datos es PostgreSQL?", ["Relacional (con extras)", "Solo clave-valor", "Solo documentos", "En memoria únicamente"], 0, "Postgres es un RDBMS objeto-relacional."],
      ["¿Cuál es el puerto por defecto?", ["3306", "5432", "27017", "6379"], 1, "Postgres escucha en el 5432."],
      ["¿Qué comando cliente de terminal usa?", ["mysql", "psql", "mongo", "redis-cli"], 1, "psql es el cliente interactivo."],
      ["¿Qué tipo almacena texto de longitud variable?", ["CHAR fijo", "VARCHAR/TEXT", "INT", "BOOL"], 1, "VARCHAR y TEXT guardan cadenas variables."],
      ["¿Qué tipo guarda verdadero/falso?", ["BIT", "BOOLEAN", "FLAG", "TINYINT"], 1, "BOOLEAN es nativo en Postgres."],
    ]),
    fase(2, [
      ["¿Qué tipo genera identificadores únicos aleatorios?", ["SERIAL siempre", "UUID", "TEXT", "MONEY"], 1, "UUID es común para claves no secuenciales."],
      ["¿Qué crea SERIAL/BIGSERIAL?", ["Un entero autoincremental con secuencia", "Un UUID", "Un índice", "Un tipo JSON"], 0, "SERIAL usa una secuencia para autoincremento."],
      ["¿Qué tipo almacena fecha y hora con zona?", ["DATE", "TIMESTAMPTZ", "TIME", "INTERVAL"], 1, "TIMESTAMPTZ guarda instante con zona horaria."],
      ["¿Qué tipo guarda datos JSON binarios e indexables?", ["JSON", "JSONB", "TEXT", "XML"], 1, "JSONB es más eficiente y soporta índices."],
      ["¿Qué comando crea una base de datos?", ["MAKE DATABASE", "CREATE DATABASE", "NEW DB", "INIT DB"], 1, "CREATE DATABASE crea una nueva base."],
    ]),
    fase(3, [
      ["¿Qué ventaja tiene JSONB sobre JSON en Postgres?", ["Se almacena binario, es más rápido de consultar e indexable", "Ocupa menos siempre", "Es solo texto", "No permite índices"], 0, "JSONB permite operadores e índices GIN."],
      ["¿Qué operador accede a un campo JSONB como texto?", ["->>", "==", "::", "&&"], 0, "col->>'clave' devuelve el valor como texto."],
      ["¿Qué es una secuencia (SEQUENCE)?", ["Un generador de números incrementales", "Un índice", "Una vista", "Un tipo JSON"], 0, "Las secuencias respaldan columnas autoincrementales."],
      ["¿Qué comando agrega una columna?", ["ALTER TABLE ... ADD COLUMN", "UPDATE TABLE", "MODIFY TABLE", "ADD FIELD"], 0, "ALTER TABLE modifica el esquema."],
      ["¿Qué es un schema en Postgres?", ["Un espacio de nombres para agrupar objetos (tablas, vistas)", "Una fila", "Un índice", "Un backup"], 0, "El schema organiza objetos (p.ej. public)."],
    ]),
    fase(4, [
      ["¿Qué tipo de índice es el predeterminado?", ["Hash", "B-tree", "GIN", "BRIN"], 1, "B-tree sirve para igualdad y rangos."],
      ["¿Qué índice acelera búsquedas en JSONB/arrays/full-text?", ["B-tree", "GIN", "Hash", "BRIN"], 1, "GIN indexa valores compuestos/contenidos."],
      ["¿Qué es un constraint UNIQUE?", ["Impide valores duplicados en una columna", "Un índice espacial", "Una vista", "Un trigger"], 0, "UNIQUE garantiza unicidad."],
      ["¿Qué hace RETURNING en un INSERT?", ["Devuelve columnas de las filas insertadas", "Crea un índice", "Borra filas", "Hace commit"], 0, "RETURNING evita una consulta extra tras insertar."],
      ["¿Qué es un CHECK constraint?", ["Valida que los valores cumplan una condición", "Un índice", "Una secuencia", "Un backup"], 0, "CHECK restringe valores permitidos."],
    ]),
    fase(5, [
      ["¿Qué es MVCC en Postgres?", ["Control de concurrencia con múltiples versiones de fila", "Un tipo de índice", "Un backup", "Un JSON"], 0, "MVCC permite leer sin bloquear escrituras."],
      ["¿Qué hace VACUUM?", ["Recupera espacio de filas muertas (versiones obsoletas)", "Crea índices", "Cifra", "Hace backup"], 0, "VACUUM limpia tuplas muertas del MVCC."],
      ["¿Qué es un índice parcial?", ["Indexa solo filas que cumplen una condición", "Indexa todo", "Una vista", "Un trigger"], 0, "Reduce tamaño indexando un subconjunto útil."],
      ["¿Qué es un trigger?", ["Función que se ejecuta ante eventos (INSERT/UPDATE/DELETE)", "Un índice", "Una secuencia", "Un backup"], 0, "Los triggers automatizan lógica en la DB."],
      ["¿Qué es una vista materializada?", ["Una vista cuyo resultado se almacena físicamente", "Una vista normal", "Un índice", "Un trigger"], 0, "Cachea resultados; se refresca con REFRESH."],
    ]),
    fase(6, [
      ["¿Qué es un índice expresión (functional index)?", ["Indexa el resultado de una expresión (p.ej. lower(email))", "Indexa NULLs", "Una vista", "Un trigger"], 0, "Permite consultas sargables sobre funciones."],
      ["¿Qué operador comprueba contención en JSONB?", ["@>", "->>", "::", "||"], 0, "col @> '{...}' verifica si contiene el JSON."],
      ["¿Qué es full-text search en Postgres?", ["Búsqueda de texto con tsvector/tsquery y ranking", "Un LIKE simple", "Un índice B-tree", "Un backup"], 0, "tsvector indexa documentos para búsqueda textual."],
      ["¿Qué hace ON CONFLICT ... DO UPDATE (upsert)?", ["Inserta o actualiza si ya existe (según constraint)", "Solo inserta", "Solo borra", "Hace backup"], 0, "El upsert combina INSERT y UPDATE."],
      ["¿Qué es una función en PL/pgSQL?", ["Lógica procedural ejecutada dentro de la base de datos", "Un índice", "Un backup", "Un tipo"], 0, "PL/pgSQL permite programar en el servidor."],
    ]),
    fase(7, [
      ["¿Qué problema resuelve un índice GIN sobre JSONB?", ["Consultas eficientes por contención/claves en documentos", "Ordenar por fecha", "Cifrar", "Backups"], 0, "GIN acelera búsquedas dentro del JSONB."],
      ["¿Qué es table partitioning?", ["Dividir una tabla grande en particiones por rango/lista/hash", "Un índice", "Una vista", "Un trigger"], 0, "Mejora rendimiento y mantenimiento de tablas enormes."],
      ["¿Qué diferencia hay entre TRUNCATE y DELETE?", ["TRUNCATE vacía la tabla rápido sin escanear fila por fila", "Son iguales", "DELETE es más rápido", "TRUNCATE filtra"], 0, "TRUNCATE es más veloz pero menos flexible."],
      ["¿Qué es autovacuum?", ["Proceso que ejecuta VACUUM/ANALYZE automáticamente", "Un índice", "Un backup manual", "Un trigger"], 0, "Mantiene la salud del MVCC sin intervención."],
      ["¿Qué es ANALYZE?", ["Actualiza estadísticas para que el planner elija buenos planes", "Crea índices", "Cifra", "Backup"], 0, "Las estadísticas guían al optimizador."],
    ]),
    fase(8, [
      ["¿Qué causa 'bloat' en tablas/índices y cómo se mitiga?", ["Tuplas muertas del MVCC; se mitiga con VACUUM/autovacuum", "Falta de índices", "Cifrado", "Backups"], 0, "El bloat crece si el vacuum no sigue el ritmo."],
      ["¿Cuándo conviene un índice BRIN?", ["En columnas grandes y correlacionadas físicamente (p.ej. fechas append-only)", "Para JSONB", "Para búsquedas únicas", "Para texto"], 0, "BRIN es compacto para datos ordenados naturalmente."],
      ["¿Qué es SELECT ... FOR UPDATE?", ["Bloquea las filas seleccionadas para actualización concurrente segura", "Solo lee", "Crea un índice", "Hace backup"], 0, "Evita condiciones de carrera en actualizaciones."],
      ["¿Qué es transaction wraparound y por qué importa?", ["Agotamiento del contador de transacciones (XID) que exige vacuum", "Un índice lleno", "Un backup", "Cifrado"], 0, "Sin vacuum, el wraparound puede detener la DB."],
      ["¿Qué ventaja da CONCURRENTLY al crear un índice?", ["No bloquea escrituras en la tabla durante la creación", "Es más rápido", "Cifra", "Nada"], 0, "CREATE INDEX CONCURRENTLY evita bloqueos largos."],
    ]),
    fase(9, [
      ["¿Por qué muchos índices pueden dañar el rendimiento de escritura?", ["Cada modificación mantiene todos los índices y genera bloat", "No afecta", "Acelera escrituras", "Cifra"], 0, "Hay que indexar solo lo que las consultas usan."],
      ["¿Qué es HOT (Heap-Only Tuple) update?", ["Actualización que evita reescribir índices si no cambian columnas indexadas", "Un backup", "Un trigger", "Un índice GIN"], 0, "HOT reduce el costo de UPDATEs frecuentes."],
      ["¿Qué información clave da EXPLAIN ANALYZE?", ["Plan real con tiempos y filas estimadas vs. reales", "Solo el esquema", "Solo índices", "Backups"], 0, "Diferencias grandes indican estadísticas desactualizadas."],
      ["¿Qué es logical replication frente a physical?", ["Replica cambios a nivel de filas/tablas seleccionables", "Copia bytes del disco entero", "Un backup", "Un índice"], 0, "La lógica permite replicar tablas específicas y upgrades."],
      ["¿Qué garantiza un índice único sobre una columna con upsert?", ["Define el conflicto sobre el que ON CONFLICT actúa", "Ordena", "Cifra", "Nada"], 0, "El upsert necesita un constraint único de referencia."],
    ]),
    fase(10, [
      ["¿Qué trade-off tiene una vista materializada?", ["Lecturas rápidas a costa de datos potencialmente stale hasta refrescar", "Siempre frescos", "Solo desventajas", "Ninguno"], 0, "Hay que decidir cuándo hacer REFRESH."],
      ["¿Por qué el connection pooling (p.ej. PgBouncer) es clave a escala?", ["Postgres usa un proceso por conexión; el pool evita agotar recursos", "Cifra conexiones", "Crea índices", "Hace backups"], 0, "Muchas conexiones directas saturan el servidor."],
      ["¿Qué implica que Postgres use un proceso por conexión para el diseño?", ["Limitar/agrupar conexiones y preferir consultas cortas", "Conexiones infinitas gratis", "Es multihilo puro", "Nada"], 0, "El modelo de procesos condiciona la escalabilidad de conexiones."],
      ["¿Qué problema resuelve particionar por rango de fecha en tablas de eventos?", ["Consultas y mantenimiento (drop de particiones viejas) más eficientes", "Cifrado", "Menos índices", "Nada"], 0, "Facilita purgar y consultar por periodos."],
      ["¿Por qué mantener estadísticas (ANALYZE) al día es crítico para el planner?", ["Planes malos por estadísticas obsoletas causan consultas lentas", "No importa", "Cifra datos", "Crea backups"], 0, "El optimizador depende de estadísticas precisas."],
    ]),
  ],
);

const mongodb: QuizTema = tema(
  "mongodb",
  "MongoDB",
  "Base de datos de documentos: colecciones, BSON, consultas, índices y agregación.",
  [
    fase(1, [
      ["¿Qué tipo de base de datos es MongoDB?", ["Relacional", "Orientada a documentos (NoSQL)", "Clave-valor pura", "En columnas"], 1, "MongoDB almacena documentos tipo JSON."],
      ["¿Cómo se llama un registro en MongoDB?", ["Fila", "Documento", "Tupla", "Entrada"], 1, "El documento es la unidad de datos."],
      ["¿Cómo se agrupan los documentos?", ["Tablas", "Colecciones", "Índices", "Vistas"], 1, "Las colecciones agrupan documentos."],
      ["¿En qué formato se almacenan internamente los documentos?", ["XML", "BSON", "CSV", "YAML"], 1, "BSON es JSON binario."],
      ["¿Qué campo identifica de forma única un documento?", ["id", "_id", "pk", "key"], 1, "_id es la clave primaria del documento."],
    ]),
    fase(2, [
      ["¿Qué método inserta un documento?", ["insertOne()", "addRow()", "put()", "create()"], 0, "insertOne agrega un documento."],
      ["¿Qué método busca documentos?", ["select()", "find()", "get()", "query()"], 1, "find() consulta la colección."],
      ["¿Qué método actualiza documentos?", ["updateOne()", "set()", "modify()", "change()"], 0, "updateOne modifica un documento."],
      ["¿Qué método elimina documentos?", ["deleteOne()", "remove()", "drop()", "clear()"], 0, "deleteOne borra un documento."],
      ["¿Los documentos de una colección deben tener el mismo esquema?", ["Sí, estricto", "No, es de esquema flexible", "Solo el _id", "Nunca comparten campos"], 1, "MongoDB es schema-flexible."],
    ]),
    fase(3, [
      ["¿Qué operador filtra por mayor que?", ["$gt", "$max", "$more", "$hi"], 0, "$gt significa 'greater than'."],
      ["¿Qué operador coincide con cualquiera de una lista?", ["$or", "$in", "$any", "$list"], 1, "$in busca valores dentro de un array."],
      ["¿Qué es un documento embebido?", ["Un documento anidado dentro de otro", "Una colección", "Un índice", "Una vista"], 0, "Modela relaciones 'contiene' sin joins."],
      ["¿Qué método limita resultados?", ["limit()", "top()", "max()", "cut()"], 0, "limit() restringe la cantidad devuelta."],
      ["¿Qué método ordena resultados?", ["order()", "sort()", "arrange()", "by()"], 1, "sort() ordena por campos."],
    ]),
    fase(4, [
      ["¿Qué es el aggregation pipeline?", ["Etapas encadenadas que transforman documentos ($match, $group...)", "Un índice", "Un backup", "Un join simple"], 0, "El pipeline procesa datos por etapas."],
      ["¿Qué etapa filtra documentos en el pipeline?", ["$group", "$match", "$sort", "$project"], 1, "$match filtra como un WHERE."],
      ["¿Qué etapa agrupa y agrega?", ["$match", "$group", "$limit", "$project"], 1, "$group agrupa y calcula agregados."],
      ["¿Qué etapa selecciona/renombra campos?", ["$project", "$match", "$sort", "$skip"], 0, "$project define la forma del resultado."],
      ["¿Qué operador de $group cuenta documentos?", ["$sum: 1", "$count()", "$len", "$total"], 0, "$sum:1 acumula uno por documento."],
    ]),
    fase(5, [
      ["¿Qué hace $lookup?", ["Un join con otra colección", "Un índice", "Un backup", "Un filtro"], 0, "$lookup une documentos de otra colección."],
      ["¿Qué es un índice en MongoDB?", ["Estructura que acelera consultas por ciertos campos", "Una colección", "Un pipeline", "Un backup"], 0, "Sin índice, las consultas escanean toda la colección."],
      ["¿Qué es referencing frente a embedding?", ["Guardar el _id de otro documento en vez de anidarlo", "Anidar siempre", "Un índice", "Un backup"], 0, "Referencing normaliza; embedding desnormaliza."],
      ["¿Cuándo conviene embeber datos?", ["Cuando se leen juntos y la relación es contenida/1-a-pocos", "Siempre", "Nunca", "Solo con $lookup"], 0, "Embeber favorece lecturas de datos que van juntos."],
      ["¿Qué método actualiza muchos documentos?", ["updateMany()", "updateAll()", "setMany()", "modifyMany()"], 0, "updateMany afecta a todos los que coinciden."],
    ]),
    fase(6, [
      ["¿Qué es un índice compuesto en MongoDB?", ["Índice sobre varios campos, sensible al orden", "Un índice de texto", "Un backup", "Un pipeline"], 0, "El orden de campos importa (regla ESR)."],
      ["¿Qué es la regla ESR para índices?", ["Equality, Sort, Range: orden óptimo de campos en el índice", "Un tipo de backup", "Una etapa", "Un shard"], 0, "Guía cómo ordenar campos en índices compuestos."],
      ["¿Qué es un índice multikey?", ["Índice sobre un campo array (indexa cada elemento)", "Un índice único", "Un backup", "Un shard"], 0, "MongoDB crea entradas por cada valor del array."],
      ["¿Qué modelo de consistencia ofrece por defecto en réplicas?", ["Lecturas del primario con consistencia fuerte por defecto", "Siempre eventual", "Sin réplicas", "Solo del secundario"], 0, "Por defecto se lee del primario (majority en writes)."],
      ["¿Qué es un replica set?", ["Un grupo de nodos con un primario y secundarios para alta disponibilidad", "Un índice", "Un shard", "Un backup"], 0, "El replica set da redundancia y failover."],
    ]),
    fase(7, [
      ["¿Qué es sharding en MongoDB?", ["Particionar datos entre varios nodos por una shard key", "Replicar todo", "Un índice", "Un backup"], 0, "El sharding escala horizontalmente."],
      ["¿Por qué es crítica la elección de la shard key?", ["Determina la distribución y evita hotspots/desbalance", "No importa", "Solo cifra", "Solo backups"], 0, "Una mala shard key concentra la carga."],
      ["¿Qué son las transacciones multi-documento?", ["Operaciones ACID sobre varios documentos/colecciones", "Solo un documento", "Un índice", "Un backup"], 0, "Disponibles desde MongoDB 4.0 en replica sets."],
      ["¿Qué es un covered query?", ["La consulta se resuelve solo con el índice, sin leer documentos", "Un backup", "Un shard", "Un pipeline"], 0, "El índice contiene todos los campos requeridos."],
      ["¿Qué es write concern?", ["Nivel de garantía de que una escritura se replicó (p.ej. majority)", "Un índice", "Un pipeline", "Un backup"], 0, "Controla durabilidad vs. latencia de escritura."],
    ]),
    fase(8, [
      ["¿Qué trade-off tiene embedding en documentos que crecen sin límite?", ["Pueden superar el límite de 16MB y encarecer actualizaciones", "Siempre mejor", "Sin límite", "Nada"], 0, "Los documentos ilimitados favorecen referencing."],
      ["¿Qué es read concern 'majority'?", ["Leer datos confirmados por la mayoría de réplicas (más consistentes)", "Leer sin confirmar", "Un índice", "Un shard"], 0, "Evita leer escrituras que podrían revertirse."],
      ["¿Qué problema causa una shard key monotónica (p.ej. timestamp)?", ["Todas las escrituras van al mismo shard (hotspot)", "Distribuye bien", "Cifra", "Nada"], 0, "Las claves crecientes concentran inserciones."],
      ["¿Qué es el patrón bucket en series temporales?", ["Agrupar muchas mediciones en un documento por intervalo", "Un índice", "Un shard", "Un backup"], 0, "Reduce la cantidad de documentos y mejora consultas."],
      ["¿Qué garantiza majority write concern ante failover?", ["Que la escritura sobreviva a la elección de un nuevo primario", "Menor latencia", "Un índice", "Nada"], 0, "Los datos en la mayoría no se pierden al cambiar de primario."],
    ]),
    fase(9, [
      ["¿Por qué el esquema flexible no significa 'sin diseño de datos'?", ["El patrón de acceso debe guiar embedding/referencing e índices", "El esquema es irrelevante", "Todo se embebe", "Todo se referencia"], 0, "En NoSQL, se modela según cómo se consulta."],
      ["¿Qué riesgo tiene $lookup en colecciones grandes sin índice?", ["Uniones costosas que escanean toda la colección referenciada", "Ninguno", "Siempre rápido", "Cifra"], 0, "Los joins requieren índices en el campo unido."],
      ["¿Qué es change streams?", ["Suscribirse a cambios de datos en tiempo real", "Un índice", "Un backup", "Un shard"], 0, "Permite reaccionar a inserts/updates/deletes."],
      ["¿Qué implica la consistencia eventual al leer de secundarios?", ["Pueden devolver datos ligeramente atrasados respecto al primario", "Siempre al día", "No se puede leer", "Cifra"], 0, "Leer de secundarios mejora escalado a costa de frescura."],
      ["¿Qué es hashed sharding y cuándo usarlo?", ["Distribuye por hash de la clave para repartir escrituras uniformemente", "Ordena físicamente", "Un índice de texto", "Un backup"], 0, "Evita hotspots de claves monotónicas."],
    ]),
    fase(10, [
      ["¿Qué trade-off central hay entre embedding y referencing a escala?", ["Embedding: lecturas rápidas pero duplicación/límites; referencing: normalizado pero requiere joins", "Ninguno", "Referencing es siempre mejor", "Embedding no tiene límites"], 0, "Se elige según patrón de acceso y crecimiento."],
      ["¿Por qué MongoDB prioriza el diseño 'schema-on-read' guiado por queries?", ["Se modela para el patrón de acceso, no para la normalización teórica", "Para ahorrar espacio siempre", "Por ACID", "Por cifrado"], 0, "El rendimiento depende de cómo se accede a los datos."],
      ["¿Qué garantiza una transacción multi-documento en cuanto a costo?", ["ACID a cambio de mayor latencia y locking; usar con moderación", "Es gratis", "No existe", "Solo lectura"], 0, "Las transacciones tienen costo; el diseño suele evitarlas."],
      ["¿Qué problema resuelve el patrón outlier/extended reference?", ["Manejar documentos atípicos o denormalizar campos frecuentes de referencias", "Un índice de texto", "Un shard", "Un backup"], 0, "Optimiza casos donde embedding puro no encaja."],
      ["¿Por qué la shard key no se puede cambiar fácilmente tras crearla (históricamente)?", ["Reparticionar datos es costoso; una mala elección es difícil de revertir", "Se cambia gratis", "No afecta", "Cifra"], 0, "Por eso elegir bien la shard key es crítico desde el inicio."],
    ]),
  ],
);

const prisma: QuizTema = tema(
  "prisma",
  "Prisma ORM",
  "ORM type-safe para TypeScript: schema, migraciones, cliente y relaciones.",
  [
    fase(1, [
      ["¿Qué es Prisma?", ["Un ORM type-safe para Node/TypeScript", "Una base de datos", "Un servidor web", "Un navegador"], 0, "Prisma mapea la DB a un cliente tipado."],
      ["¿En qué archivo se define el modelo de datos?", ["schema.prisma", "prisma.json", "models.ts", "db.config"], 0, "schema.prisma describe modelos y datasource."],
      ["¿Qué comando genera el cliente?", ["prisma build", "prisma generate", "prisma make", "prisma init"], 1, "prisma generate crea el cliente tipado."],
      ["¿Cómo se declara una entidad?", ["class", "model", "table", "entity"], 1, "La palabra clave model define una tabla."],
      ["¿Qué representa cada model?", ["Una tabla de la base de datos", "Una consulta", "Un índice", "Un backup"], 0, "Cada model se corresponde con una tabla."],
    ]),
    fase(2, [
      ["¿Qué atributo marca la clave primaria?", ["@unique", "@id", "@pk", "@primary"], 1, "@id define la clave primaria."],
      ["¿Qué atributo impone unicidad?", ["@id", "@unique", "@default", "@map"], 1, "@unique evita valores duplicados."],
      ["¿Qué atributo da un valor por defecto?", ["@default", "@init", "@value", "@auto"], 0, "@default(...) fija el valor inicial."],
      ["¿Cómo se lee un registro por id?", ["findUnique", "getById", "selectOne", "queryId"], 0, "findUnique busca por clave única."],
      ["¿Cómo se crean registros?", ["create", "insert", "add", "new"], 0, "db.model.create({ data }) inserta."],
    ]),
    fase(3, [
      ["¿Cómo se listan varios registros?", ["findMany", "getAll", "selectMany", "list"], 0, "findMany devuelve un array de registros."],
      ["¿Cómo se actualiza un registro?", ["update", "set", "modify", "change"], 0, "update({ where, data }) modifica."],
      ["¿Cómo se elimina un registro?", ["delete", "remove", "drop", "destroy"], 0, "delete({ where }) borra el registro."],
      ["¿Qué opción filtra resultados?", ["where", "filter", "match", "query"], 0, "where define las condiciones."],
      ["¿Qué opción selecciona campos específicos?", ["select", "fields", "pick", "only"], 0, "select limita las columnas devueltas."],
    ]),
    fase(4, [
      ["¿Qué opción incluye relaciones en la consulta?", ["include", "join", "with", "relations"], 0, "include trae datos relacionados."],
      ["¿Qué atributo define una relación entre modelos?", ["@relation", "@link", "@ref", "@join"], 0, "@relation especifica claves de la relación."],
      ["¿Qué comando aplica cambios de esquema en desarrollo?", ["prisma migrate dev", "prisma push all", "prisma sync", "prisma apply"], 0, "migrate dev crea y aplica migraciones."],
      ["¿Qué hace prisma db push?", ["Sincroniza el esquema con la DB sin crear migración", "Genera el cliente", "Hace backup", "Crea seeds"], 0, "db push es útil en prototipos."],
      ["¿Qué es un campo opcional en Prisma?", ["Se marca con ? (permite null)", "Con @optional", "Con @null", "Con default null"], 0, "String? indica un campo anulable."],
    ]),
    fase(5, [
      ["¿Qué método inserta o actualiza según exista?", ["upsert", "insertOrUpdate", "merge", "save"], 0, "upsert combina create y update."],
      ["¿Qué opción ordena resultados?", ["orderBy", "sort", "arrange", "order"], 0, "orderBy define el orden."],
      ["¿Qué opciones paginan resultados?", ["skip y take", "offset y limit", "from y to", "page y size"], 0, "skip/take controlan la paginación."],
      ["¿Qué método ejecuta varias operaciones atómicamente?", ["$transaction", "$atomic", "$batch", "$all"], 0, "$transaction agrupa operaciones."],
      ["¿Qué método cuenta registros?", ["count", "size", "length", "total"], 0, "count() devuelve la cantidad."],
    ]),
    fase(6, [
      ["¿Por qué usar $transaction para operaciones dependientes?", ["Garantiza que todas se apliquen o ninguna (atomicidad)", "Es más rápido", "Cifra", "Cachea"], 0, "Evita estados inconsistentes ante fallos parciales."],
      ["¿Qué problema resuelve el connection pooling en serverless con Prisma?", ["Evitar agotar conexiones al abrir una por invocación", "Cifra", "Crea índices", "Nada"], 0, "Se usa un pooler (p.ej. PgBouncer/Accelerate)."],
      ["¿Qué es una migración en Prisma?", ["Un archivo SQL versionado que evoluciona el esquema", "Un backup", "Un índice", "Un seed"], 0, "Las migraciones registran cambios reproducibles."],
      ["¿Qué hace prisma migrate deploy?", ["Aplica migraciones pendientes en producción", "Crea nuevas migraciones", "Genera el cliente", "Hace seed"], 0, "deploy solo aplica lo ya versionado."],
      ["¿Qué es el problema N+1 con include vs. consultas sueltas?", ["Cargar relaciones en bucle genera muchas queries; include las agrupa", "No existe", "include lo empeora", "Cifra"], 0, "include/relationLoadStrategy evita el N+1."],
    ]),
    fase(7, [
      ["¿Qué garantiza la seguridad de tipos de Prisma Client?", ["Errores en compilación si consultas campos/relaciones inexistentes", "Más velocidad de red", "Cifrado", "Backups"], 0, "El cliente se genera desde el esquema tipado."],
      ["¿Qué es $queryRaw y cuándo usarlo?", ["Ejecutar SQL crudo (parametrizado) para casos no cubiertos por el API", "Para todo siempre", "Para cifrar", "Para seeds"], 0, "Útil para consultas avanzadas manteniendo parámetros seguros."],
      ["¿Por qué preferir $queryRaw parametrizado sobre concatenar SQL?", ["Previene inyección SQL", "Es más lento", "No usa índices", "Cifra"], 0, "Los parámetros separan datos de la consulta."],
      ["¿Qué controla relationLoadStrategy (join vs. query)?", ["Cómo se cargan las relaciones: con JOIN o consultas separadas", "El cifrado", "Los backups", "Los índices"], 0, "Permite optimizar la carga de relaciones."],
      ["¿Qué es el middleware/extends de Prisma Client?", ["Interceptar o extender operaciones (logging, soft delete)", "Un índice", "Un backup", "Un seed"], 0, "Client extensions añaden lógica transversal."],
    ]),
    fase(8, [
      ["¿Qué diferencia hay entre migrate dev y db push en el flujo de trabajo?", ["migrate dev versiona cambios; db push sincroniza sin historial", "Son iguales", "db push versiona", "migrate dev no aplica"], 0, "db push sirve para prototipar sin migraciones."],
      ["¿Qué riesgo tiene una migración destructiva (drop de columna)?", ["Pérdida de datos; requiere revisión y respaldo", "Ninguno", "Solo lentitud", "Cifra"], 0, "Prisma advierte sobre cambios destructivos."],
      ["¿Qué es una transacción interactiva ($transaction async)?", ["Ejecutar lógica entre operaciones dentro de la misma transacción", "Solo un array de queries", "Un backup", "Un índice"], 0, "Permite condicionar operaciones según resultados previos."],
      ["¿Por qué instanciar PrismaClient una sola vez (singleton) en dev?", ["El hot-reload crearía muchas conexiones y las agotaría", "Es más lento", "Cifra", "Nada"], 0, "Se cachea en globalThis para evitar fugas de conexión."],
      ["¿Qué ventaja da select/omit sobre traer todo el modelo?", ["Menos datos transferidos y consultas más eficientes", "Rompe tipos", "Cifra", "Nada"], 0, "Traer solo lo necesario mejora rendimiento."],
    ]),
    fase(9, [
      ["¿Qué problema resuelve Prisma Accelerate/Data Proxy en serverless?", ["Pooling y caché de conexiones para entornos sin estado", "Cifra la DB", "Crea índices", "Hace backups"], 0, "Evita agotar conexiones en funciones efímeras."],
      ["¿Cómo evita Prisma el N+1 en relaciones anidadas?", ["Con include/relationLoadStrategy que agrupa la carga", "No lo evita", "Con más queries", "Cifrando"], 0, "Carga las relaciones de forma agrupada."],
      ["¿Qué trade-off tiene $queryRaw frente al API tipado?", ["Máxima flexibilidad a costa de perder seguridad de tipos y portabilidad", "Solo ventajas", "Es más seguro por tipos", "Nada"], 0, "El SQL crudo no se valida por tipos automáticamente."],
      ["¿Por qué las migraciones deben ser deterministas y versionadas?", ["Para reproducir el mismo esquema en todos los entornos del equipo", "Por cifrado", "Por índices", "Por backups"], 0, "El historial versionado evita divergencias."],
      ["¿Qué es optimistic concurrency y cómo se modela?", ["Detectar conflictos con un campo version/updatedAt en el where del update", "Bloqueos siempre", "Un índice", "Un backup"], 0, "Evita sobrescribir cambios concurrentes sin bloquear."],
    ]),
    fase(10, [
      ["¿Qué trade-off central tiene un ORM como Prisma frente a SQL puro?", ["Productividad y seguridad de tipos a costa de menos control fino en casos extremos", "Solo ventajas", "Solo desventajas", "Ninguno"], 0, "Para casos límite se combina con $queryRaw."],
      ["¿Por qué el connection pooling es especialmente crítico con Prisma en Vercel/serverless?", ["Cada función puede abrir conexiones; sin pooler se agota la DB", "No aplica", "Cifra", "Crea índices"], 0, "El entorno efímero multiplica conexiones."],
      ["¿Qué garantiza mantener el schema.prisma como fuente de verdad?", ["Cliente, tipos y migraciones derivan de un único esquema coherente", "Menos seguridad", "Más SQL manual", "Nada"], 0, "Un solo origen evita desincronización."],
      ["¿Qué riesgo introduce editar la DB por fuera de las migraciones de Prisma?", ["Drift entre esquema real y migraciones, rompiendo despliegues", "Ninguno", "Mejora el rendimiento", "Cifra"], 0, "El drift causa migraciones fallidas o inconsistencias."],
      ["¿Por qué revisar el SQL generado por una migración antes de aplicarla en prod?", ["Detectar operaciones destructivas o bloqueos largos sobre tablas grandes", "Es innecesario", "Cifra", "Reduce tipos"], 0, "Algunas migraciones pueden bloquear o perder datos."],
    ]),
  ],
);

const redis: QuizTema = tema(
  "redis",
  "Redis",
  "Almacén clave-valor en memoria: estructuras, caché, TTL, pub/sub y persistencia.",
  [
    fase(1, [
      ["¿Qué tipo de almacenamiento es Redis?", ["Clave-valor en memoria", "Relacional en disco", "De documentos", "En columnas"], 0, "Redis guarda datos en memoria para baja latencia."],
      ["¿Cuál es su puerto por defecto?", ["5432", "6379", "27017", "3306"], 1, "Redis escucha en el 6379."],
      ["¿Qué comando fija un valor?", ["PUT", "SET", "ADD", "STORE"], 1, "SET clave valor almacena un string."],
      ["¿Qué comando lee un valor?", ["READ", "GET", "FETCH", "SELECT"], 1, "GET clave devuelve el valor."],
      ["¿Para qué se usa Redis comúnmente?", ["Caché y datos de acceso rápido", "Almacenar archivos grandes", "Renderizar HTML", "Compilar código"], 0, "Es habitual como caché de baja latencia."],
    ]),
    fase(2, [
      ["¿Qué comando fija expiración a una clave?", ["EXPIRE", "TIMEOUT", "TTLSET", "AGE"], 0, "EXPIRE clave segundos define el TTL."],
      ["¿Qué comando borra una clave?", ["REMOVE", "DEL", "DROP", "CLEAR"], 1, "DEL elimina una o más claves."],
      ["¿Qué estructura es una lista ordenada de elementos?", ["Hash", "List", "Set", "String"], 1, "List almacena elementos en orden (LPUSH/RPUSH)."],
      ["¿Qué estructura guarda campos y valores como un objeto?", ["Hash", "List", "Set", "String"], 0, "Hash mapea campos a valores (HSET/HGET)."],
      ["¿Qué estructura guarda elementos únicos sin orden?", ["List", "Set", "Hash", "String"], 1, "Set almacena miembros únicos."],
    ]),
    fase(3, [
      ["¿Qué estructura asocia miembros a una puntuación ordenable?", ["Sorted Set (ZSET)", "List", "Hash", "String"], 0, "ZSET ordena por score (rankings)."],
      ["¿Qué comando incrementa un contador atómicamente?", ["ADD", "INCR", "PLUS", "UP"], 1, "INCR aumenta un entero de forma atómica."],
      ["¿Qué es el TTL de una clave?", ["El tiempo restante antes de expirar", "Su tamaño", "Su tipo", "Su score"], 0, "TTL devuelve los segundos hasta el vencimiento."],
      ["¿Qué patrón de caché consulta Redis y si falla va a la DB?", ["cache-aside", "write-behind", "pub/sub", "sharding"], 0, "Cache-aside carga bajo demanda."],
      ["¿Qué comando añade a una lista por la izquierda?", ["LPUSH", "APPEND", "PUSHLEFT", "ADDL"], 0, "LPUSH inserta al inicio de la lista."],
    ]),
    fase(4, [
      ["¿Qué mecanismo de mensajería ofrece Redis?", ["Pub/Sub", "SQL joins", "Triggers", "Vistas"], 0, "Publish/Subscribe distribuye mensajes a canales."],
      ["¿Qué comando publica en un canal?", ["SEND", "PUBLISH", "EMIT", "POST"], 1, "PUBLISH canal mensaje envía a suscriptores."],
      ["¿Es Redis single-thread para comandos?", ["No", "Sí, procesa comandos en un hilo principal", "Depende del SO", "Solo en cluster"], 1, "Su modelo single-thread simplifica la atomicidad."],
      ["¿Qué comando fija valor solo si no existe?", ["SETNX", "SETIF", "ADDNEW", "PUTNX"], 0, "SETNX (o SET NX) evita sobrescribir."],
      ["¿Qué es la evicción de claves?", ["Descartar claves cuando se llena la memoria (según política)", "Cifrarlas", "Duplicarlas", "Indexarlas"], 0, "La política LRU/LFU decide qué eliminar."],
    ]),
    fase(5, [
      ["¿Qué persistencia hace snapshots periódicos?", ["RDB", "AOF", "WAL", "BSON"], 0, "RDB guarda una imagen del dataset."],
      ["¿Qué persistencia registra cada escritura?", ["RDB", "AOF", "MVCC", "GIN"], 1, "AOF (append-only file) registra operaciones."],
      ["¿Qué trade-off tiene RDB frente a AOF?", ["RDB: recuperación rápida pero puede perder datos recientes; AOF: más durable pero mayor tamaño", "Son iguales", "AOF pierde más", "RDB es más durable"], 0, "Se pueden combinar ambos."],
      ["¿Qué comando ejecuta operaciones de forma atómica agrupada?", ["MULTI/EXEC (transacción)", "BEGIN/COMMIT SQL", "LOCK", "SYNC"], 0, "MULTI encola y EXEC ejecuta atómicamente."],
      ["¿Qué es una operación atómica en Redis?", ["Se ejecuta por completo sin interrupción de otros comandos", "Se ejecuta en paralelo", "Se cifra", "Se cachea"], 0, "El modelo single-thread garantiza atomicidad por comando."],
    ]),
    fase(6, [
      ["¿Por qué INCR es seguro para contadores concurrentes?", ["Es atómico: no hay condición de carrera entre lecturas/escrituras", "Usa locks explícitos", "Cifra", "Cachea"], 0, "Evita el patrón inseguro leer-modificar-escribir."],
      ["¿Qué es un script Lua en Redis y su ventaja?", ["Ejecuta varios comandos atómicamente en el servidor", "Cifra", "Un backup", "Un índice"], 0, "Lua agrupa lógica en una operación atómica."],
      ["¿Qué estructura usarías para un ranking de puntuaciones?", ["Sorted Set (ZSET)", "List", "Hash", "String"], 0, "ZADD/ZRANGE gestionan rankings ordenados."],
      ["¿Qué es un TTL con expiración para implementar rate limiting?", ["Contar peticiones en una ventana usando INCR + EXPIRE", "Un backup", "Un índice", "Un pub/sub"], 0, "Es el patrón clásico de límite por ventana."],
      ["¿Qué estructura estima cardinalidad con poca memoria?", ["HyperLogLog", "List", "Hash", "String"], 0, "HyperLogLog cuenta elementos únicos aproximadamente."],
    ]),
    fase(7, [
      ["¿Qué política de evicción conviene para una caché pura?", ["allkeys-lru (descarta las menos usadas)", "noeviction", "Ninguna", "RDB"], 0, "LRU prioriza mantener las claves activas."],
      ["¿Qué problema tiene noeviction al llenarse la memoria?", ["Las escrituras empiezan a fallar con error OOM", "Borra todo", "Cifra", "Nada"], 0, "Sin evicción, no hay espacio para nuevas claves."],
      ["¿Qué es Redis Cluster?", ["Particiona el keyspace en slots entre varios nodos (sharding)", "Un backup", "Un índice", "Un pub/sub"], 0, "Escala horizontalmente distribuyendo claves."],
      ["¿Qué son los hash slots en Redis Cluster?", ["16384 slots que reparten las claves entre nodos", "Índices SQL", "Backups", "Canales"], 0, "La clave se asigna a un slot por CRC16."],
      ["¿Qué es una operación bloqueante como BLPOP?", ["Espera hasta que haya un elemento (útil para colas)", "Cifra", "Un backup", "Un índice"], 0, "Permite implementar colas productor-consumidor."],
    ]),
    fase(8, [
      ["¿Qué es cache stampede en Redis y cómo mitigarlo?", ["Muchas peticiones recalculan al expirar una clave; se usa lock/single-flight o TTL con jitter", "No existe", "Más réplicas", "Cifrado"], 0, "Coordinar el recálculo evita la avalancha."],
      ["¿Qué garantiza un lock distribuido bien implementado (p.ej. Redlock)?", ["Exclusión mutua entre procesos con expiración para evitar deadlocks", "Cifrado", "Backups", "Índices"], 0, "Debe manejar TTL y liberación segura."],
      ["¿Por qué SETEX/SET con EX es preferible para caché con expiración?", ["Fija valor y TTL atómicamente, evitando claves sin expirar", "Es más lento", "Cifra", "Nada"], 0, "Evita el riesgo de olvidar el EXPIRE."],
      ["¿Qué diferencia hay entre Redis Streams y Pub/Sub?", ["Streams persisten y permiten grupos de consumidores; Pub/Sub es efímero", "Son iguales", "Pub/Sub persiste", "Streams no ordena"], 0, "Streams son aptos para colas duraderas."],
      ["¿Qué es un consumer group en Redis Streams?", ["Reparte mensajes entre consumidores con seguimiento de entrega", "Un backup", "Un índice", "Un canal simple"], 0, "Permite procesamiento distribuido y reintentos."],
    ]),
    fase(9, [
      ["¿Por qué un comando O(N) sobre una estructura enorme puede dañar a todos?", ["El modelo single-thread bloquea el resto de comandos mientras se ejecuta", "No afecta", "Va en paralelo", "Cifra"], 0, "Comandos como KEYS * en producción son peligrosos."],
      ["¿Qué alternativa segura a KEYS existe para iterar?", ["SCAN (iteración incremental sin bloquear)", "KEYS *", "FLUSHALL", "GETALL"], 0, "SCAN recorre en cursores pequeños."],
      ["¿Qué trade-off tiene AOF con fsync always?", ["Máxima durabilidad a costa de menor rendimiento de escritura", "Menos durable", "Sin costo", "Cifra"], 0, "El fsync por comando es seguro pero lento."],
      ["¿Qué problema resuelve la replicación en Redis?", ["Alta disponibilidad y escalado de lecturas con réplicas", "Cifrado", "Índices", "Backups únicamente"], 0, "Las réplicas ofrecen failover y lecturas escaladas."],
      ["¿Qué es la consistencia de Redis Cluster ante particiones?", ["Puede perder escrituras no replicadas al fallar un primario (no es CP fuerte)", "Consistencia fuerte total", "No replica", "Cifra"], 0, "Prioriza disponibilidad; existe ventana de pérdida."],
    ]),
    fase(10, [
      ["¿Qué trade-off central tiene almacenar en memoria (Redis)?", ["Latencia mínima a cambio de costo de RAM y necesidad de estrategia de persistencia/evicción", "Solo ventajas", "Solo desventajas", "Ninguno"], 0, "La memoria es rápida pero limitada y volátil."],
      ["¿Por qué el modelo single-thread simplifica pero también limita a Redis?", ["Garantiza atomicidad sin locks, pero un comando lento afecta a todos", "Es multihilo", "No es atómico", "Cifra"], 0, "El diseño exige comandos rápidos y estructuras adecuadas."],
      ["¿Cuándo Redis NO debe ser la única fuente de verdad?", ["Cuando los datos deben ser durables/consistentes; se combina con una DB primaria", "Siempre es fuente de verdad", "Nunca cachea", "Solo con cluster"], 0, "Como caché, respalda pero no reemplaza la DB durable."],
      ["¿Qué garantiza usar SET con NX+EX para un lock simple?", ["Adquirir el lock y su expiración atómicamente, evitando deadlocks", "Menos memoria", "Cifrado", "Nada"], 0, "Es la base de un lock básico correcto."],
      ["¿Qué problema resuelve Redis Streams frente a listas para colas?", ["Persistencia, IDs, grupos de consumidores y reintentos gestionados", "Nada nuevo", "Menos memoria siempre", "Cifrado"], 0, "Streams están diseñados para mensajería duradera."],
    ]),
  ],
);

export const TEMAS_BASES_DATOS: QuizTema[] = [sql, postgresql, mongodb, prisma, redis];
