import { fase, tema, type QuizTema } from "./tipos";

// Categoría: Frameworks. Temas: React, Next.js, Vue, Angular, Svelte.

const react: QuizTema = tema(
  "react",
  "React",
  "Componentes, JSX, estado, props, hooks y renderizado declarativo.",
  [
    fase(1, [
      ["¿Qué es React?", ["Una base de datos", "Una librería para construir interfaces con componentes", "Un lenguaje", "Un servidor"], 1, "React es una librería de UI basada en componentes."],
      ["¿Qué es JSX?", ["Un tipo de CSS", "Sintaxis que mezcla marcado con JavaScript", "Un ORM", "Un bundler"], 1, "JSX describe la UI dentro de JavaScript."],
      ["¿Cómo se pasan datos de un componente padre a un hijo?", ["Con estado", "Con props", "Con context siempre", "Con refs"], 1, "Las props transmiten datos hacia abajo."],
      ["¿Qué hook maneja estado local?", ["useEffect", "useState", "useRef", "useMemo"], 1, "useState agrega estado a un componente funcional."],
      ["¿Cómo debe empezar el nombre de un componente?", ["En minúscula", "Con mayúscula", "Con guion", "Con número"], 1, "Los componentes se nombran con mayúscula inicial."],
    ]),
    fase(2, [
      ["¿Son las props mutables por el hijo?", ["Sí", "No, son de solo lectura", "Solo con let", "Depende del hook"], 1, "Las props no deben modificarse en el hijo."],
      ["¿Qué hook ejecuta efectos secundarios?", ["useState", "useEffect", "useContext", "useId"], 1, "useEffect sincroniza con sistemas externos."],
      ["¿Qué prop identifica elementos en una lista?", ["id", "key", "ref", "index"], 1, "key ayuda a React a reconciliar listas."],
      ["¿Cómo se renderiza condicionalmente?", ["Con for", "Con && o ternario en JSX", "Con while", "Con switch en HTML"], 1, "Se usa {cond && <X/>} o ternario."],
      ["¿Qué retorna un componente funcional?", ["Un string", "JSX (elementos de React)", "Un objeto DOM", "Una promesa"], 1, "Devuelve el árbol de UI en JSX."],
    ]),
    fase(3, [
      ["¿Qué hace el array de dependencias de useEffect?", ["Nada", "Controla cuándo se re-ejecuta el efecto", "Ordena efectos", "Crea estado"], 1, "El efecto corre cuando cambia alguna dependencia."],
      ["¿Qué pasa si useEffect no tiene array de dependencias?", ["Corre una vez", "Corre en cada render", "Nunca corre", "Da error"], 1, "Sin array, se ejecuta tras cada render."],
      ["¿Cómo se actualiza el estado basándose en el previo?", ["setX(x+1)", "setX(prev => prev+1)", "x++", "mutar x"], 1, "La forma funcional evita valores obsoletos."],
      ["¿Qué es el 'lifting state up'?", ["Mover el estado al ancestro común para compartirlo", "Usar refs", "Un HOC", "Un portal"], 0, "Se eleva el estado al padre que ambos hijos comparten."],
      ["¿Qué hook referencia un elemento del DOM sin re-render?", ["useState", "useRef", "useMemo", "useEffect"], 1, "useRef guarda un valor mutable persistente."],
    ]),
    fase(4, [
      ["¿Qué hook memoiza un valor calculado?", ["useEffect", "useMemo", "useRef", "useState"], 1, "useMemo evita recalcular en cada render."],
      ["¿Qué hook memoiza una función?", ["useMemo", "useCallback", "useRef", "useId"], 1, "useCallback conserva la misma referencia de función."],
      ["¿Qué es el Context?", ["Una forma de compartir datos sin pasar props manualmente", "Un ORM", "Un router", "Un bundler"], 0, "Context evita el prop drilling."],
      ["¿Qué hace la función de limpieza retornada por useEffect?", ["Nada", "Se ejecuta antes del próximo efecto o al desmontar", "Corre solo una vez", "Crea estado"], 1, "Sirve para cancelar suscripciones/timers."],
      ["¿Qué es un componente controlado?", ["Su valor lo maneja el estado de React", "Usa el DOM directamente", "No tiene props", "Es un HOC"], 0, "El input controlado refleja el estado."],
    ]),
    fase(5, [
      ["¿Qué es un custom hook?", ["Una función que empieza con 'use' y reutiliza lógica con hooks", "Un componente", "Un contexto", "Un HOC"], 0, "Encapsula lógica de estado reutilizable."],
      ["¿Qué hook maneja estado complejo con un reducer?", ["useState", "useReducer", "useMemo", "useRef"], 1, "useReducer centraliza transiciones de estado."],
      ["¿Por qué las listas necesitan keys estables?", ["Para estilos", "Para que React identifique y preserve elementos correctamente", "Para SEO", "Para el router"], 1, "Keys inestables causan remounts y bugs de estado."],
      ["¿Qué provoca un bucle infinito con useEffect?", ["Un array vacío", "Actualizar un estado del que depende el efecto sin control", "Usar useRef", "Un ternario"], 1, "El estado cambia → efecto corre → estado cambia..."],
      ["¿Qué es el 'reconciliation'?", ["El algoritmo que compara el virtual DOM para aplicar cambios mínimos", "Un router", "Un hook", "Un bundler"], 0, "React diferencia el árbol virtual y actualiza lo necesario."],
    ]),
    fase(6, [
      ["¿Qué son las 'rules of hooks'?", ["Llamar hooks solo en el nivel superior y desde componentes/hooks", "Usar hooks en bucles", "Usarlos en clases", "No usar arrays"], 0, "No llamarlos condicionalmente ni dentro de loops."],
      ["¿Qué hace React.memo?", ["Memoiza el render de un componente por sus props", "Crea estado", "Un router", "Un contexto"], 0, "Evita re-render si las props no cambian."],
      ["¿Qué problema resuelve useMemo/useCallback?", ["Evitar cálculos y referencias nuevas costosas en cada render", "El SEO", "El routing", "La hidratación"], 0, "Estabiliza valores/funciones para optimizar."],
      ["¿Qué es un portal?", ["Renderizar hijos en un nodo DOM fuera del padre", "Un router", "Un hook", "Un contexto"], 0, "createPortal renderiza fuera de la jerarquía DOM del padre."],
      ["¿Qué es un error boundary?", ["Un componente que captura errores de render de sus hijos", "Un try/catch de hooks", "Un router", "Un portal"], 0, "Los error boundaries evitan que un error tumbe toda la app."],
    ]),
    fase(7, [
      ["¿Qué garantiza el batching de actualizaciones de estado?", ["Agrupar varios setState en un solo re-render", "Ordenar efectos", "Evitar hooks", "Un router"], 0, "React agrupa updates para minimizar renders."],
      ["¿Qué hace useLayoutEffect frente a useEffect?", ["Corre de forma síncrona tras las mutaciones del DOM, antes de pintar", "Es idéntico", "Nunca corre", "Solo en el servidor"], 0, "Útil para medir el DOM antes del paint."],
      ["¿Qué es 'derivar estado' y por qué evitar duplicarlo?", ["Calcular durante el render en vez de guardarlo redundante", "Usar refs", "Un HOC", "Un portal"], 0, "El estado duplicado se desincroniza; mejor derivar."],
      ["¿Qué es el patrón de renderizado con children as a function?", ["Pasar una función como children para compartir lógica", "Un HOC", "Un portal", "Un contexto"], 0, "Es el patrón render props."],
      ["¿Qué es la 'stale closure' en hooks?", ["Un efecto/callback que captura un valor viejo del render anterior", "Un error de red", "Un portal", "Un memo"], 0, "Ocurre al no incluir dependencias actualizadas."],
    ]),
    fase(8, [
      ["¿Qué hace useTransition?", ["Marca actualizaciones como no urgentes para no bloquear la UI", "Crea rutas", "Memoiza", "Hace fetch"], 0, "Prioriza la interacción sobre renders costosos."],
      ["¿Qué es el concurrent rendering?", ["React puede interrumpir y reanudar el render para mantener fluidez", "Renderizar en varios hilos del SO", "Un router", "Un bundler"], 0, "Permite trabajo interrumpible y prioridades."],
      ["¿Qué hace useDeferredValue?", ["Difiere un valor para no recalcular UI costosa de inmediato", "Crea estado", "Hace fetch", "Un portal"], 0, "Mantiene la UI responsiva difiriendo actualizaciones."],
      ["¿Qué es la hidratación?", ["Adjuntar interactividad de React a HTML renderizado en servidor", "Renderizar en cliente solamente", "Un router", "Un memo"], 0, "Hydration conecta el HTML del SSR con React."],
      ["¿Qué son los Server Components de React?", ["Componentes que se renderizan en el servidor y no envían su JS al cliente", "Componentes con estado", "Portales", "HOCs"], 0, "Reducen el bundle ejecutándose en el servidor."],
    ]),
    fase(9, [
      ["¿Qué garantiza el hook useSyncExternalStore?", ["Suscribirse a stores externos de forma segura con concurrencia", "Crear rutas", "Memoizar", "Hacer fetch"], 0, "Evita tearing al leer stores externos."],
      ["¿Qué es 'tearing' en UI concurrente?", ["Ver estados inconsistentes de un mismo dato en un render", "Un error de red", "Un portal roto", "Un memo obsoleto"], 0, "El render concurrente puede mostrar datos desincronizados sin cuidado."],
      ["¿Qué diferencia hay entre estado de servidor y de cliente?", ["El de servidor es remoto/cacheable (React Query); el de cliente es local", "Ninguna", "El de cliente es remoto", "Ambos son props"], 0, "Distinguirlos guía la arquitectura de datos."],
      ["¿Por qué la key no debe ser el índice del array en listas dinámicas?", ["Al reordenar/insertar, el estado se asocia al elemento equivocado", "Es más lento", "Rompe el SEO", "No se puede"], 0, "El índice cambia al mutar el array, confundiendo la reconciliación."],
      ["¿Qué es el patrón compound components?", ["Componentes que colaboran compartiendo estado implícito vía context", "Un HOC", "Un portal", "Un memo"], 0, "Ej.: <Tabs><Tab/></Tabs> comparten estado por context."],
    ]),
    fase(10, [
      ["¿Qué problema resuelven las Actions y useActionState (React 19)?", ["Gestionar transiciones async de formularios/mutaciones con estado pendiente", "El routing", "El SEO puro", "Los portales"], 0, "Simplifican mutaciones con estados de carga y error."],
      ["¿Qué hace el hook use (React 19) con una promesa?", ["Suspende hasta resolverla e integra con Suspense", "Crea estado", "Un router", "Un memo"], 0, "use() permite leer promesas/context durante el render."],
      ["¿Por qué los Server Components no pueden usar useState?", ["No se hidratan ni tienen ciclo de vida interactivo en el cliente", "Son más lentos", "Falta el bundler", "Usan portales"], 0, "El estado interactivo pertenece a los Client Components."],
      ["¿Qué es el 'waterfall' de datos y cómo evitarlo?", ["Fetches encadenados secuenciales; se evita paralelizando o con Suspense/RSC", "Un memo", "Un portal", "Un HOC"], 0, "Paralelizar peticiones evita esperas en cascada."],
      ["¿Qué garantiza la inmutabilidad del estado en React?", ["Detectar cambios por referencia y renders predecibles", "Menos memoria", "SEO", "Rutas"], 0, "Mutar en el lugar rompe la detección de cambios."],
    ]),
  ],
);

const nextjs: QuizTema = tema(
  "nextjs",
  "Next.js",
  "App Router, Server/Client Components, rutas, renderizado y APIs.",
  [
    fase(1, [
      ["¿Qué es Next.js?", ["Un framework full-stack sobre React", "Una base de datos", "Un lenguaje", "Un ORM"], 0, "Next.js añade routing, SSR y APIs a React."],
      ["En el App Router, ¿qué carpeta define las rutas?", ["pages", "app", "routes", "src/views"], 1, "La carpeta app contiene rutas basadas en archivos."],
      ["¿Qué archivo define la UI de una ruta?", ["route.tsx", "page.tsx", "index.tsx", "view.tsx"], 1, "page.tsx renderiza la ruta."],
      ["¿Qué archivo envuelve rutas con UI compartida?", ["wrapper.tsx", "layout.tsx", "shell.tsx", "root.tsx"], 1, "layout.tsx define estructura común y persistente."],
      ["¿Con qué se navega entre rutas sin recargar?", ["<a>", "<Link>", "<nav>", "<route>"], 1, "<Link> hace navegación del lado del cliente."],
    ]),
    fase(2, [
      ["Por defecto en el App Router, ¿los componentes son?", ["Client Components", "Server Components", "Estáticos siempre", "APIs"], 1, "Son Server Components salvo que se indique 'use client'."],
      ["¿Qué directiva marca un Client Component?", ["'use server'", "'use client'", "'client only'", "'react'"], 1, "'use client' habilita interactividad en el navegador."],
      ["¿Dónde se define un endpoint de API en el App Router?", ["api.tsx", "route.ts", "server.ts", "handler.ts"], 1, "route.ts exporta GET/POST, etc."],
      ["¿Cómo se crea una ruta dinámica?", ["Carpeta (id)", "Carpeta [id]", "Archivo id.tsx", "Query ?id"], 1, "Los corchetes [id] definen segmentos dinámicos."],
      ["¿Qué archivo muestra un estado de carga?", ["spinner.tsx", "loading.tsx", "wait.tsx", "suspense.tsx"], 1, "loading.tsx se muestra vía Suspense mientras carga."],
    ]),
    fase(3, [
      ["¿Qué archivo maneja errores de un segmento?", ["catch.tsx", "error.tsx", "fail.tsx", "boundary.tsx"], 1, "error.tsx es un error boundary del segmento."],
      ["¿Qué archivo define un 404 personalizado?", ["404.tsx", "not-found.tsx", "missing.tsx", "empty.tsx"], 1, "not-found.tsx renderiza la página no encontrada."],
      ["¿Pueden los Server Components acceder a la base de datos directamente?", ["No, nunca", "Sí, corren en el servidor", "Solo con fetch", "Solo con 'use client'"], 1, "Los Server Components pueden consultar datos server-side."],
      ["¿Qué son los route groups (carpeta)?", ["Agrupan rutas sin afectar la URL", "Rutas dinámicas", "APIs", "Layouts globales"], 0, "(grupo) organiza sin agregar segmento a la URL."],
      ["¿Cómo se leen params en una page async?", ["De props (params)", "De window", "De cookies", "De un hook global"], 0, "La page recibe { params } (Promise en versiones recientes)."],
    ]),
    fase(4, [
      ["¿Qué es una Server Action?", ["Función servidor invocable desde el cliente para mutar datos", "Un endpoint REST", "Un hook", "Un layout"], 0, "'use server' permite mutaciones sin escribir una API."],
      ["¿Qué hace generateStaticParams?", ["Predefine rutas dinámicas para prerender estático", "Crea APIs", "Define layouts", "Maneja errores"], 0, "Genera las rutas a construir en build."],
      ["¿Cómo se define metadata para SEO?", ["export const metadata / generateMetadata", "<head> manual", "un hook", "route.ts"], 0, "Next.js expone la API de Metadata."],
      ["¿Qué diferencia hay entre SSR y SSG?", ["SSR renderiza por request; SSG en build", "Son iguales", "SSG por request", "SSR en cliente"], 0, "SSG pre-genera; SSR genera al solicitar."],
      ["¿Qué es el prefetching de <Link>?", ["Precarga la ruta destino para navegación instantánea", "Un cache de API", "Un layout", "Un error boundary"], 0, "Next precarga rutas visibles para acelerar la navegación."],
    ]),
    fase(5, [
      ["¿Qué hace revalidate en el fetch/segmento?", ["Controla cada cuánto se regenera el contenido cacheado (ISR)", "Borra cookies", "Define layouts", "Crea APIs"], 0, "ISR revalida contenido tras un intervalo."],
      ["¿Qué es ISR?", ["Incremental Static Regeneration: regenerar páginas estáticas bajo demanda", "Un router", "Un hook", "Un ORM"], 0, "Combina lo estático con actualizaciones periódicas."],
      ["¿Qué componente optimiza imágenes?", ["<img>", "next/image", "<picture>", "next/img-opt"], 1, "next/image hace lazy load, resize y formatos modernos."],
      ["¿Dónde corre el middleware de Next.js?", ["En el cliente", "Antes de completar la request (edge/servidor)", "En build", "En el layout"], 1, "middleware.ts intercepta requests (auth, redirects)."],
      ["¿Qué hace el archivo template.tsx frente a layout.tsx?", ["Se re-monta en cada navegación (no persiste estado)", "Es idéntico", "Define APIs", "Es un error boundary"], 0, "template crea una nueva instancia en cada navegación."],
    ]),
    fase(6, [
      ["¿Qué es el data cache de Next.js?", ["Cachea resultados de fetch entre requests/deploys", "Cookies", "Un layout", "El bundle"], 0, "Permite reutilizar respuestas y controlar su frescura."],
      ["¿Cómo se opta por render dinámico en un segmento?", ["export const dynamic='force-dynamic' o usar cookies/headers", "'use client'", "generateStaticParams", "un layout"], 0, "Leer datos por-request fuerza render dinámico."],
      ["¿Qué es streaming con Suspense en el App Router?", ["Enviar HTML por partes a medida que se resuelven los datos", "Un websocket", "Un router", "Un cache"], 0, "Suspense permite mostrar UI progresivamente."],
      ["¿Dónde deben ir los secretos (API keys)?", ["En Client Components", "En Server Components/variables de entorno del servidor", "En el bundle", "En cookies públicas"], 1, "Nunca exponer secretos al cliente."],
      ["¿Qué prefijo expone una env var al navegador?", ["SECRET_", "NEXT_PUBLIC_", "PUBLIC_", "CLIENT_"], 1, "Solo NEXT_PUBLIC_* llega al cliente."],
    ]),
    fase(7, [
      ["¿Qué hace revalidatePath/revalidateTag?", ["Invalida caché tras una mutación para refrescar datos", "Redirige", "Crea rutas", "Borra cookies"], 0, "Se usan tras Server Actions para actualizar la vista."],
      ["¿Por qué un Client Component no puede importar código 'server-only'?", ["Ese código no debe enviarse al navegador (secretos/DB)", "Es más lento", "No hay bundler", "Falta React"], 0, "server-only impide filtrar lógica sensible al cliente."],
      ["¿Qué es el patrón de pasar Server Components como children a Client Components?", ["Permite componer manteniendo parte en servidor dentro de uno cliente", "Un HOC", "Un portal", "Un middleware"], 0, "Los children server se renderizan aparte y se insertan."],
      ["¿Qué runtime edge implica sobre las APIs de Node?", ["No están todas disponibles (entorno limitado)", "Son todas iguales", "Corre en el cliente", "Requiere Docker"], 0, "El edge runtime restringe APIs de Node."],
      ["¿Cómo se maneja la navegación programática?", ["useRouter().push()", "window.location solamente", "un layout", "route.ts"], 0, "useRouter (next/navigation) navega en el cliente."],
    ]),
    fase(8, [
      ["¿Qué garantiza la deduplicación de fetch en un render?", ["Peticiones idénticas se hacen una sola vez por request", "Cachea cookies", "Crea rutas", "Redirige"], 0, "Next dedupe fetches iguales dentro del mismo render."],
      ["¿Qué es Partial Prerendering (PPR)?", ["Combinar shell estático con partes dinámicas en streaming", "Solo SSG", "Solo SSR", "Un cache de cookies"], 0, "PPR sirve una cáscara estática y streamea lo dinámico."],
      ["¿Por qué preferir Server Actions frente a fetch a una API propia en mutaciones simples?", ["Menos boilerplate y ejecución segura en servidor con revalidación integrada", "Son más lentas", "Exponen secretos", "No cachean"], 0, "Reducen código y se integran con la caché."],
      ["¿Qué implica que layout.tsx sea un Server Component por defecto?", ["Puede hacer data fetching sin enviar JS al cliente", "Es interactivo", "Corre en build siempre", "Usa hooks"], 0, "Los layouts server pueden cargar datos sin costo de bundle."],
      ["¿Qué es el cache de router del lado cliente?", ["Cachea segmentos ya visitados para navegación instantánea", "Cookies", "Un ORM", "Un middleware"], 0, "Guarda RSC payloads de rutas visitadas."],
    ]),
    fase(9, [
      ["¿Qué problema causa poner 'use client' en la raíz del árbol?", ["Convierte casi todo en cliente, perdiendo beneficios de RSC (bundle/SEO)", "Mejora el SEO", "Acelera el build", "Nada"], 0, "Debe empujarse 'use client' a las hojas interactivas."],
      ["¿Cómo fluye data de un Server a un Client Component?", ["Como props serializables", "Con context global", "Con window", "No se puede"], 0, "Solo se pasan props serializables al límite cliente."],
      ["¿Qué garantiza el cache 'use cache' / unstable de funciones?", ["Memoiza resultados con etiquetas para invalidar selectivamente", "Cookies", "Un layout", "Un middleware"], 0, "Permite cachear y revalidar por tags."],
      ["¿Por qué evitar efectos de red en Server Components sin control de caché?", ["Pueden refetch en cada request y degradar rendimiento", "No compilan", "Rompen hooks", "Exponen secretos"], 0, "Sin caché adecuada se pierde el beneficio del prerender."],
      ["¿Qué es 'hydration mismatch' y una causa común?", ["El HTML del servidor difiere del cliente (p.ej. Date.now/random en render)", "Un 404", "Un error de red", "Un cache"], 0, "Renderizar valores no deterministas causa mismatch."],
    ]),
    fase(10, [
      ["¿Qué trade-off introduce PPR entre estático y dinámico?", ["Latencia baja del shell estático con frescura de las partes dinámicas", "Solo latencia alta", "Pierde SEO", "No cachea nada"], 0, "Equilibra velocidad y datos frescos."],
      ["¿Cómo mitigar el 'request waterfall' entre Server Components anidados?", ["Iniciar fetches en paralelo (Promise.all) o subir la carga", "Poner 'use client'", "Más middleware", "Deshabilitar caché"], 0, "Paralelizar evita cascadas de espera."],
      ["¿Qué implica la serialización del RSC payload para las props?", ["Solo datos serializables cruzan el límite; funciones/clases no", "Todo se serializa", "Nada cruza", "Se usan cookies"], 0, "No se pueden pasar funciones al límite cliente (salvo Server Actions)."],
      ["¿Por qué las Server Actions deben validar y autorizar siempre?", ["Son endpoints públicos invocables; el cliente no es de confianza", "Son privadas", "Corren en build", "No reciben input"], 0, "Aunque parezcan funciones locales, se exponen como endpoints."],
      ["¿Qué ventaja de rendimiento dan los RSC en apps grandes?", ["Reducen el JavaScript enviado al cliente moviendo render al servidor", "Eliminan el servidor", "Quitan el routing", "Evitan CSS"], 0, "Menos JS = cargas más rápidas e interactividad temprana."],
    ]),
  ],
);

const vue: QuizTema = tema(
  "vue",
  "Vue",
  "Reactividad, plantillas, componentes, Composition API y directivas.",
  [
    fase(1, [
      ["¿Qué es Vue?", ["Un framework progresivo para interfaces", "Una base de datos", "Un lenguaje", "Un ORM"], 0, "Vue es un framework de UI incremental."],
      ["¿Qué directiva enlaza texto reactivo?", ["v-for", "{{ }} (interpolación)", "v-if", "v-on"], 1, "Las dobles llaves muestran datos reactivos."],
      ["¿Qué directiva renderiza listas?", ["v-if", "v-for", "v-bind", "v-model"], 1, "v-for itera sobre colecciones."],
      ["¿Qué directiva maneja eventos?", ["v-on (@)", "v-bind", "v-model", "v-if"], 0, "@click escucha eventos."],
      ["¿Qué directiva hace binding bidireccional en inputs?", ["v-bind", "v-model", "v-for", "v-show"], 1, "v-model sincroniza input y estado."],
    ]),
    fase(2, [
      ["¿Qué directiva enlaza un atributo?", ["v-on", "v-bind (:)", "v-for", "v-model"], 1, ":href enlaza atributos dinámicamente."],
      ["¿Diferencia entre v-if y v-show?", ["v-if quita del DOM; v-show solo oculta con CSS", "Son iguales", "v-show quita del DOM", "v-if usa CSS"], 0, "v-show alterna display; v-if monta/desmonta."],
      ["¿Qué es una prop en Vue?", ["Dato que el padre pasa al hijo", "Estado global", "Un evento", "Una directiva"], 0, "Las props fluyen del padre al hijo."],
      ["¿Cómo comunica un hijo un cambio al padre?", ["Mutando la prop", "Emitiendo un evento ($emit)", "Con v-for", "Con v-show"], 1, "El hijo emite eventos que el padre escucha."],
      ["¿Qué archivo agrupa template, script y style?", [".vue (Single File Component)", ".jsx", ".html", ".ts"], 0, "Los SFC combinan las tres secciones."],
    ]),
    fase(3, [
      ["¿Qué es una propiedad computada?", ["Un valor derivado y cacheado de datos reactivos", "Un método normal", "Una prop", "Un evento"], 0, "computed se recalcula solo si cambian sus dependencias."],
      ["¿Qué es un watcher?", ["Ejecuta lógica cuando cambia un dato reactivo", "Una prop", "Un slot", "Una directiva"], 0, "watch reacciona a cambios específicos."],
      ["¿Qué son los slots?", ["Puntos donde el padre inyecta contenido en el hijo", "Eventos", "Props", "Directivas"], 0, "Los slots permiten composición de contenido."],
      ["¿Qué API compone lógica en funciones reutilizables?", ["Options API", "Composition API", "Router API", "Store API"], 1, "La Composition API usa setup/ref/reactive."],
      ["¿Con qué se crea un valor reactivo primitivo en Composition API?", ["ref()", "computed()", "watch()", "slot()"], 0, "ref() envuelve valores reactivos (.value)."],
    ]),
    fase(4, [
      ["¿Qué hace reactive()?", ["Crea un objeto reactivo profundo", "Un watcher", "Un slot", "Un evento"], 0, "reactive convierte objetos en reactivos."],
      ["¿Cómo se accede al valor de un ref en el script?", ["ref", "ref.value", "ref()", "ref[0]"], 1, "Se usa .value dentro del script."],
      ["¿Qué hook corre tras montar el componente?", ["onMounted", "onCreated", "onRender", "onLoad"], 0, "onMounted se ejecuta al insertarse en el DOM."],
      ["¿Qué es defineProps en <script setup>?", ["Declara las props del componente", "Emite eventos", "Crea un store", "Define slots"], 0, "defineProps tipa y recibe las props."],
      ["¿Qué es defineEmits?", ["Declara los eventos que el componente emite", "Recibe props", "Crea computed", "Un slot"], 0, "defineEmits documenta y emite eventos."],
    ]),
    fase(5, [
      ["¿Cómo se comparte estado global moderno en Vue 3?", ["Vuex clásico obligatorio", "Pinia", "localStorage siempre", "props profundas"], 1, "Pinia es el store recomendado en Vue 3."],
      ["¿Qué es un composable?", ["Una función que encapsula lógica reactiva reutilizable (useX)", "Un componente", "Un slot", "Una directiva"], 0, "Equivale a los custom hooks de React."],
      ["¿Qué hace provide/inject?", ["Pasar datos a descendientes sin props intermedias", "Emitir eventos", "Un watcher", "Un slot"], 0, "Evita el prop drilling hacia abajo."],
      ["¿Por qué v-for necesita :key?", ["Para reutilizar/reordenar nodos correctamente", "Para estilos", "Para SEO", "Para el router"], 0, "La key ayuda al diffing del DOM virtual."],
      ["¿Qué es un scoped style?", ["CSS que solo aplica al componente actual", "Estilo global", "Un slot", "Una prop"], 0, "<style scoped> aísla los estilos del componente."],
    ]),
    fase(6, [
      ["¿Qué diferencia hay entre watch y watchEffect?", ["watchEffect rastrea dependencias automáticamente; watch observa fuentes explícitas", "Son iguales", "watch es automático", "watchEffect no reacciona"], 0, "watchEffect ejecuta y colecta dependencias al vuelo."],
      ["¿Qué hace toRefs?", ["Convierte propiedades de un objeto reactivo en refs individuales", "Crea un store", "Un slot", "Un evento"], 0, "Preserva reactividad al desestructurar."],
      ["¿Qué es un slot con nombre?", ["Un slot identificado para insertar contenido específico", "Una prop", "Un evento", "Un watcher"], 0, "Permite múltiples puntos de inserción."],
      ["¿Qué es un scoped slot?", ["Un slot que expone datos del hijo al contenido del padre", "Un estilo aislado", "Un store", "Una directiva"], 0, "El hijo pasa props al contenido del slot."],
      ["¿Qué hace nextTick?", ["Espera al siguiente ciclo de actualización del DOM", "Crea un ref", "Emite eventos", "Un slot"], 0, "nextTick corre tras aplicar los cambios al DOM."],
    ]),
    fase(7, [
      ["¿Cómo funciona la reactividad en Vue 3?", ["Con Proxies que interceptan lecturas/escrituras", "Con dirty checking", "Con getters manuales", "No es reactivo"], 0, "Vue 3 usa Proxy para rastrear dependencias."],
      ["¿Por qué reactive pierde reactividad al desestructurar?", ["La desestructuración copia valores, no la referencia reactiva", "Por el router", "Por el bundler", "No la pierde"], 0, "Se usa toRefs para conservarla."],
      ["¿Qué es shallowRef?", ["Un ref cuya reactividad no es profunda", "Un slot", "Un store", "Un evento"], 0, "Solo reacciona al reemplazar .value, no a mutaciones internas."],
      ["¿Qué son los componentes async (defineAsyncComponent)?", ["Se cargan de forma diferida (code splitting)", "Un slot", "Un watcher", "Un store"], 0, "Cargan bajo demanda para reducir el bundle inicial."],
      ["¿Qué hace <Suspense> en Vue?", ["Muestra un fallback mientras se resuelven dependencias async", "Un router", "Un store", "Un slot"], 0, "Coordina estados de carga de componentes async."],
    ]),
    fase(8, [
      ["¿Qué es el efecto de scope (effectScope)?", ["Agrupa efectos reactivos para limpiarlos juntos", "Un slot", "Un store", "Un router"], 0, "Facilita disponer múltiples efectos a la vez."],
      ["¿Por qué computed se prefiere a un método para valores derivados?", ["computed cachea y solo recalcula si cambian dependencias", "Es más lento", "No cachea", "Es global"], 0, "El método se ejecuta en cada render; computed cachea."],
      ["¿Qué es markRaw?", ["Marca un objeto para que Vue no lo haga reactivo", "Crea un ref", "Un slot", "Un evento"], 0, "Útil para instancias externas costosas."],
      ["¿Qué garantiza customRef?", ["Control fino del rastreo/disparo de reactividad (p.ej. debounce)", "Un store", "Un slot", "Un router"], 0, "Permite lógica personalizada de reactividad."],
      ["¿Qué es el teleport?", ["Renderizar contenido en otro punto del DOM (p.ej. modales)", "Un store", "Un slot", "Un watcher"], 0, "<Teleport> mueve el nodo a otro contenedor."],
    ]),
    fase(9, [
      ["¿Qué problema evita usar un composable frente a mixins?", ["Colisiones de nombres y origen implícito de propiedades", "Menos memoria", "SEO", "Rutas"], 0, "Los composables hacen explícito qué se importa."],
      ["¿Qué es tree-shaking y cómo lo aprovecha Vue 3?", ["Eliminar código no usado; la API modular de Vue 3 lo facilita", "Un store", "Un slot", "Un router"], 0, "Importar solo lo necesario reduce el bundle."],
      ["¿Por qué shallowReactive puede mejorar el rendimiento?", ["Evita convertir estructuras profundas grandes en reactivas", "Es más lento", "Es global", "Rompe el DOM"], 0, "Reduce el costo de proxies en datos grandes."],
      ["¿Qué es la hidratación en SSR con Vue (Nuxt)?", ["Adjuntar reactividad al HTML renderizado en servidor", "Renderizar en cliente solamente", "Un store", "Un slot"], 0, "Hydration conecta el HTML SSR con la app."],
      ["¿Qué causa un memory leak con watchers en Composition API?", ["No detenerlos cuando el scope no se limpia solo", "Usar refs", "Usar computed", "El router"], 0, "Watchers fuera de setup deben detenerse manualmente."],
    ]),
    fase(10, [
      ["¿Qué ventaja da <script setup> a nivel de compilación?", ["Menos boilerplate y mejor rendimiento/inferencia de tipos", "Más JS enviado", "Rompe reactividad", "Quita el template"], 0, "El compilador optimiza el setup en tiempo de build."],
      ["¿Cómo optimiza el compilador de Vue 3 el render (static hoisting)?", ["Extrae nodos estáticos para no recrearlos en cada render", "Renderiza todo siempre", "Usa dirty checking", "Desactiva proxies"], 0, "Los nodos estáticos se izan y reutilizan."],
      ["¿Qué son los 'patch flags' del compilador?", ["Marcas que indican qué partes son dinámicas para diffear solo eso", "Un store", "Un slot", "Un router"], 0, "Aceleran el diffing enfocándolo en lo dinámico."],
      ["¿Por qué evitar mutar props directamente?", ["Rompe el flujo unidireccional y avisa en consola; usa eventos o copias", "Es más lento", "No compila", "Rompe el router"], 0, "Las props son de solo lectura para el hijo."],
      ["¿Qué implica la reactividad basada en Proxy para Sets/Maps?", ["Vue 3 puede rastrear sus mutaciones (a diferencia de Vue 2)", "No son reactivos", "Requieren Vuex", "Solo con refs"], 0, "Proxy permite reactividad en colecciones nativas."],
    ]),
  ],
);

const angular: QuizTema = tema(
  "angular",
  "Angular",
  "Componentes, módulos, servicios, inyección de dependencias y RxJS.",
  [
    fase(1, [
      ["¿Qué es Angular?", ["Un framework completo de aplicaciones en TypeScript", "Una librería pequeña", "Un lenguaje", "Un ORM"], 0, "Angular es un framework SPA opinado."],
      ["¿En qué lenguaje se escribe Angular?", ["JavaScript puro", "TypeScript", "CoffeeScript", "Dart"], 1, "Angular está construido en TypeScript."],
      ["¿Qué decorador define un componente?", ["@Injectable", "@Component", "@NgModule", "@Directive"], 1, "@Component marca una clase como componente."],
      ["¿Qué archivo suele tener la plantilla?", [".html", ".css", ".ts únicamente", ".json"], 0, "El template vive en un .html o inline."],
      ["¿Qué directiva estructural repite elementos?", ["*ngIf", "*ngFor", "ngClass", "ngModel"], 1, "*ngFor itera sobre colecciones."],
    ]),
    fase(2, [
      ["¿Qué directiva renderiza condicionalmente?", ["*ngFor", "*ngIf", "ngStyle", "ngModel"], 1, "*ngIf agrega/quita el elemento del DOM."],
      ["¿Qué sintaxis enlaza una propiedad?", ["{{ }}", "[propiedad]", "(evento)", "#ref"], 1, "[prop]=\"valor\" es property binding."],
      ["¿Qué sintaxis escucha eventos?", ["[evento]", "(evento)", "{{evento}}", "#evento"], 1, "(click)=\"fn()\" es event binding."],
      ["¿Qué habilita el binding bidireccional?", ["[()] con ngModel", "solo [ ]", "solo ( )", "{{ }}"], 0, "[(ngModel)] combina property y event binding."],
      ["¿Qué es un módulo (@NgModule)?", ["Agrupa componentes, directivas y servicios relacionados", "Un servicio", "Un pipe", "Un componente"], 0, "Organiza la aplicación en bloques cohesivos."],
    ]),
    fase(3, [
      ["¿Qué es un servicio en Angular?", ["Clase reutilizable para lógica/datos compartidos", "Una plantilla", "Un pipe", "Una directiva estructural"], 0, "Los servicios encapsulan lógica no visual."],
      ["¿Qué decorador marca una clase inyectable?", ["@Component", "@Injectable", "@Pipe", "@Input"], 1, "@Injectable permite inyectarla como dependencia."],
      ["¿Qué es la inyección de dependencias?", ["Proveer instancias a través del constructor automáticamente", "Copiar objetos", "Un pipe", "Un módulo"], 0, "El framework resuelve y provee dependencias."],
      ["¿Qué transforma valores en la plantilla?", ["Un servicio", "Un pipe", "Un módulo", "Un guard"], 1, "Los pipes formatean datos (date, uppercase)."],
      ["¿Qué decorador recibe datos del padre?", ["@Output", "@Input", "@Inject", "@Pipe"], 1, "@Input define props de entrada."],
    ]),
    fase(4, [
      ["¿Qué decorador emite eventos al padre?", ["@Input", "@Output", "@Inject", "@ViewChild"], 1, "@Output con EventEmitter notifica al padre."],
      ["¿Qué es RxJS en Angular?", ["Librería de programación reactiva con Observables", "Un router", "Un ORM", "Un compilador"], 0, "Angular usa Observables para flujos asíncronos."],
      ["¿Qué es un Observable?", ["Un flujo de valores en el tiempo al que te suscribes", "Una promesa única", "Un pipe", "Un módulo"], 0, "Los Observables emiten múltiples valores."],
      ["¿Qué hace el router de Angular?", ["Mapea rutas a componentes en una SPA", "Consulta la DB", "Formatea fechas", "Inyecta servicios"], 0, "RouterModule gestiona la navegación."],
      ["¿Qué es un guard de ruta?", ["Controla si se puede activar/salir de una ruta", "Un pipe", "Un módulo", "Un observable"], 0, "CanActivate protege rutas (p.ej. auth)."],
    ]),
    fase(5, [
      ["¿Qué operador de RxJS transforma cada valor emitido?", ["filter", "map", "reduce", "merge"], 1, "map transforma los valores del flujo."],
      ["¿Qué hace async pipe?", ["Se suscribe a un Observable y maneja la desuscripción", "Formatea fechas", "Un guard", "Un módulo"], 0, "async se suscribe y limpia automáticamente."],
      ["¿Qué es un componente standalone?", ["Un componente que no necesita declararse en un NgModule", "Un servicio", "Un pipe", "Un guard"], 0, "Los standalone components simplifican la modularidad."],
      ["¿Qué es lazy loading de rutas?", ["Cargar módulos/rutas bajo demanda", "Cargar todo al inicio", "Un pipe", "Un observable"], 0, "Divide el bundle y carga al navegar."],
      ["¿Qué operador combina el último valor de varios Observables?", ["combineLatest", "map", "filter", "take"], 0, "combineLatest emite al cambiar cualquiera."],
    ]),
    fase(6, [
      ["¿Qué es change detection en Angular?", ["El mecanismo que actualiza la vista cuando cambian los datos", "Un router", "Un pipe", "Un guard"], 0, "Angular detecta cambios y re-renderiza."],
      ["¿Qué hace ChangeDetectionStrategy.OnPush?", ["Solo detecta cambios ante nuevas referencias/inputs o eventos", "Detecta siempre", "Desactiva la vista", "Un pipe"], 0, "OnPush optimiza reduciendo comprobaciones."],
      ["¿Qué operador cancela peticiones previas al llegar una nueva?", ["mergeMap", "switchMap", "concatMap", "forkJoin"], 1, "switchMap cancela el observable interno anterior."],
      ["¿Por qué desuscribirse de Observables manuales?", ["Evitar fugas de memoria", "Mejorar SEO", "Formatear datos", "Un guard"], 0, "Las suscripciones vivas retienen memoria."],
      ["¿Qué es un resolver de ruta?", ["Precarga datos antes de activar la ruta", "Un pipe", "Un módulo", "Un guard de salida"], 0, "Resolve entrega datos listos al componente."],
    ]),
    fase(7, [
      ["¿Qué es Zone.js y su rol en Angular?", ["Parchea APIs async para disparar change detection automáticamente", "Un ORM", "Un router", "Un pipe"], 0, "Zone.js sabe cuándo revisar por cambios."],
      ["¿Qué ventaja da 'zoneless' / signals?", ["Reactividad más granular y menos overhead de detección global", "Más lento", "Sin tipos", "Sin router"], 0, "Los signals actualizan lo justo sin Zone.js."],
      ["¿Qué es un signal en Angular moderno?", ["Un valor reactivo con lectura/escritura explícita y dependencias rastreadas", "Un observable frío", "Un pipe", "Un guard"], 0, "Los signals modelan estado reactivo fino."],
      ["¿Qué hace forkJoin?", ["Emite cuando todos los Observables completan, con sus últimos valores", "Cancela previos", "Filtra", "Mapea"], 0, "Similar a Promise.all para Observables que completan."],
      ["¿Qué es un HTTP interceptor?", ["Intercepta peticiones/respuestas HTTP (auth, errores)", "Un pipe", "Un guard", "Un módulo"], 0, "Permite añadir headers o manejar errores centralizado."],
    ]),
    fase(8, [
      ["¿Qué diferencia hay entre mergeMap y concatMap?", ["mergeMap concurre; concatMap serializa en orden", "Son iguales", "concatMap cancela", "mergeMap ordena"], 0, "concatMap espera a que termine el anterior."],
      ["¿Qué es un Observable frío vs. caliente?", ["Frío: cada suscriptor recibe su propia ejecución; caliente: comparten la fuente", "Son iguales", "Caliente es más lento", "Frío no emite"], 0, "El multicasting convierte frío en caliente."],
      ["¿Qué operador comparte una ejecución entre suscriptores?", ["share/shareReplay", "map", "filter", "take"], 0, "shareReplay evita re-ejecutar y cachea emisiones."],
      ["¿Qué es la jerarquía de inyectores en Angular?", ["Los providers se resuelven por niveles (root, módulo, componente)", "No existe", "Solo hay uno global", "Un pipe"], 0, "La DI busca hacia arriba en el árbol de inyectores."],
      ["¿Qué garantiza providedIn: 'root'?", ["Un singleton disponible en toda la app y tree-shakeable", "Una instancia por componente", "Nada", "Un guard"], 0, "Crea un único servicio global optimizable."],
    ]),
    fase(9, [
      ["¿Por qué OnPush requiere inmutabilidad para inputs?", ["Detecta cambios por referencia; mutar no dispara la actualización", "Es más lento", "No aplica", "Rompe el router"], 0, "Con OnPush hay que crear nuevas referencias."],
      ["¿Qué problema resuelven los signals frente a Zone.js?", ["Actualizaciones dirigidas sin revisar todo el árbol de componentes", "Menos memoria de red", "SEO", "Rutas"], 0, "Reducen el trabajo de change detection global."],
      ["¿Qué es backpressure y cómo se maneja en RxJS?", ["El productor emite más rápido de lo que el consumidor procesa; se usa buffer/throttle", "Un guard", "Un pipe", "Un módulo"], 0, "Operadores como throttleTime regulan el flujo."],
      ["¿Qué diferencia hay entre exhaustMap y switchMap?", ["exhaustMap ignora nuevas fuentes mientras la actual no completa", "Son iguales", "switchMap ignora", "exhaustMap cancela"], 0, "exhaustMap descarta emisiones durante una ejecución activa."],
      ["¿Qué es el patrón de facade con servicios y stores?", ["Exponer una API simple sobre estado/lógica compleja", "Un guard", "Un pipe", "Un router"], 0, "El facade oculta la complejidad del estado."],
    ]),
    fase(10, [
      ["¿Qué ventaja da la compilación AOT frente a JIT?", ["Compila plantillas en build: arranque más rápido y errores tempranos", "Más lenta", "Menos segura", "Sin tipos"], 0, "AOT precompila y reduce el trabajo en runtime."],
      ["¿Cómo interoperan signals y RxJS en Angular?", ["Con toSignal/toObservable para convertir entre ambos modelos", "No interoperan", "Solo con Zone.js", "Con pipes"], 0, "Permiten combinar estado reactivo y flujos async."],
      ["¿Qué riesgo tiene shareReplay sin refCount?", ["Mantiene viva la fuente y puede filtrar memoria", "Es más rápido", "No cachea", "Rompe tipos"], 0, "Sin refCount la suscripción interna no se libera."],
      ["¿Qué es hydration no destructiva en Angular SSR moderno?", ["Reutiliza el DOM del servidor sin recrearlo al hidratar", "Recrea todo el DOM", "Un guard", "Un pipe"], 0, "Mejora rendimiento evitando re-render completo."],
      ["¿Por qué preferir OnPush + inmutabilidad + async pipe en apps grandes?", ["Minimiza detección de cambios y evita fugas de suscripción", "Aumenta el bundle", "Rompe el router", "Elimina servicios"], 0, "Es la combinación idiomática para rendimiento."],
    ]),
  ],
);

const svelte: QuizTema = tema(
  "svelte",
  "Svelte",
  "Compilador reactivo, reactividad, stores, props y transiciones.",
  [
    fase(1, [
      ["¿Qué distingue a Svelte de otros frameworks?", ["Es un compilador: genera JS sin virtual DOM", "Usa virtual DOM pesado", "Es un lenguaje", "Es un ORM"], 0, "Svelte compila los componentes a JS eficiente."],
      ["¿Qué extensión tienen los componentes?", [".jsx", ".svelte", ".vue", ".ts"], 1, "Los componentes viven en archivos .svelte."],
      ["¿Cómo se declara estado reactivo básico?", ["useState", "una variable normal (let)", "ref()", "signal()"], 1, "Una variable let es reactiva al reasignarse."],
      ["¿Cómo se interpola una variable en el marcado?", ["{{ x }}", "{ x }", "${x}", "<x>"], 1, "Se usan llaves simples { x }."],
      ["¿Cómo se escucha un evento de click?", ["v-on:click", "on:click", "@click", "(click)"], 1, "on:click asocia el handler."],
    ]),
    fase(2, [
      ["¿Qué bloque renderiza listas?", ["{#for}", "{#each}", "{#map}", "v-for"], 1, "{#each items as item} itera."],
      ["¿Qué bloque renderiza condicionalmente?", ["{#when}", "{#if}", "*ngIf", "v-if"], 1, "{#if cond}...{/if} condiciona el marcado."],
      ["¿Cómo se declara una prop que recibe el componente?", ["prop x", "export let x", "@Input x", "defineProps"], 1, "export let x expone una prop."],
      ["¿Dónde va la lógica JavaScript del componente?", ["<script>", "<logic>", "<code>", "<setup>"], 0, "El bloque <script> contiene la lógica."],
      ["¿Cómo se enlaza el valor de un input?", ["v-model", "bind:value", "[(ngModel)]", "value.value"], 1, "bind:value sincroniza el input con la variable."],
    ]),
    fase(3, [
      ["¿Qué hace la etiqueta $: (reactive statement)?", ["Recalcula cuando cambian sus dependencias", "Define una prop", "Crea un store", "Un evento"], 0, "$: total = a + b se recalcula reactivamente."],
      ["¿Qué es un store en Svelte?", ["Un contenedor de estado observable compartible", "Un componente", "Una prop", "Un evento"], 0, "Los stores comparten estado entre componentes."],
      ["¿Cómo se lee un store en el marcado?", ["store()", "$store", "store.value", "get(store)"], 1, "El prefijo $ auto-suscribe al store."],
      ["¿Qué tipo de store tiene valor y se puede actualizar?", ["readable", "writable", "derived", "const"], 1, "writable permite set/update."],
      ["¿Qué es un derived store?", ["Un store calculado a partir de otros", "Un componente", "Un evento", "Una transición"], 0, "derived combina otros stores en un valor."],
    ]),
    fase(4, [
      ["¿Cómo comunica un hijo un evento personalizado al padre?", ["$emit", "createEventDispatcher", "@Output", "props mutadas"], 1, "createEventDispatcher despacha eventos."],
      ["¿Qué son los slots en Svelte?", ["Puntos de inserción de contenido del padre", "Props", "Stores", "Transiciones"], 0, "<slot> recibe contenido externo."],
      ["¿Qué directiva aplica clases condicionalmente?", ["class:nombre", "ngClass", ":class", "v-bind:class"], 0, "class:activo={cond} alterna la clase."],
      ["¿Qué hace bind: en general?", ["Enlaza una propiedad de forma bidireccional", "Emite eventos", "Crea stores", "Un slot"], 0, "bind: sincroniza el valor entre DOM y variable."],
      ["¿Cómo se pasa contenido a un slot con nombre?", ["slot=\"nombre\"", "name=\"nombre\"", "#nombre", "@nombre"], 0, "El atributo slot dirige el contenido."],
    ]),
    fase(5, [
      ["¿Qué hook corre al montar el componente?", ["onMounted", "onMount", "created", "ngOnInit"], 1, "onMount se ejecuta tras insertarse en el DOM."],
      ["¿Qué hook limpia al destruirse?", ["onDestroy", "onUnmount", "cleanup", "ngOnDestroy"], 0, "onDestroy libera recursos."],
      ["¿Qué es una transición (transition:)?", ["Animación al entrar/salir del DOM", "Un store", "Una prop", "Un slot"], 0, "transition:fade anima montaje/desmontaje."],
      ["¿Qué hace tick()?", ["Espera a que Svelte aplique cambios pendientes al DOM", "Crea un store", "Emite eventos", "Un slot"], 0, "tick permite leer el DOM ya actualizado."],
      ["¿Por qué {#each} suele necesitar una key (item.id)?", ["Para reordenar/actualizar la lista correctamente", "Para estilos", "Para SEO", "Para stores"], 0, "La key preserva identidad de los elementos."],
    ]),
    fase(6, [
      ["¿Por qué push() a un array no dispara reactividad por sí solo?", ["Svelte reacciona a la asignación, no a la mutación in situ", "Es un bug", "Falta un store", "Por el compilador"], 0, "Hay que reasignar: arr = [...arr, x]."],
      ["¿Qué es una action (use:)?", ["Una función que recibe un nodo DOM para lógica personalizada", "Un store", "Un slot", "Una prop"], 0, "use:accion se ejecuta al montar el elemento."],
      ["¿Qué garantiza el auto-subscribe con $store?", ["Suscribe y desuscribe automáticamente según el ciclo de vida", "Nada", "Solo lee una vez", "Es global"], 0, "Evita fugas manejando la desuscripción."],
      ["¿Qué es un context (setContext/getContext)?", ["Comparte datos con descendientes sin props", "Un store global", "Un slot", "Una transición"], 0, "El context viaja por el árbol de componentes."],
      ["¿Qué diferencia hay entre context y store?", ["context es por árbol de componentes; store es un valor observable compartible", "Son iguales", "store es por árbol", "context es reactivo siempre"], 0, "El context no es necesariamente reactivo."],
    ]),
    fase(7, [
      ["¿Qué ventaja da que Svelte no use virtual DOM?", ["Genera actualizaciones dirigidas, con menos overhead en runtime", "Más JS enviado", "Peor rendimiento", "Sin reactividad"], 0, "El compilador sabe qué actualizar sin diffing."],
      ["¿Qué es SvelteKit?", ["El framework de aplicaciones (routing, SSR) sobre Svelte", "Un store", "Un ORM", "Un compilador aparte"], 0, "SvelteKit añade routing, SSR y endpoints."],
      ["¿Qué es una custom transition?", ["Definir una función que devuelve css/tick para animar", "Un store", "Un slot", "Una action"], 0, "Permite animaciones a medida en entrada/salida."],
      ["¿Qué hace el modificador on:click|preventDefault?", ["Aplica preventDefault al evento automáticamente", "Cancela el componente", "Un store", "Un slot"], 0, "Los modificadores de evento simplifican el manejo."],
      ["¿Qué es un derived store con múltiples dependencias?", ["derived([a,b], ([$a,$b]) => ...) combina varios stores", "Un context", "Un slot", "Una action"], 0, "derived acepta un array de stores fuente."],
    ]),
    fase(8, [
      ["¿Qué introduce Svelte 5 con las 'runes'?", ["Reactividad explícita con $state, $derived, $effect", "Elimina componentes", "Quita stores", "Añade virtual DOM"], 0, "Las runes hacen la reactividad explícita y granular."],
      ["¿Qué hace $state en runes?", ["Declara estado reactivo explícito", "Un slot", "Un context", "Una action"], 0, "$state(valor) crea estado reactivo."],
      ["¿Qué hace $derived?", ["Declara un valor calculado reactivo", "Un efecto", "Un store readable", "Un slot"], 0, "$derived(expr) se recalcula según dependencias."],
      ["¿Qué hace $effect?", ["Ejecuta efectos secundarios cuando cambian dependencias", "Declara props", "Un slot", "Un context"], 0, "$effect reacciona a cambios como useEffect."],
      ["¿Qué ventaja da la reactividad basada en señales de Svelte 5?", ["Actualizaciones más finas y predecibles fuera de componentes", "Más overhead", "Sin tipos", "Sin SSR"], 0, "Las señales permiten reactividad granular reutilizable."],
    ]),
    fase(9, [
      ["¿Qué problema resuelven las runes frente a $: reactivo?", ["Reactividad explícita y componible también fuera de componentes .svelte", "Más lento", "Menos claro", "Sin stores"], 0, "$: solo funciona en el tope de componentes; las runes no."],
      ["¿Qué garantiza el fine-grained reactivity de señales?", ["Actualizar solo las dependencias afectadas, no todo el componente", "Re-render total", "Diffing de virtual DOM", "Nada"], 0, "Solo recalcula lo que depende del valor cambiado."],
      ["¿Por qué las load functions de SvelteKit corren en servidor y cliente?", ["Permiten SSR inicial y navegación en cliente reutilizando la misma carga", "Solo en cliente", "Solo en build", "Nunca"], 0, "load unifica la obtención de datos por ruta."],
      ["¿Qué es progressive enhancement con use:enhance en formularios?", ["El form funciona sin JS y mejora con JS si está disponible", "Requiere JS siempre", "Un store", "Un slot"], 0, "Los formularios degradan con gracia."],
      ["¿Qué riesgo tiene un $effect que escribe un $state del que depende?", ["Bucle de actualización infinito", "Nada", "Mejora el rendimiento", "Rompe el SSR"], 0, "Debe evitarse la dependencia circular en efectos."],
    ]),
    fase(10, [
      ["¿Qué trade-off tiene compilar a JS sin runtime de framework?", ["Bundles pequeños por app, pero sin runtime compartido entre componentes", "Bundles enormes", "Sin reactividad", "Peor DX"], 0, "El costo se distribuye por componente compilado."],
      ["¿Cómo evita Svelte el 'diffing' del virtual DOM al actualizar?", ["El compilador enlaza cada dato con las instrucciones DOM exactas", "Recorre todo el árbol", "Usa Zone.js", "No actualiza"], 0, "Genera código que toca solo lo necesario."],
      ["¿Qué ventaja da SvelteKit al hacer code splitting por ruta?", ["Carga solo el JS de la ruta actual, reduciendo el TTI", "Carga todo", "Sin SSR", "Sin caché"], 0, "Divide el bundle por página automáticamente."],
      ["¿Qué es la 'universal reactivity' de las runes en .svelte.js?", ["Reactividad reutilizable en módulos, no solo en componentes", "Solo en componentes", "Sin efectos", "Sin estado"], 0, "Permite composables reactivos fuera del .svelte."],
      ["¿Por qué es clave reasignar en vez de mutar para grandes estructuras en Svelte 4?", ["El compilador rastrea asignaciones para invalidar dependencias", "Es más lento", "Por el SSR", "Por los slots"], 0, "La invalidación se basa en la asignación de la variable."],
    ]),
  ],
);

export const TEMAS_FRAMEWORKS: QuizTema[] = [react, nextjs, vue, angular, svelte];
