import { fase, tema, type QuizTema } from "./tipos";

// Categoría: Fundamentos de programación.
// Temas: Git, Estructuras de datos, Algoritmos, POO, HTML y CSS.

const git: QuizTema = tema(
  "git",
  "Git y control de versiones",
  "Commits, ramas, merges, historia y flujos de colaboración.",
  [
    fase(1, [
      ["¿Qué es Git?", ["Un sistema de control de versiones distribuido", "Un lenguaje", "Un editor", "Una base de datos"], 0, "Git rastrea cambios en el código."],
      ["¿Qué comando inicializa un repositorio?", ["git start", "git init", "git new", "git create"], 1, "git init crea un repositorio local."],
      ["¿Qué comando guarda cambios en el historial?", ["git save", "git commit", "git store", "git keep"], 1, "git commit registra los cambios preparados."],
      ["¿Qué comando prepara archivos para el commit?", ["git add", "git stage", "git prep", "git ready"], 0, "git add mueve cambios al staging area."],
      ["¿Qué comando muestra el estado del repositorio?", ["git info", "git status", "git show", "git state"], 1, "git status lista cambios y archivos preparados."],
    ]),
    fase(2, [
      ["¿Qué comando descarga un repositorio remoto?", ["git copy", "git clone", "git download", "git pull-all"], 1, "git clone copia el repositorio completo."],
      ["¿Qué comando sube commits al remoto?", ["git upload", "git push", "git send", "git commit -r"], 1, "git push publica los commits locales."],
      ["¿Qué comando trae cambios del remoto y los fusiona?", ["git fetch", "git pull", "git get", "git sync"], 1, "git pull = fetch + merge."],
      ["¿Qué archivo lista lo que Git debe ignorar?", [".gitignore", ".ignore", "git.config", ".gitkeep"], 0, ".gitignore excluye archivos del control."],
      ["¿Qué comando muestra el historial de commits?", ["git list", "git log", "git history", "git commits"], 1, "git log muestra la historia."],
    ]),
    fase(3, [
      ["¿Qué es una rama (branch)?", ["Una línea de desarrollo independiente", "Un commit", "Un remoto", "Un tag"], 0, "Las ramas aíslan trabajo en paralelo."],
      ["¿Qué comando crea y cambia a una rama nueva?", ["git branch new", "git checkout -b", "git switch --create-only", "git make"], 1, "git checkout -b crea y cambia de rama."],
      ["¿Qué comando fusiona una rama en la actual?", ["git join", "git merge", "git combine", "git mix"], 1, "git merge integra otra rama."],
      ["¿Qué es el staging area?", ["Zona intermedia con los cambios a incluir en el próximo commit", "El remoto", "Un tag", "El historial"], 0, "El índice prepara qué se commiteará."],
      ["¿Qué comando descarta cambios no preparados de un archivo?", ["git restore", "git undo", "git revert", "git clean"], 0, "git restore revierte el working tree."],
    ]),
    fase(4, [
      ["¿Qué es un merge conflict?", ["Cambios incompatibles en la misma parte de un archivo", "Un commit vacío", "Un tag", "Un remoto"], 0, "Ocurre al fusionar ediciones solapadas."],
      ["¿Qué comando crea un nuevo commit que deshace otro?", ["git reset", "git revert", "git undo", "git drop"], 1, "git revert es seguro en historia compartida."],
      ["¿Qué hace git reset --hard?", ["Descarta commits y cambios locales (destructivo)", "Solo mueve la rama", "Crea un commit", "Sube al remoto"], 0, "Es destructivo: pierde cambios."],
      ["¿Qué es un remote?", ["Una referencia a un repositorio en otro lugar (p.ej. origin)", "Una rama local", "Un tag", "El staging"], 0, "El remoto sincroniza con GitHub, etc."],
      ["¿Qué comando muestra diferencias no preparadas?", ["git diff", "git changes", "git delta", "git compare"], 0, "git diff muestra los cambios del working tree."],
    ]),
    fase(5, [
      ["¿Qué es un Pull Request?", ["Una propuesta de fusionar cambios revisable por el equipo", "Un commit local", "Un tag", "Un stash"], 0, "El PR facilita revisión antes de mergear."],
      ["¿Qué hace git stash?", ["Guarda temporalmente cambios sin commitear", "Borra ramas", "Crea tags", "Sube al remoto"], 0, "stash aparta cambios para retomarlos luego."],
      ["¿Qué es HEAD en Git?", ["Un puntero al commit/rama actual", "El primer commit", "El remoto", "Un tag"], 0, "HEAD indica dónde estás parado."],
      ["¿Qué comando descarga cambios sin fusionarlos?", ["git pull", "git fetch", "git clone", "git merge"], 1, "git fetch actualiza referencias sin tocar tu rama."],
      ["¿Qué es un tag?", ["Una marca en un commit (p.ej. una versión)", "Una rama", "Un remoto", "Un stash"], 0, "Los tags nombran puntos como releases."],
    ]),
    fase(6, [
      ["¿Qué diferencia hay entre merge y rebase?", ["merge crea un commit de unión; rebase reescribe la base de los commits", "Son iguales", "rebase crea merge commit", "merge reescribe"], 0, "Rebase produce una historia lineal."],
      ["¿Por qué NO rebasar ramas ya compartidas/públicas?", ["Reescribe la historia y rompe el trabajo de otros", "Es más lento", "Borra el remoto", "Nada"], 0, "El rebase de historia pública causa conflictos a todos."],
      ["¿Qué hace git cherry-pick?", ["Aplica un commit específico en la rama actual", "Fusiona todo", "Borra commits", "Crea tags"], 0, "cherry-pick traslada commits puntuales."],
      ["¿Qué es fast-forward en un merge?", ["Mover el puntero de rama sin crear commit de merge", "Un rebase", "Un stash", "Un tag"], 0, "Ocurre cuando no hay divergencia."],
      ["¿Qué hace git log --oneline --graph?", ["Muestra la historia compacta y ramificada", "Borra commits", "Sube al remoto", "Crea ramas"], 0, "Visualiza la topología de commits."],
    ]),
    fase(7, [
      ["¿Qué guarda el reflog?", ["El historial de dónde ha apuntado HEAD (permite recuperar commits perdidos)", "Solo los tags", "El remoto", "El stash"], 0, "El reflog ayuda a rescatar commits tras un reset."],
      ["¿Qué es un rebase interactivo?", ["Reordenar, combinar (squash) o editar commits", "Un merge", "Un stash", "Un fetch"], 0, "git rebase -i permite limpiar la historia."],
      ["¿Qué es squash de commits?", ["Combinar varios commits en uno solo", "Dividir un commit", "Borrar ramas", "Un tag"], 0, "El squash agrupa cambios en un único commit."],
      ["¿Qué hace git bisect?", ["Búsqueda binaria en la historia para hallar el commit que introdujo un bug", "Un merge", "Un stash", "Un rebase"], 0, "bisect localiza regresiones eficientemente."],
      ["¿Qué es el detached HEAD?", ["HEAD apunta a un commit directo, no a una rama", "Un merge fallido", "Un stash", "Un tag"], 0, "Los commits nuevos pueden perderse si no se ramifica."],
    ]),
    fase(8, [
      ["¿Qué es una estrategia de branching como trunk-based?", ["Integrar frecuentemente a una rama principal con ramas cortas", "Ramas de larga vida", "Sin ramas", "Solo tags"], 0, "Favorece integración continua y menos conflictos."],
      ["¿Qué riesgo tiene git push --force en una rama compartida?", ["Sobrescribe la historia remota y puede borrar el trabajo de otros", "Ninguno", "Es más rápido", "Crea tags"], 0, "Se prefiere --force-with-lease si es imprescindible."],
      ["¿Qué hace --force-with-lease frente a --force?", ["Solo fuerza si el remoto no cambió desde tu última referencia", "Es idéntico", "Nunca fuerza", "Borra ramas"], 0, "Evita pisar cambios ajenos inesperados."],
      ["¿Qué es un hook de Git (pre-commit)?", ["Un script que se ejecuta ante eventos de Git (p.ej. antes de commit)", "Un tag", "Un remoto", "Un stash"], 0, "Automatiza lint/tests antes de commitear."],
      ["¿Por qué evitar --no-verify al commitear?", ["Salta los hooks de calidad (lint, commitlint) del equipo", "Es más seguro", "Sube más rápido", "Nada"], 0, "Saltar hooks rompe las garantías de calidad acordadas."],
    ]),
    fase(9, [
      ["¿Qué problema resuelve git rerere?", ["Recuerda resoluciones de conflictos para reaplicarlas automáticamente", "Un tag", "Un stash", "Un fetch"], 0, "Útil en rebases repetidos con los mismos conflictos."],
      ["¿Qué es un merge de tres vías (3-way)?", ["Usa el ancestro común y ambas puntas para fusionar", "Copia una rama", "Un fast-forward", "Un tag"], 0, "El ancestro común guía la resolución."],
      ["¿Qué garantiza que Git sea un grafo dirigido acíclico (DAG)?", ["Cada commit referencia a sus padres, formando una historia inmutable", "Que no hay ramas", "Que no hay tags", "Que es lineal"], 0, "El DAG modela merges y ramas."],
      ["¿Qué es git worktree?", ["Trabajar varias ramas en directorios separados del mismo repo", "Un stash", "Un tag", "Un remoto"], 0, "Permite checkouts paralelos sin clonar de nuevo."],
      ["¿Por qué los commits se identifican con un hash SHA?", ["El hash resume su contenido y su historia, garantizando integridad", "Es aleatorio", "Es un contador", "Es la fecha"], 0, "Cambiar algo cambia el hash y detecta manipulaciones."],
    ]),
    fase(10, [
      ["¿Qué trade-off central hay entre merge y rebase en un equipo?", ["Rebase da historia limpia pero reescribe; merge preserva contexto con commits de unión", "Ninguno", "Merge reescribe", "Rebase preserva merges"], 0, "Se elige según las convenciones del equipo."],
      ["¿Por qué la historia inmutable de Git habilita colaboración distribuida?", ["Cada copia es completa y verificable; se sincroniza sin un servidor central obligatorio", "Requiere un servidor central", "No permite ramas", "Es solo local"], 0, "Git es distribuido: cada clon tiene toda la historia."],
      ["¿Qué garantiza --force-with-lease en un flujo con revisión?", ["Actualizar la rama sin pisar cambios que no habías visto", "Nunca falla", "Evita todo conflicto", "Crea tags"], 0, "Protege contra sobrescrituras accidentales."],
      ["¿Qué problema resuelve rebase interactivo antes de abrir un PR?", ["Limpiar y agrupar commits para una historia legible y revisable", "Subir más rápido", "Evita tests", "Cifra"], 0, "Una historia clara facilita la revisión."],
      ["¿Por qué proteger ramas como main/dev en el flujo del equipo?", ["Evitar pushes directos y forzar revisión (PR) antes de integrar", "Es cosmético", "Acelera merges", "Borra tags"], 0, "Las ramas protegidas resguardan la línea de producción."],
    ]),
  ],
);

const estructurasDatos: QuizTema = tema(
  "estructuras-datos",
  "Estructuras de datos",
  "Arrays, listas, pilas, colas, árboles, grafos y tablas hash.",
  [
    fase(1, [
      ["¿Qué es un array?", ["Colección indexada de elementos contiguos", "Un par clave-valor", "Un árbol", "Un grafo"], 0, "El array accede por índice en O(1)."],
      ["¿Desde qué índice empiezan los arrays normalmente?", ["1", "0", "-1", "Depende del valor"], 1, "El primer elemento está en el índice 0."],
      ["¿Qué estructura sigue LIFO (último en entrar, primero en salir)?", ["Cola", "Pila (Stack)", "Array", "Árbol"], 1, "La pila apila y desapila por el tope."],
      ["¿Qué estructura sigue FIFO (primero en entrar, primero en salir)?", ["Pila", "Cola (Queue)", "Árbol", "Grafo"], 1, "La cola encola al final y desencola al frente."],
      ["¿Qué estructura asocia claves a valores?", ["Array", "Tabla hash (mapa)", "Pila", "Cola"], 1, "La tabla hash mapea clave a valor."],
    ]),
    fase(2, [
      ["¿Qué es una lista enlazada?", ["Nodos que apuntan al siguiente", "Un array contiguo", "Una tabla hash", "Un árbol"], 0, "Cada nodo enlaza al siguiente."],
      ["¿Qué operación de pila añade un elemento?", ["push", "enqueue", "insert", "add-front"], 0, "push apila en el tope."],
      ["¿Qué operación de cola quita el primer elemento?", ["pop", "dequeue", "shift-top", "peek"], 1, "dequeue retira del frente."],
      ["¿Qué es la complejidad O(1)?", ["Tiempo constante independiente del tamaño", "Lineal", "Cuadrática", "Logarítmica"], 0, "O(1) no crece con n."],
      ["¿Acceder por índice en un array es?", ["O(n)", "O(1)", "O(log n)", "O(n^2)"], 1, "El acceso indexado es constante."],
    ]),
    fase(3, [
      ["¿Qué complejidad tiene buscar un valor en un array no ordenado?", ["O(1)", "O(n)", "O(log n)", "O(n log n)"], 1, "Hay que recorrer en el peor caso."],
      ["¿Qué es un árbol binario?", ["Cada nodo tiene hasta dos hijos", "Una lista", "Una cola", "Un grafo cíclico"], 0, "Los nodos tienen hijo izquierdo y derecho."],
      ["¿Qué ventaja tiene una lista enlazada sobre un array?", ["Inserción/borrado O(1) en posiciones conocidas sin desplazar", "Acceso O(1) por índice", "Menos memoria por nodo", "Búsqueda O(1)"], 0, "No requiere mover elementos contiguos."],
      ["¿Qué operación mira el tope de la pila sin quitarlo?", ["pop", "peek", "push", "poll"], 1, "peek consulta el tope."],
      ["¿Qué estructura es ideal para deshacer/rehacer (undo)?", ["Cola", "Pila", "Árbol", "Grafo"], 1, "La pila modela el historial LIFO."],
    ]),
    fase(4, [
      ["¿Qué complejidad promedio tiene buscar en una tabla hash?", ["O(n)", "O(1)", "O(log n)", "O(n log n)"], 1, "El hashing da acceso casi constante."],
      ["¿Qué es una colisión en una tabla hash?", ["Dos claves distintas caen en el mismo bucket", "Un error de índice", "Un árbol desbalanceado", "Una pila llena"], 0, "Se resuelve con encadenamiento o direccionamiento abierto."],
      ["¿Qué es un BST (árbol binario de búsqueda)?", ["Izquierda < nodo < derecha, permite búsqueda ordenada", "Un árbol sin orden", "Una cola", "Un grafo"], 0, "El orden permite buscar en O(log n) si está balanceado."],
      ["¿Qué complejidad tiene la búsqueda en un BST balanceado?", ["O(n)", "O(log n)", "O(1)", "O(n^2)"], 1, "La altura logarítmica acelera la búsqueda."],
      ["¿Qué es un grafo?", ["Nodos conectados por aristas (relaciones)", "Un árbol jerárquico", "Una pila", "Una cola"], 0, "Modela redes: nodos y conexiones."],
    ]),
    fase(5, [
      ["¿Qué estructura usa BFS para explorar por niveles?", ["Pila", "Cola", "Árbol AVL", "Heap"], 1, "BFS usa una cola."],
      ["¿Qué estructura usa DFS típicamente?", ["Cola", "Pila (o recursión)", "Heap", "Hash"], 1, "DFS usa pila/recursión."],
      ["¿Qué es un heap (montículo)?", ["Árbol donde el padre cumple una prioridad sobre los hijos", "Una tabla hash", "Una cola simple", "Un grafo"], 0, "El heap da acceso O(1) al mínimo/máximo."],
      ["¿Para qué sirve una cola de prioridad?", ["Atender siempre el elemento de mayor/menor prioridad", "FIFO estricto", "LIFO estricto", "Acceso aleatorio"], 0, "Se implementa comúnmente con un heap."],
      ["¿Qué complejidad tiene insertar en un heap?", ["O(1)", "O(log n)", "O(n)", "O(n log n)"], 1, "Se reordena por la altura logarítmica."],
    ]),
    fase(6, [
      ["¿Qué problema resuelve un árbol balanceado (AVL/Red-Black)?", ["Evitar que el BST degenere en lista y pierda O(log n)", "Ahorrar memoria", "Ordenar hash", "Evitar colisiones"], 0, "El balanceo mantiene la altura logarítmica."],
      ["¿Qué es un trie (árbol de prefijos)?", ["Estructura para strings que comparte prefijos comunes", "Un heap", "Una cola", "Un grafo cíclico"], 0, "Eficiente para autocompletado y diccionarios."],
      ["¿Qué diferencia hay entre grafo dirigido y no dirigido?", ["El dirigido tiene aristas con sentido; el no dirigido, bidireccionales", "Son iguales", "El no dirigido tiene sentido", "El dirigido no tiene aristas"], 0, "La dirección modela relaciones asimétricas."],
      ["¿Qué representa una matriz de adyacencia?", ["Conexiones de un grafo en una matriz NxN", "Un árbol", "Una pila", "Una cola"], 0, "Adecuada para grafos densos."],
      ["¿Qué representa una lista de adyacencia?", ["Cada nodo guarda sus vecinos; eficiente en grafos dispersos", "Una matriz densa", "Un heap", "Un trie"], 0, "Ahorra memoria en grafos con pocas aristas."],
    ]),
    fase(7, [
      ["¿Qué trade-off tiene una tabla hash respecto al orden?", ["Acceso O(1) promedio pero no mantiene orden de claves", "Mantiene orden", "Es más lenta que un array", "No colisiona"], 0, "Para orden se usan árboles balanceados."],
      ["¿Cuándo una tabla hash degrada a O(n)?", ["Con muchas colisiones o mala función hash", "Nunca", "Siempre", "Solo con árboles"], 0, "Un hash pobre concentra elementos en pocos buckets."],
      ["¿Qué es un B-tree y dónde se usa?", ["Árbol multi-hijo optimizado para disco (índices de DB)", "Un heap binario", "Un trie", "Una pila"], 0, "Minimiza accesos a disco en bases de datos."],
      ["¿Qué es una lista doblemente enlazada?", ["Cada nodo apunta al siguiente y al anterior", "Un array", "Un heap", "Un trie"], 0, "Permite recorrido en ambas direcciones."],
      ["¿Qué estructura conviene para LRU cache?", ["Hash map + lista doblemente enlazada", "Solo un array", "Un heap", "Un trie"], 0, "Combina acceso O(1) y orden de uso."],
    ]),
    fase(8, [
      ["¿Qué garantiza el factor de carga bajo en una tabla hash?", ["Menos colisiones y operaciones cercanas a O(1)", "Más memoria siempre peor", "Orden de claves", "O(n) garantizado"], 0, "Se rehashea al superar cierto umbral."],
      ["¿Qué es el rehashing?", ["Redimensionar y redistribuir las claves al crecer la tabla", "Borrar la tabla", "Ordenar claves", "Un trie"], 0, "Mantiene el rendimiento al aumentar elementos."],
      ["¿Qué estructura se usa en el algoritmo de Dijkstra?", ["Cola de prioridad (heap)", "Pila", "Trie", "Array simple"], 0, "El heap selecciona el nodo de menor costo."],
      ["¿Qué es un DAG y un ejemplo de uso?", ["Grafo dirigido acíclico; p.ej. dependencias/tareas (topological sort)", "Un árbol binario", "Una cola", "Un heap"], 0, "Los DAG modelan orden de dependencias."],
      ["¿Qué complejidad tiene el ordenamiento topológico de un DAG?", ["O(V+E)", "O(n^2)", "O(log n)", "O(1)"], 0, "Recorre vértices y aristas una vez."],
    ]),
    fase(9, [
      ["¿Por qué un skip list es una alternativa a árboles balanceados?", ["Da búsqueda O(log n) probabilística con implementación más simple", "Es O(n)", "No permite orden", "Usa hashing"], 0, "Los niveles aleatorios aceleran la búsqueda."],
      ["¿Qué problema resuelve un union-find (disjoint set)?", ["Agrupar y consultar componentes conexas eficientemente", "Ordenar arrays", "Cachear", "Buscar strings"], 0, "Con path compression opera casi en O(1)."],
      ["¿Qué ventaja da una lista de adyacencia frente a matriz en grafos dispersos?", ["Menos memoria: O(V+E) en vez de O(V^2)", "Acceso O(1) a cualquier arista", "Mantiene orden", "Evita ciclos"], 0, "Es preferible cuando hay pocas aristas."],
      ["¿Qué es un heap binario de Fibonacci frente a uno binario?", ["Mejora amortizada de decrease-key, útil en Dijkstra teórico", "Es más simple", "No soporta prioridad", "Es un trie"], 0, "Ofrece mejores cotas amortizadas en ciertas operaciones."],
      ["¿Qué estructura optimiza consultas de rango (suma/mínimo) con actualizaciones?", ["Segment tree / Fenwick tree", "Una pila", "Una tabla hash", "Un trie"], 0, "Permiten consultas y updates en O(log n)."],
    ]),
    fase(10, [
      ["¿Qué trade-off central hay entre array y lista enlazada?", ["Array: acceso O(1) pero inserción costosa; lista: inserción O(1) pero acceso O(n)", "Ninguno", "La lista accede en O(1)", "El array inserta en O(1)"], 0, "Se elige según el patrón de operaciones."],
      ["¿Por qué la localidad de caché favorece a los arrays sobre listas enlazadas?", ["Los datos contiguos aprovechan la línea de caché; los nodos dispersos no", "No influye", "Las listas son contiguas", "El hardware prefiere punteros"], 0, "La contigüidad mejora el rendimiento real."],
      ["¿Qué estructura elegirías para autocompletado por prefijo a gran escala?", ["Trie (o variantes comprimidas como radix tree)", "Un heap", "Una cola", "Un array ordenado simple"], 0, "El trie comparte prefijos y busca rápido por ellos."],
      ["¿Qué garantiza un árbol balanceado frente a una tabla hash para rangos ordenados?", ["Consultas por rango y orden (in-order), que el hash no ofrece", "Acceso O(1)", "Menos memoria", "Evita colisiones"], 0, "Los árboles mantienen orden; el hash no."],
      ["¿Cómo se combinan estructuras en un LRU cache O(1)?", ["Hash map para acceso y lista doblemente enlazada para recencia", "Solo un heap", "Solo un array", "Solo un trie"], 0, "La combinación logra get/put en O(1)."],
    ]),
  ],
);

const algoritmos: QuizTema = tema(
  "algoritmos",
  "Algoritmos",
  "Complejidad, ordenamiento, búsqueda, recursión y técnicas de diseño.",
  [
    fase(1, [
      ["¿Qué es un algoritmo?", ["Una secuencia finita de pasos para resolver un problema", "Un lenguaje", "Una estructura de datos", "Un compilador"], 0, "El algoritmo define cómo resolver algo."],
      ["¿Qué mide la notación Big O?", ["El crecimiento del costo según el tamaño de la entrada", "El tamaño del archivo", "La memoria RAM total", "El número de líneas"], 0, "Big O describe la escalabilidad asintótica."],
      ["¿Cuál es más eficiente para grandes n: O(1) u O(n)?", ["O(n)", "O(1)", "Son iguales", "Depende del lenguaje"], 1, "O(1) es constante, mejor que lineal."],
      ["¿Qué hace la búsqueda lineal?", ["Recorre elemento por elemento hasta encontrar", "Divide a la mitad", "Ordena primero", "Usa hashing"], 0, "Revisa todos en el peor caso: O(n)."],
      ["¿Qué es la recursión?", ["Una función que se llama a sí misma", "Un bucle for", "Una tabla hash", "Un grafo"], 0, "La recursión resuelve subproblemas más pequeños."],
    ]),
    fase(2, [
      ["¿Qué requiere la búsqueda binaria?", ["Que la colección esté ordenada", "Una tabla hash", "Un grafo", "Nada especial"], 0, "Divide el rango ordenado a la mitad."],
      ["¿Qué complejidad tiene la búsqueda binaria?", ["O(n)", "O(log n)", "O(1)", "O(n^2)"], 1, "Descarta la mitad en cada paso."],
      ["¿Qué necesita toda recursión para terminar?", ["Un caso base", "Un array", "Un grafo", "Una pila explícita"], 0, "Sin caso base hay recursión infinita."],
      ["¿Qué complejidad tiene recorrer una matriz NxN completa?", ["O(n)", "O(n^2)", "O(log n)", "O(1)"], 1, "Dos bucles anidados dan cuadrática."],
      ["¿Qué es un algoritmo de ordenamiento?", ["Reorganiza elementos según un criterio", "Busca elementos", "Cifra datos", "Comprime"], 0, "Ordena la colección (asc/desc)."],
    ]),
    fase(3, [
      ["¿Qué complejidad promedio tiene un buen algoritmo de ordenamiento por comparación?", ["O(n)", "O(n log n)", "O(n^2)", "O(1)"], 1, "Merge/quick/heap sort logran O(n log n)."],
      ["¿Qué complejidad tiene bubble sort en el peor caso?", ["O(n)", "O(n log n)", "O(n^2)", "O(log n)"], 2, "Comparaciones anidadas lo hacen cuadrático."],
      ["¿Qué técnica usa merge sort?", ["Divide y vencerás", "Programación dinámica", "Voraz", "Backtracking"], 0, "Divide, ordena mitades y combina."],
      ["¿Qué es la complejidad espacial?", ["La memoria adicional que usa el algoritmo según la entrada", "El tiempo de CPU", "El tamaño del disco", "El número de bucles"], 0, "Mide el uso de memoria extra."],
      ["¿Qué algoritmo elige repetidamente el mínimo y lo coloca al frente?", ["Selection sort", "Merge sort", "Quick sort", "Búsqueda binaria"], 0, "Selection sort selecciona el menor en cada pasada."],
    ]),
    fase(4, [
      ["¿Qué es divide y vencerás?", ["Dividir el problema en subproblemas, resolverlos y combinar", "Elegir lo óptimo local", "Probar todo con backtracking", "Memoizar"], 0, "Merge sort y binary search lo aplican."],
      ["¿Qué caracteriza a un algoritmo voraz (greedy)?", ["Elige el óptimo local en cada paso esperando el global", "Prueba todas las opciones", "Memoiza subproblemas", "Divide siempre"], 0, "No siempre da el óptimo global."],
      ["¿Qué es programación dinámica?", ["Resolver subproblemas superpuestos y reutilizar sus resultados", "Elegir local", "Dividir sin reutilizar", "Ordenar"], 0, "Evita recomputar con memoización/tabulación."],
      ["¿Qué complejidad tiene el Fibonacci recursivo ingenuo?", ["O(n)", "O(2^n)", "O(log n)", "O(n^2)"], 1, "Recalcula subproblemas exponencialmente."],
      ["¿Cómo se optimiza Fibonacci con memoización?", ["Guardando resultados ya calculados: O(n)", "No se puede", "Con backtracking", "Con greedy"], 0, "La memoización reduce a O(n)."],
    ]),
    fase(5, [
      ["¿Qué es backtracking?", ["Construir soluciones y retroceder al llegar a un callejón sin salida", "Elegir local siempre", "Dividir y combinar", "Ordenar"], 0, "Explora el espacio de soluciones podando ramas."],
      ["¿Qué recorrido de grafo explora por niveles?", ["DFS", "BFS", "Dijkstra", "Backtracking"], 1, "BFS visita vecinos antes de profundizar."],
      ["¿Qué recorrido profundiza hasta el fondo antes de retroceder?", ["BFS", "DFS", "Greedy", "Merge sort"], 1, "DFS explora un camino completo primero."],
      ["¿Para qué sirve el algoritmo de Dijkstra?", ["Camino más corto desde un origen con pesos no negativos", "Ordenar", "Buscar en hash", "Comprimir"], 0, "Encuentra distancias mínimas en grafos ponderados."],
      ["¿Qué estabilidad de ordenamiento significa?", ["Mantiene el orden relativo de elementos con igual clave", "Es más rápido", "Usa menos memoria", "Es recursivo"], 0, "Un sort estable preserva el orden de iguales."],
    ]),
    fase(6, [
      ["¿Qué complejidad tiene quicksort en el peor caso y por qué?", ["O(n^2) con pivotes mal elegidos", "O(n) siempre", "O(log n)", "O(1)"], 0, "Un mal pivote genera particiones desbalanceadas."],
      ["¿Cómo se mitiga el peor caso de quicksort?", ["Elegir pivote aleatorio o mediana de tres", "Usar bubble sort", "Sin solución", "Ordenar dos veces"], 0, "La aleatorización evita el peor caso sistemático."],
      ["¿Qué garantiza merge sort frente a quicksort?", ["O(n log n) garantizado y estabilidad, a costa de O(n) memoria", "Es in-place", "Es más rápido siempre", "Usa menos memoria"], 0, "Merge sort es estable y predecible."],
      ["¿Qué es un ordenamiento que NO es por comparación?", ["Counting/radix sort (usa claves enteras)", "Merge sort", "Quick sort", "Heap sort"], 0, "Pueden lograr O(n) bajo ciertas condiciones."],
      ["¿Qué cota inferior tiene el ordenamiento por comparación?", ["O(n log n)", "O(n)", "O(1)", "O(log n)"], 0, "Ningún sort por comparación baja de n log n."],
    ]),
    fase(7, [
      ["¿Qué diferencia hay entre memoización y tabulación en DP?", ["Memoización es top-down (recursiva); tabulación es bottom-up (iterativa)", "Son iguales", "Tabulación es recursiva", "Memoización no cachea"], 0, "Ambas evitan recomputar, con enfoques distintos."],
      ["¿Cuándo NO garantiza óptimo un algoritmo greedy?", ["Cuando el problema no cumple la propiedad de elección voraz/subestructura óptima", "Nunca falla", "Siempre falla", "Solo con grafos"], 0, "Ej.: cambio de monedas con ciertas denominaciones."],
      ["¿Qué algoritmo halla caminos mínimos con pesos negativos (sin ciclos negativos)?", ["Bellman-Ford", "Dijkstra", "BFS", "Quick sort"], 0, "Bellman-Ford tolera pesos negativos."],
      ["¿Qué complejidad tiene BFS/DFS sobre un grafo?", ["O(V+E)", "O(V^2) siempre", "O(log V)", "O(1)"], 0, "Visitan cada vértice y arista una vez."],
      ["¿Qué es la complejidad amortizada?", ["Costo promedio por operación en una secuencia, aunque alguna sea costosa", "El peor caso único", "El mejor caso", "La memoria"], 0, "Ej.: el resize de un array dinámico."],
    ]),
    fase(8, [
      ["¿Qué técnica resuelve la mochila 0/1 óptimamente?", ["Programación dinámica", "Greedy", "Búsqueda binaria", "BFS"], 0, "La DP explora combinaciones reutilizando subproblemas."],
      ["¿Por qué greedy sí funciona en la mochila fraccionaria?", ["Se puede tomar fracciones, y elegir la mejor razón valor/peso es óptimo", "No funciona", "Por casualidad", "Por backtracking"], 0, "La subestructura óptima se cumple al fraccionar."],
      ["¿Qué es la relajación de aristas en caminos mínimos?", ["Actualizar la distancia si se halla un camino más corto", "Ordenar aristas", "Eliminar aristas", "Un backtracking"], 0, "Es la operación central de Dijkstra/Bellman-Ford."],
      ["¿Qué garantiza el árbol de expansión mínima (MST)?", ["Conectar todos los nodos con el menor peso total sin ciclos", "El camino más corto entre dos nodos", "Ordenar el grafo", "Un DAG"], 0, "Prim/Kruskal construyen el MST."],
      ["¿Qué estructura acelera Kruskal para detectar ciclos?", ["Union-Find (disjoint set)", "Un heap binario", "Una cola", "Un trie"], 0, "Union-Find agrupa componentes eficientemente."],
    ]),
    fase(9, [
      ["¿Qué significa que un problema sea NP-completo?", ["Está en NP y es al menos tan difícil como cualquier otro de NP", "Se resuelve en O(1)", "No tiene solución", "Es lineal"], 0, "No se conoce solución polinómica general."],
      ["¿Qué es una heurística frente a un algoritmo exacto?", ["Da buenas soluciones aproximadas rápido, sin garantizar el óptimo", "Siempre óptima", "Más lenta siempre", "No termina"], 0, "Útil cuando el óptimo es intratable."],
      ["¿Qué garantiza un algoritmo de aproximación con factor 2?", ["La solución nunca es peor que el doble del óptimo", "Es exacta", "Es aleatoria", "Es lineal"], 0, "Acota qué tan lejos del óptimo puede estar."],
      ["¿Por qué Dijkstra falla con pesos negativos?", ["Asume que al fijar un nodo su distancia es definitiva, lo cual se rompe", "Es muy lento", "No usa heap", "Por memoria"], 0, "Un peso negativo podría mejorar un nodo ya fijado."],
      ["¿Qué técnica usa 'divide y vencerás' con recurrencia analizable por el teorema maestro?", ["Estimar la complejidad de algoritmos recursivos como merge sort", "Ordenar hash", "Backtracking", "Greedy"], 0, "El teorema maestro resuelve recurrencias comunes."],
    ]),
    fase(10, [
      ["¿Qué trade-off central hay entre tiempo y espacio en algoritmos?", ["A menudo se gana velocidad usando más memoria (p.ej. memoización) y viceversa", "No existe", "Siempre ganan ambos", "Solo importa el tiempo"], 0, "El space-time tradeoff guía muchas decisiones."],
      ["¿Por qué el análisis asintótico ignora constantes pero importan en la práctica?", ["Big O predice escalabilidad; en tamaños reales, constantes y caché deciden", "Las constantes no importan nunca", "Big O mide memoria RAM", "Es irrelevante"], 0, "Un O(n) con constante alta puede perder ante O(n log n) pequeño en datos reales."],
      ["¿Qué implica que la mochila 0/1 sea NP-difícil para el diseño?", ["Se usa DP pseudopolinómica o heurísticas según el tamaño", "Tiene solución O(n)", "No se puede aproximar", "Es lineal"], 0, "El enfoque depende de las restricciones del problema."],
      ["¿Cuándo conviene una solución aproximada frente a la exacta?", ["Cuando el óptimo es intratable y una buena solución rápida basta", "Nunca", "Siempre", "Solo en ordenamiento"], 0, "Es un equilibrio entre calidad y tiempo."],
      ["¿Qué garantiza elegir la estructura de datos correcta para un algoritmo?", ["Puede cambiar la complejidad total (p.ej. heap en Dijkstra)", "No influye", "Solo afecta memoria", "Siempre O(1)"], 0, "El algoritmo y la estructura se diseñan juntos."],
    ]),
  ],
);

const poo: QuizTema = tema(
  "poo",
  "Programación orientada a objetos",
  "Clases, objetos, encapsulación, herencia, polimorfismo y principios SOLID.",
  [
    fase(1, [
      ["¿Qué es una clase?", ["Una plantilla para crear objetos", "Un objeto concreto", "Una función suelta", "Una variable"], 0, "La clase define atributos y métodos."],
      ["¿Qué es un objeto?", ["Una instancia concreta de una clase", "Una plantilla", "Un método estático", "Un tipo primitivo"], 0, "El objeto es una instancia con estado propio."],
      ["¿Qué es un atributo (propiedad)?", ["Un dato que describe el estado del objeto", "Una acción", "Una clase", "Un módulo"], 0, "Los atributos guardan el estado."],
      ["¿Qué es un método?", ["Una función asociada a una clase/objeto (comportamiento)", "Un atributo", "Una variable global", "Un tipo"], 0, "Los métodos definen el comportamiento."],
      ["¿Qué método inicializa un objeto al crearse?", ["El destructor", "El constructor", "Un getter", "Un setter"], 1, "El constructor prepara el estado inicial."],
    ]),
    fase(2, [
      ["¿Qué es la encapsulación?", ["Ocultar el estado interno y exponerlo controladamente", "Heredar de otra clase", "Redefinir métodos", "Crear objetos"], 0, "Protege los datos tras una interfaz."],
      ["¿Para qué sirven getters y setters?", ["Acceder/modificar atributos privados de forma controlada", "Heredar", "Crear clases", "Destruir objetos"], 0, "Permiten validar y encapsular el acceso."],
      ["¿Qué modificador hace privado un atributo?", ["public", "private", "global", "static"], 1, "private restringe el acceso a la clase."],
      ["¿Qué es la herencia?", ["Una clase reutiliza y extiende a otra", "Copiar código a mano", "Ocultar datos", "Crear objetos"], 0, "Modela relaciones 'es-un'."],
      ["¿Qué es la clase base (padre/superclase)?", ["La clase de la que otras heredan", "La instancia", "El destructor", "Un método"], 0, "Provee atributos/métodos comunes."],
    ]),
    fase(3, [
      ["¿Qué es el polimorfismo?", ["Tratar objetos de distintas clases mediante una interfaz común", "Ocultar atributos", "Heredar constructores", "Crear instancias"], 0, "El mismo mensaje se comporta según el tipo real."],
      ["¿Qué es la abstracción?", ["Exponer lo esencial ocultando detalles de implementación", "Copiar clases", "Instanciar", "Destruir"], 0, "Modela el problema con conceptos relevantes."],
      ["¿Qué es la sobrescritura (override)?", ["Redefinir en la subclase un método de la superclase", "Mismo nombre distintos parámetros", "Crear un getter", "Un constructor"], 0, "El override cambia el comportamiento heredado."],
      ["¿Qué es la sobrecarga (overload)?", ["Mismo nombre de método con distintas firmas de parámetros", "Redefinir en subclase", "Un destructor", "Un atributo"], 0, "El overload distingue por parámetros."],
      ["¿Qué es una interfaz/contrato?", ["Un conjunto de métodos que una clase promete implementar", "Una instancia", "Un atributo", "Un constructor"], 0, "Define capacidades sin implementación."],
    ]),
    fase(4, [
      ["¿Qué es una clase abstracta?", ["No se instancia; define una base parcial para subclases", "Una instancia", "Una interfaz sin métodos", "Un objeto"], 0, "Puede tener métodos abstractos y concretos."],
      ["¿Qué relación modela la composición?", ["'tiene-un' (un objeto contiene a otros)", "'es-un'", "Sobrecarga", "Encapsulación"], 0, "La composición arma objetos con partes."],
      ["¿Por qué preferir composición sobre herencia a menudo?", ["Menos acoplamiento y más flexibilidad que jerarquías rígidas", "Es más rápido", "Oculta datos", "Es obligatorio"], 0, "La herencia profunda acopla y es frágil."],
      ["¿Qué es this/self?", ["Referencia al objeto actual", "La superclase", "Un método estático", "Un atributo global"], 0, "Apunta a la instancia en curso."],
      ["¿Qué es un miembro estático?", ["Pertenece a la clase, no a las instancias", "Es privado siempre", "Es un constructor", "Es abstracto"], 0, "Se comparte entre todas las instancias."],
    ]),
    fase(5, [
      ["¿Qué es el acoplamiento?", ["El grado de dependencia entre módulos/clases", "La cohesión interna", "La herencia", "El polimorfismo"], 0, "Se busca bajo acoplamiento."],
      ["¿Qué es la cohesión?", ["Qué tan enfocada está una clase en una sola responsabilidad", "La dependencia externa", "La herencia", "La abstracción"], 0, "Se busca alta cohesión."],
      ["¿Qué principio dice que una clase debe tener una sola razón para cambiar?", ["Single Responsibility (SRP)", "Open/Closed", "Liskov", "Dependency Inversion"], 0, "SRP: una responsabilidad por clase."],
      ["¿Qué principio dice 'abierto a extensión, cerrado a modificación'?", ["Open/Closed (OCP)", "SRP", "Interface Segregation", "Liskov"], 0, "OCP favorece extender sin tocar lo existente."],
      ["¿Qué es la inyección de dependencias?", ["Proveer las dependencias desde afuera en vez de crearlas dentro", "Heredar", "Sobrecargar", "Instanciar todo"], 0, "Reduce acoplamiento y mejora pruebas."],
    ]),
    fase(6, [
      ["¿Qué exige el principio de sustitución de Liskov (LSP)?", ["Un subtipo debe poder usarse donde se espera el tipo base sin romper", "Una sola responsabilidad", "Interfaces pequeñas", "Invertir dependencias"], 0, "Las subclases deben respetar el contrato base."],
      ["¿Qué dice Interface Segregation (ISP)?", ["Muchas interfaces específicas mejor que una general enorme", "Una responsabilidad", "Invertir dependencias", "Cerrado a extensión"], 0, "Evita forzar a implementar métodos que no se usan."],
      ["¿Qué dice Dependency Inversion (DIP)?", ["Depender de abstracciones, no de implementaciones concretas", "Una responsabilidad", "Interfaces pequeñas", "Sustitución"], 0, "Los módulos de alto nivel no dependen de detalles."],
      ["¿Qué es un patrón de diseño?", ["Una solución reutilizable a un problema recurrente de diseño", "Un lenguaje", "Una clase base", "Un framework"], 0, "Los patrones capturan buenas prácticas probadas."],
      ["¿Qué hace el patrón Singleton?", ["Garantiza una única instancia global de una clase", "Crea muchas instancias", "Hereda", "Sobrecarga"], 0, "Provee un punto de acceso único."],
    ]),
    fase(7, [
      ["¿Qué problema resuelve el patrón Factory?", ["Crear objetos sin acoplar el código a clases concretas", "Ordenar datos", "Cifrar", "Heredar"], 0, "Encapsula la lógica de creación."],
      ["¿Qué hace el patrón Observer?", ["Notificar a suscriptores cuando cambia el estado de un sujeto", "Crear instancias", "Ordenar", "Cifrar"], 0, "Modela pub/sub entre objetos."],
      ["¿Qué hace el patrón Strategy?", ["Intercambiar algoritmos encapsulados en tiempo de ejecución", "Crear una única instancia", "Notificar cambios", "Heredar"], 0, "Permite elegir el comportamiento dinámicamente."],
      ["¿Por qué el Singleton puede considerarse un antipatrón?", ["Introduce estado global y acoplamiento que dificulta pruebas", "Es muy rápido", "No compila", "Es abstracto"], 0, "El estado global oculto complica el testing."],
      ["¿Qué es la ley de Demeter?", ["'Habla solo con tus vecinos': no encadenar accesos profundos a objetos ajenos", "Herencia profunda", "Sobrecarga", "Singleton"], 0, "Reduce el acoplamiento entre objetos."],
    ]),
    fase(8, [
      ["¿Por qué la herencia profunda se considera frágil?", ["Cambios en la base propagan efectos difíciles de predecir a subclases", "Es más lenta", "No compila", "Oculta datos"], 0, "El 'fragile base class problem' motiva la composición."],
      ["¿Qué violación de LSP es típica?", ["Una subclase que lanza excepción o cambia el contrato del método base", "Agregar un método", "Renombrar la clase", "Usar interfaces"], 0, "Rompe la sustituibilidad esperada."],
      ["¿Qué facilita programar contra interfaces (DIP + ISP)?", ["Sustituir implementaciones y testear con mocks fácilmente", "Más acoplamiento", "Menos cohesión", "Herencia forzada"], 0, "Desacopla el qué del cómo."],
      ["¿Qué hace el patrón Adapter?", ["Convertir la interfaz de una clase en otra que el cliente espera", "Crear instancias únicas", "Notificar cambios", "Ordenar"], 0, "Permite colaborar a clases con interfaces incompatibles."],
      ["¿Qué hace el patrón Decorator?", ["Añadir responsabilidades a un objeto dinámicamente sin subclasear", "Crear un singleton", "Un factory", "Un observer"], 0, "Envuelve el objeto agregando comportamiento."],
    ]),
    fase(9, [
      ["¿Qué trade-off tiene aplicar muchos patrones sin necesidad?", ["Sobreingeniería: complejidad innecesaria (YAGNI)", "Siempre mejora", "Menos código", "Más rápido"], 0, "Los patrones resuelven problemas reales, no imaginarios."],
      ["¿Qué principio guía 'no repitas lógica'?", ["DRY (Don't Repeat Yourself)", "KISS", "YAGNI", "SRP"], 0, "DRY evita duplicación que se desincroniza."],
      ["¿Qué equilibra DRY con la claridad?", ["A veces una abstracción prematura acopla más que duplicar un poco", "Nunca duplicar nada", "Duplicar siempre", "No aplica"], 0, "La abstracción incorrecta puede ser peor que la duplicación."],
      ["¿Qué hace el patrón Repository en el dominio?", ["Abstrae la persistencia tras una interfaz orientada al dominio", "Crea singletons", "Notifica", "Ordena"], 0, "Desacopla la lógica de negocio del almacenamiento."],
      ["¿Qué garantiza inyectar dependencias por constructor?", ["Dependencias explícitas e inmutables, fáciles de testear", "Estado global", "Acoplamiento oculto", "Herencia"], 0, "El objeto declara claramente qué necesita."],
    ]),
    fase(10, [
      ["¿Qué trade-off central hay entre herencia y composición?", ["Herencia reutiliza pero acopla jerárquicamente; composición es flexible pero más verbosa", "Ninguno", "La herencia es siempre mejor", "La composición acopla más"], 0, "Se prefiere composición para flexibilidad."],
      ["¿Por qué SOLID mejora la mantenibilidad a largo plazo?", ["Reduce acoplamiento y facilita extender/cambiar sin romper", "Acelera la CPU", "Reduce memoria", "Es cosmético"], 0, "Son principios para diseños sostenibles."],
      ["¿Cuándo un patrón de diseño se vuelve contraproducente?", ["Cuando añade complejidad sin resolver un problema real (over-engineering)", "Nunca", "Siempre ayuda", "Solo en herencia"], 0, "El contexto decide si un patrón aporta."],
      ["¿Qué garantiza programar orientado a abstracciones en un sistema grande?", ["Módulos intercambiables y testeables sin reescribir a los consumidores", "Más acoplamiento", "Menos cohesión", "Herencia forzada"], 0, "Las abstracciones estables aíslan el cambio."],
      ["¿Qué equilibrio buscan los principios KISS, DRY y YAGNI juntos?", ["Simplicidad, sin duplicación y sin construir lo que aún no se necesita", "Máxima abstracción siempre", "Duplicar por velocidad", "Ignorar el diseño"], 0, "Balancean pragmatismo y calidad de diseño."],
    ]),
  ],
);

const htmlCss: QuizTema = tema(
  "html-css",
  "HTML y CSS",
  "Estructura semántica, el modelo de caja, flexbox, grid y diseño responsivo.",
  [
    fase(1, [
      ["¿Qué significa HTML?", ["HyperText Markup Language", "High Text Modern Language", "Hyperlink Machine Language", "Home Tool Markup"], 0, "HTML estructura el contenido web."],
      ["¿Qué etiqueta crea un enlace?", ["<link>", "<a>", "<href>", "<url>"], 1, "<a href> crea hipervínculos."],
      ["¿Qué etiqueta muestra una imagen?", ["<image>", "<img>", "<pic>", "<src>"], 1, "<img src> inserta imágenes."],
      ["¿Qué significa CSS?", ["Cascading Style Sheets", "Computer Style System", "Creative Style Syntax", "Colorful Style Sheets"], 0, "CSS da estilo a los documentos HTML."],
      ["¿Qué etiqueta crea un párrafo?", ["<par>", "<p>", "<text>", "<span>"], 1, "<p> define un párrafo."],
    ]),
    fase(2, [
      ["¿Qué etiqueta define el contenido principal del documento?", ["<section>", "<main>", "<div>", "<content>"], 1, "<main> marca el contenido principal."],
      ["¿Qué atributo identifica de forma única un elemento?", ["class", "id", "name", "key"], 1, "id debe ser único en la página."],
      ["¿Qué propiedad CSS cambia el color del texto?", ["background", "color", "font", "text-color"], 1, "color define el color del texto."],
      ["¿Qué propiedad controla el espacio interno de un elemento?", ["margin", "padding", "border", "gap"], 1, "padding es el espacio interior."],
      ["¿Qué propiedad controla el espacio exterior de un elemento?", ["padding", "margin", "border", "gap"], 1, "margin es el espacio exterior."],
    ]),
    fase(3, [
      ["¿Qué compone el modelo de caja de afuera hacia adentro?", ["margin, border, padding, content", "content, padding, border, margin", "padding, margin, content, border", "border, margin, padding, content"], 0, "El box model va margin → border → padding → content."],
      ["¿Qué selector CSS apunta a una clase?", ["#nombre", ".nombre", "nombre", "*nombre"], 1, ".clase selecciona por class."],
      ["¿Qué selector apunta a un id?", [".nombre", "#nombre", "nombre", "@nombre"], 1, "#id selecciona por id."],
      ["¿Qué etiqueta semántica define un encabezado de sección/página?", ["<head>", "<header>", "<top>", "<h>"], 1, "<header> agrupa contenido introductorio."],
      ["¿Qué etiqueta define navegación?", ["<navigate>", "<nav>", "<menu-bar>", "<links>"], 1, "<nav> agrupa enlaces de navegación."],
    ]),
    fase(4, [
      ["¿Qué valor de display crea un contenedor flex?", ["block", "flex", "grid", "inline"], 1, "display: flex activa flexbox."],
      ["¿Qué propiedad alinea items flex en el eje principal?", ["align-items", "justify-content", "align-content", "place-items"], 1, "justify-content controla el eje principal."],
      ["¿Qué propiedad alinea items flex en el eje transversal?", ["justify-content", "align-items", "justify-items", "gap"], 1, "align-items controla el eje cruzado."],
      ["¿Qué es una media query?", ["Aplicar estilos según características del dispositivo (ancho, etc.)", "Una etiqueta HTML", "Un selector de id", "Una animación"], 0, "@media adapta el diseño a la pantalla."],
      ["¿Qué unidad es relativa al tamaño de fuente raíz?", ["px", "rem", "pt", "cm"], 1, "rem se basa en el font-size del root."],
    ]),
    fase(5, [
      ["¿Qué propiedad define columnas y filas en CSS Grid?", ["grid-template", "flex-direction", "float", "position"], 0, "grid-template-columns/rows define la cuadrícula."],
      ["¿Qué hace position: absolute?", ["Posiciona respecto al ancestro posicionado más cercano", "Sigue el flujo normal", "Es fijo al viewport", "Centra el elemento"], 0, "Se saca del flujo y se ubica respecto al contenedor posicionado."],
      ["¿Qué controla z-index?", ["El orden de apilamiento de elementos posicionados", "El zoom", "La opacidad", "El margen"], 0, "Mayor z-index se dibuja por delante."],
      ["¿Qué es el diseño responsivo?", ["Adaptar la interfaz a distintos tamaños de pantalla", "Usar solo px", "Fijar el ancho", "Ocultar en móvil"], 0, "Responde a múltiples dispositivos."],
      ["¿Qué propiedad crea espacio entre items en flex/grid?", ["margin", "gap", "padding", "space"], 1, "gap separa filas/columnas."],
    ]),
    fase(6, [
      ["¿Qué es la especificidad en CSS?", ["El peso que decide qué regla gana ante conflictos", "El orden alfabético", "El tamaño del archivo", "La cantidad de reglas"], 0, "id > clase > etiqueta en especificidad."],
      ["¿Qué unidades son relativas al viewport?", ["vw y vh", "px y pt", "cm y mm", "em y rem"], 0, "vw/vh se basan en el ancho/alto de la ventana."],
      ["¿Qué hace box-sizing: border-box?", ["Incluye padding y border dentro del width declarado", "Excluye el border", "Duplica el tamaño", "Centra el elemento"], 0, "Simplifica el cálculo de tamaños."],
      ["¿Qué diferencia hay entre em y rem?", ["em es relativo al padre; rem al root", "Son iguales", "rem es relativo al padre", "em es absoluto"], 0, "rem evita la acumulación de em anidados."],
      ["¿Qué es un pseudo-elemento como ::before?", ["Inserta contenido generado antes del contenido del elemento", "Un selector de id", "Una media query", "Una variable"], 0, "::before/::after generan contenido decorativo."],
    ]),
    fase(7, [
      ["¿Qué diferencia hay entre position: sticky y fixed?", ["sticky alterna entre relative y fixed según el scroll; fixed es siempre relativo al viewport", "Son iguales", "sticky es al viewport", "fixed sigue el scroll del padre"], 0, "sticky se 'pega' al alcanzar un umbral."],
      ["¿Qué son las CSS custom properties (variables)?", ["Valores reutilizables con --var y var()", "Selectores nuevos", "Media queries", "Pseudo-clases"], 0, "Permiten temas y reutilización de valores."],
      ["¿Qué propiedad habilita el modo oscuro según el sistema?", ["@media (prefers-color-scheme: dark)", "@media print", "@supports", "@keyframes"], 0, "prefers-color-scheme detecta el tema del SO."],
      ["¿Qué hace @supports?", ["Aplica estilos si el navegador soporta una característica CSS", "Detecta el ancho", "Crea animaciones", "Importa fuentes"], 0, "@supports hace mejora progresiva."],
      ["¿Qué define @keyframes?", ["Los pasos de una animación CSS", "Una media query", "Una variable", "Un grid"], 0, "@keyframes describe la animación por fotogramas."],
    ]),
    fase(8, [
      ["¿Qué provoca el colapso de márgenes (margin collapsing)?", ["Márgenes verticales adyacentes se combinan en uno solo", "Se suman siempre", "Desaparecen ambos", "Se duplican"], 0, "Es un comportamiento clásico del flujo en bloque."],
      ["¿Qué crea un nuevo contexto de apilamiento (stacking context)?", ["position + z-index, opacity < 1, transform, etc.", "Solo el ancho", "Solo el color", "Solo el margin"], 0, "Ciertas propiedades aíslan el apilamiento de sus hijos."],
      ["¿Qué diferencia hay entre grid-template-areas y solo columnas/filas?", ["areas permite nombrar zonas para colocar items semánticamente", "Son iguales", "areas no existe", "columnas nombran zonas"], 0, "Las áreas hacen el layout más legible."],
      ["¿Qué controla minmax() en grid?", ["Un tamaño de pista con mínimo y máximo (responsivo)", "El z-index", "La opacidad", "El margin"], 0, "Ej.: minmax(200px, 1fr) para columnas flexibles."],
      ["¿Qué hace la unidad fr en grid?", ["Reparte el espacio libre en fracciones", "Es píxeles", "Es un porcentaje del padre", "Es relativa a la fuente"], 0, "1fr toma una parte del espacio disponible."],
    ]),
    fase(9, [
      ["¿Qué causa layout thrashing y cómo afecta el rendimiento?", ["Leer y escribir el layout alternadamente fuerza múltiples reflows", "Solo cambia colores", "Mejora el FPS", "No afecta"], 0, "Se agrupan lecturas/escrituras para evitarlo."],
      ["¿Qué propiedades animan sin provocar reflow costoso?", ["transform y opacity (compositor)", "width y height", "margin y padding", "top y left"], 0, "Se animan en el compositor, evitando reflow/repaint."],
      ["¿Qué hace will-change?", ["Avisa al navegador que una propiedad cambiará, optimizando la capa", "Cambia el layout", "Crea variables", "Importa fuentes"], 0, "Debe usarse con moderación para no gastar memoria."],
      ["¿Qué es CLS (Cumulative Layout Shift)?", ["Métrica de estabilidad visual: cuánto se mueve el contenido", "El tiempo de carga", "El color de fondo", "La especificidad"], 0, "Reservar espacio para imágenes/anuncios reduce el CLS."],
      ["¿Por qué preferir clases utilitarias/BEM sobre selectores muy específicos?", ["Evita guerras de especificidad y facilita el mantenimiento", "Es más lento", "Rompe el HTML", "Reduce accesibilidad"], 0, "Mantiene la especificidad baja y predecible."],
    ]),
    fase(10, [
      ["¿Qué trade-off central hay entre Flexbox y Grid?", ["Flexbox es 1D (una dirección); Grid es 2D (filas y columnas)", "Son idénticos", "Grid es 1D", "Flexbox es 2D"], 0, "Se combinan según la necesidad del layout."],
      ["¿Por qué el HTML semántico importa más allá de la estética?", ["Mejora accesibilidad, SEO y mantenibilidad", "Es solo visual", "Reduce el CSS", "Acelera la CPU"], 0, "Los lectores de pantalla y buscadores lo aprovechan."],
      ["¿Qué garantiza un enfoque mobile-first en media queries?", ["Estilos base para móvil y mejoras progresivas para pantallas grandes", "Ocultar en móvil", "Más CSS siempre", "Menos accesible"], 0, "Prioriza el caso más restringido primero."],
      ["¿Qué problema resuelve container queries frente a media queries?", ["Adaptar un componente según el tamaño de su contenedor, no del viewport", "Detectar el SO", "Cambiar colores", "Importar fuentes"], 0, "Hacen los componentes verdaderamente reutilizables."],
      ["¿Por qué minimizar la especificidad mejora un sistema de diseño escalable?", ["Las reglas son predecibles y fáciles de sobrescribir sin !important", "Es más lento", "Rompe el grid", "Reduce el SEO"], 0, "La baja especificidad facilita mantener y extender estilos."],
    ]),
  ],
);

export const TEMAS_FUNDAMENTOS: QuizTema[] = [git, estructurasDatos, algoritmos, poo, htmlCss];
