import { fase, tema, type QuizTema } from "./tipos";

// Categoría: Lenguajes de programación.
// Temas: JavaScript, Python, Java, C#, C++. Cada uno con 10 fases (dificultad creciente).

const javascript: QuizTema = tema(
  "javascript",
  "JavaScript",
  "El lenguaje de la web: tipos, funciones, asincronía, closures y el motor de ejecución.",
  [
    fase(1, [
      ["¿Con qué palabra clave se declara una variable que NO se puede reasignar?", ["var", "let", "const", "static"], 2, "const crea una vinculación de solo lectura; no se puede reasignar."],
      ["¿Qué operador imprime en la consola del navegador?", ["print()", "echo", "console.log()", "System.out"], 2, "console.log() escribe en la consola."],
      ["¿Qué tipo de dato es \"Hola\"?", ["number", "string", "boolean", "object"], 1, "El texto entre comillas es un string."],
      ["¿Cuál es el resultado de typeof 42?", ["\"int\"", "\"number\"", "\"float\"", "\"digit\""], 1, "Todos los números en JS son de tipo number."],
      ["¿Cómo se escribe un comentario de una línea?", ["# comentario", "// comentario", "<!-- comentario -->", "/ comentario"], 1, "// inicia un comentario de línea en JS."],
    ]),
    fase(2, [
      ["¿Qué valor booleano representa una cadena vacía en una condición?", ["true", "false", "null", "undefined"], 1, "\"\" es un valor falsy, se evalúa como false."],
      ["¿Qué método convierte un string a número entero?", ["Number.round()", "parseInt()", "toFixed()", "String()"], 1, "parseInt() interpreta el string como entero."],
      ["¿Qué operador compara valor Y tipo sin coerción?", ["==", "===", "=", "!="], 1, "=== es la comparación estricta."],
      ["¿Cómo se accede al primer elemento de un array arr?", ["arr[1]", "arr[0]", "arr.first", "arr(0)"], 1, "Los arrays se indexan desde 0."],
      ["¿Qué palabra clave define una función?", ["func", "def", "function", "fn"], 2, "function declara una función en JS."],
    ]),
    fase(3, [
      ["¿Qué método agrega un elemento al final de un array?", ["push()", "pop()", "shift()", "concat()"], 0, "push() añade al final y devuelve la nueva longitud."],
      ["¿Qué devuelve \"5\" + 3?", ["8", "\"53\"", "53", "NaN"], 1, "El + con un string concatena: \"53\"."],
      ["¿Qué es un template literal?", ["Un comentario", "Una cadena con backticks que permite interpolación", "Un tipo numérico", "Un bucle"], 1, "Las backticks permiten `${expresión}` dentro del string."],
      ["¿Qué método recorre un array ejecutando una función por elemento sin retornar uno nuevo?", ["map()", "forEach()", "filter()", "reduce()"], 1, "forEach() itera pero retorna undefined."],
      ["¿Qué valor tiene una variable declarada pero no inicializada?", ["null", "0", "undefined", "NaN"], 2, "Sin asignar, su valor es undefined."],
    ]),
    fase(4, [
      ["¿Qué retorna [1,2,3].map(x => x * 2)?", ["[1,2,3]", "[2,4,6]", "6", "[1,4,9]"], 1, "map() transforma cada elemento y retorna un array nuevo."],
      ["¿Qué hace filter()?", ["Modifica el array original", "Retorna un array con los elementos que cumplen la condición", "Suma los elementos", "Ordena el array"], 1, "filter() crea un array nuevo con los que pasan el test."],
      ["¿Qué es una arrow function?", ["Una función con sintaxis => sin su propio this", "Una función asíncrona", "Un método de clase", "Un tipo de bucle"], 0, "Las arrow functions no tienen this propio."],
      ["¿Qué operador extrae elementos de un array en variables?", ["spread", "desestructuración", "ternario", "módulo"], 1, "La desestructuración asigna elementos a variables."],
      ["¿Qué hace el operador spread ...arr?", ["Borra el array", "Expande sus elementos", "Lo ordena", "Lo invierte"], 1, "spread expande los elementos de un iterable."],
    ]),
    fase(5, [
      ["¿Qué es un closure?", ["Un error de sintaxis", "Una función que recuerda variables de su ámbito externo", "Un tipo de objeto", "Un bucle infinito"], 1, "El closure captura el ámbito donde fue creado."],
      ["¿Qué devuelve una función async?", ["Un string", "Una Promise", "undefined siempre", "Un callback"], 1, "Las funciones async siempre retornan una Promise."],
      ["¿Qué palabra clave pausa una función async hasta resolver una promesa?", ["yield", "await", "pause", "defer"], 1, "await espera a que la promesa se resuelva."],
      ["¿Qué método une los elementos de un array en un string?", ["split()", "join()", "concat()", "slice()"], 1, "join() une con el separador indicado."],
      ["¿Qué retorna Object.keys({a:1, b:2})?", ["[1,2]", "[\"a\",\"b\"]", "2", "{a,b}"], 1, "Object.keys() devuelve el array de nombres de propiedad."],
    ]),
    fase(6, [
      ["¿Qué hace reduce()?", ["Filtra elementos", "Acumula los elementos en un solo valor", "Duplica el array", "Ordena descendente"], 1, "reduce() reduce el array a un único valor acumulado."],
      ["¿Qué es el event loop?", ["Un bucle for", "El mecanismo que coordina tareas asíncronas en el hilo único", "Un evento del DOM", "Un tipo de promesa"], 1, "El event loop atiende la cola cuando la pila está vacía."],
      ["¿Cuál es la diferencia entre null y undefined?", ["Son idénticos", "null es asignación intencional de vacío; undefined es ausencia de valor", "undefined es un objeto", "null es un número"], 1, "null se asigna a propósito; undefined es el estado por defecto."],
      ["¿Qué imprime typeof null?", ["\"null\"", "\"undefined\"", "\"object\"", "\"boolean\""], 2, "Es un error histórico de JS: typeof null es \"object\"."],
      ["¿Qué hace Promise.all([p1, p2])?", ["Ejecuta en serie", "Resuelve cuando TODAS las promesas se resuelven", "Resuelve con la primera", "Rechaza siempre"], 1, "Promise.all espera a que todas se resuelvan (o una rechace)."],
    ]),
    fase(7, [
      ["¿Qué es el hoisting?", ["Elevación de declaraciones al inicio de su ámbito", "Un método de array", "Un tipo de closure", "Una API del DOM"], 0, "Las declaraciones se 'elevan' al tope de su ámbito."],
      ["Con let, ¿existe hoisting?", ["No existe", "Sí, pero queda en la 'zona muerta temporal' hasta su declaración", "Se inicializa en undefined", "Se vuelve global"], 1, "let se eleva pero no es accesible antes de declararse (TDZ)."],
      ["¿Qué hace bind()?", ["Ejecuta la función", "Crea una nueva función con this fijado", "Elimina this", "Clona un objeto"], 1, "bind() retorna una función con this ligado permanentemente."],
      ["¿Qué es la coerción de tipos?", ["Conversión automática entre tipos", "Un error de sintaxis", "Un método", "Bloqueo de tipos"], 0, "JS convierte tipos automáticamente en ciertas operaciones."],
      ["¿Qué retorna [] == false?", ["true", "false", "TypeError", "undefined"], 0, "Por coerción, ambos lados se convierten a 0 y son iguales."],
    ]),
    fase(8, [
      ["¿Qué es un generador (function*)?", ["Una función que puede pausar y reanudar con yield", "Una función asíncrona", "Un constructor", "Un proxy"], 0, "Los generadores producen valores bajo demanda con yield."],
      ["¿Qué diferencia hay entre map y forEach?", ["Ninguna", "map retorna un array nuevo; forEach retorna undefined", "forEach es más rápido siempre", "map muta el original"], 1, "map produce un array transformado; forEach solo itera."],
      ["¿Qué hace Object.freeze(obj)?", ["Elimina el objeto", "Impide modificar sus propiedades", "Lo clona", "Lo convierte a JSON"], 1, "freeze hace el objeto inmutable a nivel superficial."],
      ["¿Qué es la 'zona muerta temporal' (TDZ)?", ["Un ámbito global", "El intervalo donde una variable let/const existe pero no es accesible", "Un error de red", "Un método de string"], 1, "La TDZ va desde el inicio del bloque hasta la declaración."],
      ["¿Qué operador fusiona valores solo si el izquierdo es null o undefined?", ["||", "??", "&&", "?."], 1, "El nullish coalescing (??) solo cae si es null/undefined."],
    ]),
    fase(9, [
      ["¿Qué es un WeakMap?", ["Un Map con claves objeto y referencias débiles (recolectables)", "Un Map ordenado", "Un array asociativo", "Un Set inmutable"], 0, "WeakMap no impide que sus claves sean recolectadas por el GC."],
      ["¿Qué hace un Proxy?", ["Congela un objeto", "Intercepta operaciones fundamentales sobre un objeto", "Clona profundamente", "Serializa a JSON"], 1, "Proxy define trampas (traps) para get, set, etc."],
      ["¿Cuál es la salida de setTimeout respecto a un Promise.then en la misma tanda?", ["El setTimeout siempre primero", "El microtask (then) se ejecuta antes que el macrotask (setTimeout)", "Se ejecutan a la vez", "Depende del navegador"], 1, "Las microtasks (promesas) tienen prioridad sobre las macrotasks."],
      ["¿Qué es el currying?", ["Transformar una función de N args en N funciones de 1 arg", "Un método de array", "Ordenar objetos", "Un tipo de closure asíncrono"], 0, "El currying descompone una función en funciones unarias encadenadas."],
      ["¿Qué hace structuredClone(obj)?", ["Copia superficial", "Copia profunda del objeto", "Congela el objeto", "Lo convierte a string"], 1, "structuredClone realiza una copia profunda."],
    ]),
    fase(10, [
      ["¿Por qué 0.1 + 0.2 !== 0.3 en JS?", ["Bug del motor", "Por la representación de punto flotante IEEE 754", "Por coerción de strings", "Por el event loop"], 1, "Los flotantes binarios no representan 0.1 y 0.2 exactamente."],
      ["¿Qué garantiza Object.is(NaN, NaN)?", ["false", "true", "TypeError", "undefined"], 1, "Object.is trata NaN como igual a NaN, a diferencia de ===."],
      ["¿Qué es un microtask queue frente a task queue?", ["Son lo mismo", "Las microtasks (promesas) se vacían por completo entre cada macrotask", "Las macrotasks tienen prioridad", "Solo existe en Node"], 1, "El event loop vacía todas las microtasks tras cada macrotask."],
      ["¿Qué patrón evita el 'callback hell' de forma nativa moderna?", ["with", "async/await", "eval", "var hoisting"], 1, "async/await aplana el código asíncrono."],
      ["¿Qué hace el símbolo Symbol.iterator en un objeto?", ["Lo congela", "Lo hace iterable (usable en for...of y spread)", "Lo serializa", "Define su prototipo"], 1, "Implementar Symbol.iterator define cómo se itera el objeto."],
    ]),
  ],
);

const python: QuizTema = tema(
  "python",
  "Python",
  "Sintaxis limpia, estructuras de datos, comprensiones, decoradores y el modelo de datos.",
  [
    fase(1, [
      ["¿Cómo se imprime texto en Python 3?", ["echo(\"hola\")", "print(\"hola\")", "console.log(\"hola\")", "printf(\"hola\")"], 1, "print() es la función de salida estándar."],
      ["¿Qué símbolo inicia un comentario?", ["//", "#", "--", "/*"], 1, "# comienza un comentario de línea en Python."],
      ["¿Cómo se define una lista vacía?", ["[]", "{}", "()", "list{}"], 0, "[] crea una lista vacía; {} sería un dict."],
      ["¿Qué tipo devuelve type(5)?", ["<class 'float'>", "<class 'int'>", "<class 'number'>", "<class 'str'>"], 1, "5 es un entero (int)."],
      ["¿Cómo se define una función?", ["function f():", "def f():", "func f():", "fn f():"], 1, "def define funciones en Python."],
    ]),
    fase(2, [
      ["¿Qué operador se usa para exponente (potencia)?", ["^", "**", "//", "pow"], 1, "** eleva a potencia: 2**3 == 8."],
      ["¿Qué hace len(\"hola\")?", ["Devuelve 4", "Devuelve \"hola\"", "Da error", "Devuelve 5"], 0, "len() cuenta los caracteres: 4."],
      ["¿Cómo se crea un diccionario?", ["[]", "()", "{clave: valor}", "<>"], 2, "{} con pares clave:valor define un dict."],
      ["¿Qué es la indentación en Python?", ["Opcional y decorativa", "Obligatoria: define los bloques de código", "Solo para comentarios", "Un tipo de dato"], 1, "La indentación delimita bloques (no llaves)."],
      ["¿Qué devuelve range(3)?", ["[1,2,3]", "Una secuencia 0,1,2", "[0,1,2,3]", "3"], 1, "range(3) genera 0,1,2."],
    ]),
    fase(3, [
      ["¿Qué es una list comprehension?", ["Un bucle infinito", "Sintaxis concisa para construir listas: [x for x in ...]", "Un tipo de función", "Un decorador"], 1, "Permite crear listas en una línea."],
      ["¿Qué hace \"abc\".upper()?", ["\"ABC\"", "\"abc\"", "Error", "\"Abc\""], 0, "upper() convierte a mayúsculas."],
      ["¿Cuál es la diferencia entre lista y tupla?", ["Ninguna", "La tupla es inmutable; la lista es mutable", "La lista es inmutable", "La tupla no ordena"], 1, "Las tuplas no se pueden modificar tras crearse."],
      ["¿Qué hace el slicing lst[1:3]?", ["Elementos en índices 1 y 2", "Elementos 1,2,3", "Solo el índice 3", "Invierte la lista"], 0, "El slice [1:3] toma desde 1 hasta 3 sin incluir 3."],
      ["¿Qué devuelve 10 // 3?", ["3.33", "3", "1", "4"], 1, "// es división entera: 3."],
    ]),
    fase(4, [
      ["¿Qué hace un f-string?", ["Formatea con f\"{variable}\"", "Convierte a float", "Filtra listas", "Define funciones"], 0, "Los f-strings interpolan expresiones con f\"...{x}...\"."],
      ["¿Qué método agrega un elemento al final de una lista?", ["add()", "append()", "push()", "insert_end()"], 1, "append() añade al final."],
      ["¿Qué es *args en una función?", ["Un puntero", "Recibe argumentos posicionales variables como tupla", "Un decorador", "Un tipo de retorno"], 1, "*args empaqueta argumentos posicionales adicionales."],
      ["¿Qué hace dict.get(\"k\")?", ["Da KeyError si falta", "Devuelve el valor o None si no existe", "Borra la clave", "Ordena el dict"], 1, "get() no lanza error: retorna None (o el default)."],
      ["¿Qué estructura NO permite elementos duplicados?", ["list", "tuple", "set", "dict values"], 2, "El set almacena elementos únicos."],
    ]),
    fase(5, [
      ["¿Qué es **kwargs?", ["Argumentos de palabra clave variables como dict", "Un operador de potencia", "Una lista", "Un decorador"], 0, "**kwargs empaqueta argumentos nombrados en un dict."],
      ["¿Qué hace enumerate(lista)?", ["Ordena", "Devuelve pares (índice, valor)", "Cuenta duplicados", "Invierte"], 1, "enumerate produce índice y valor en cada iteración."],
      ["¿Qué es un generador en Python?", ["Una lista grande", "Una función con yield que produce valores perezosamente", "Un decorador", "Un módulo"], 1, "yield produce valores bajo demanda sin cargar todo en memoria."],
      ["¿Qué hace zip([1,2],[3,4])?", ["[1,2,3,4]", "Pares (1,3),(2,4)", "[4,6]", "Error"], 1, "zip empareja elementos posición a posición."],
      ["¿Qué maneja un bloque try/except?", ["Bucles", "Excepciones (errores)", "Importaciones", "Decoradores"], 1, "try/except captura y maneja errores."],
    ]),
    fase(6, [
      ["¿Qué es un decorador?", ["Una función que envuelve y modifica otra función", "Un comentario", "Un tipo de bucle", "Una clase abstracta"], 0, "Un decorador (@) recibe una función y retorna otra."],
      ["¿Qué hace lambda x: x+1?", ["Define una clase", "Es una función anónima de una expresión", "Un bucle", "Una lista"], 1, "lambda crea funciones anónimas breves."],
      ["¿Qué imprime bool([])?", ["True", "False", "None", "Error"], 1, "Una lista vacía es falsy."],
      ["¿Qué diferencia hay entre is y ==?", ["Ninguna", "is compara identidad (mismo objeto); == compara valor", "== compara identidad", "is compara tipos"], 1, "is verifica que sean el mismo objeto en memoria."],
      ["¿Qué método de string separa por un delimitador?", ["join()", "split()", "strip()", "replace()"], 1, "split() divide un string en una lista."],
    ]),
    fase(7, [
      ["¿Qué es el GIL en CPython?", ["Un recolector de basura", "El Global Interpreter Lock que serializa la ejecución de bytecode", "Un módulo de red", "Un tipo de hilo"], 1, "El GIL impide que múltiples hilos ejecuten bytecode a la vez."],
      ["¿Qué hace @property?", ["Crea un atributo de clase", "Expone un método como atributo de solo lectura", "Define un decorador de bucle", "Serializa"], 1, "@property permite acceder a un método como si fuera atributo."],
      ["¿Qué es un context manager (with)?", ["Un bucle", "Gestiona recursos garantizando cierre (__enter__/__exit__)", "Un decorador de clase", "Un tipo de excepción"], 1, "with asegura liberar el recurso al salir del bloque."],
      ["¿Qué devuelve list(map(str, [1,2]))?", ["[1,2]", "[\"1\",\"2\"]", "\"12\"", "Error"], 1, "map aplica str a cada elemento."],
      ["¿Qué es una comprehension de diccionario?", ["{k:v for ...}", "[k for ...]", "(k,v)", "set(k)"], 0, "{clave:valor for ...} construye un dict."],
    ]),
    fase(8, [
      ["¿Qué hace __init__ en una clase?", ["Destruye la instancia", "Es el constructor que inicializa la instancia", "Define un decorador", "Importa módulos"], 1, "__init__ se ejecuta al crear la instancia."],
      ["¿Qué es la herencia múltiple?", ["Una clase hereda de varias clases base", "Copiar métodos manualmente", "Un tipo de bucle", "No existe en Python"], 0, "Python permite heredar de varias clases; usa el MRO para resolver."],
      ["¿Qué es el MRO?", ["Method Resolution Order: orden de búsqueda de métodos", "Un módulo de red", "Un recolector", "Un tipo de decorador"], 0, "El MRO define el orden de resolución con herencia."],
      ["¿Qué hace yield from?", ["Delega a otro generador/iterable", "Cierra el generador", "Crea una lista", "Lanza excepción"], 0, "yield from delega la producción a otro iterable."],
      ["¿Qué es un dunder method?", ["Método con doble guion bajo, ej. __str__", "Un método privado", "Un decorador", "Una excepción"], 0, "Los métodos __x__ definen comportamiento del modelo de datos."],
    ]),
    fase(9, [
      ["¿Qué diferencia hay entre __str__ y __repr__?", ["Ninguna", "__str__ es legible para usuarios; __repr__ es no ambigua para desarrolladores", "__repr__ es para JSON", "__str__ define igualdad"], 1, "__repr__ apunta a una representación inequívoca."],
      ["¿Qué hace functools.lru_cache?", ["Memoiza resultados de una función", "Crea hilos", "Serializa", "Ordena"], 0, "lru_cache cachea llamadas por argumentos."],
      ["¿Qué es asyncio?", ["Un ORM", "La librería de concurrencia asíncrona con async/await", "Un test runner", "Un compilador"], 1, "asyncio provee el event loop y corrutinas."],
      ["¿Qué es un metaclass?", ["La clase de una clase (controla su creación)", "Una clase abstracta", "Un decorador", "Un módulo"], 0, "Las metaclases definen cómo se construyen las clases."],
      ["¿Qué hace __slots__?", ["Permite atributos dinámicos", "Restringe atributos y ahorra memoria evitando __dict__", "Crea propiedades", "Congela la clase"], 1, "__slots__ fija los atributos y reduce el uso de memoria."],
    ]),
    fase(10, [
      ["¿Por qué usar generadores frente a listas en datos grandes?", ["Son más lentos", "Producen valores perezosamente, sin cargar todo en memoria", "Ordenan automáticamente", "Evitan errores de tipo"], 1, "El generador evalúa bajo demanda, ideal para streaming."],
      ["¿Qué problema resuelve el patrón descriptor?", ["Renderizado", "Controlar acceso a atributos vía __get__/__set__", "Concurrencia", "Serialización"], 1, "Los descriptores gestionan el acceso a atributos reutilizablemente."],
      ["En CPython, ¿cómo se logra paralelismo real de CPU pese al GIL?", ["Con hilos", "Con multiprocessing (procesos separados)", "Con async", "No se puede"], 1, "multiprocessing evita el GIL usando procesos independientes."],
      ["¿Qué es la evaluación perezosa en itertools?", ["Cargar todo en memoria", "Iteradores que producen bajo demanda y se pueden encadenar", "Un cache", "Un decorador"], 1, "itertools ofrece iteradores perezosos y componibles."],
      ["¿Qué garantiza el protocolo async context manager (async with)?", ["Nada", "Entrar/salir de un recurso de forma asíncrona (__aenter__/__aexit__)", "Crear hilos", "Memoizar"], 1, "async with gestiona recursos asíncronos con cierre garantizado."],
    ]),
  ],
);

const java: QuizTema = tema(
  "java",
  "Java",
  "Tipado estático, POO, colecciones, genéricos, JVM y concurrencia.",
  [
    fase(1, [
      ["¿Qué método es el punto de entrada de un programa Java?", ["start()", "main()", "run()", "init()"], 1, "public static void main(String[] args) inicia la ejecución."],
      ["¿Cómo se declara un entero?", ["int x = 5;", "integer x = 5;", "var x := 5;", "num x = 5;"], 0, "int es el tipo primitivo entero."],
      ["¿Con qué se imprime en consola?", ["print()", "console.log()", "System.out.println()", "echo()"], 2, "System.out.println() imprime una línea."],
      ["¿Cómo termina cada sentencia en Java?", ["Con salto de línea", "Con punto y coma ;", "Con coma", "Con dos puntos"], 1, "Cada sentencia termina en ;."],
      ["¿Qué tipo almacena verdadero/falso?", ["bit", "bool", "boolean", "flag"], 2, "boolean es el tipo lógico en Java."],
    ]),
    fase(2, [
      ["¿Qué es una clase en Java?", ["Una función", "Una plantilla para crear objetos", "Un tipo primitivo", "Un bucle"], 1, "La clase define atributos y métodos de sus objetos."],
      ["¿Cómo se crea un objeto?", ["new Clase()", "Clase.create()", "make Clase", "Clase()"], 0, "new invoca el constructor y crea la instancia."],
      ["¿Qué palabra clave define una constante?", ["const", "final", "static", "readonly"], 1, "final impide reasignar la variable."],
      ["¿Cuál es el tipo para texto?", ["char", "String", "text", "str"], 1, "String representa cadenas de caracteres."],
      ["¿Qué tipo de dato es 3.14?", ["int", "double", "String", "char"], 1, "Por defecto los decimales son double."],
    ]),
    fase(3, [
      ["¿Qué es la encapsulación?", ["Ocultar el estado interno y exponerlo vía métodos", "Heredar de otra clase", "Sobrecargar métodos", "Crear hilos"], 0, "Se logra con private + getters/setters."],
      ["¿Qué modificador hace un atributo accesible solo dentro de su clase?", ["public", "protected", "private", "default"], 2, "private restringe el acceso a la propia clase."],
      ["¿Qué colección permite duplicados y mantiene orden de inserción?", ["Set", "ArrayList", "HashMap", "TreeSet"], 1, "ArrayList es una lista indexada que admite duplicados."],
      ["¿Qué hace un constructor?", ["Destruye el objeto", "Inicializa el objeto al crearlo", "Imprime datos", "Hereda métodos"], 1, "El constructor prepara el estado inicial."],
      ["¿Qué es la sobrecarga de métodos?", ["Mismo nombre con distintas firmas de parámetros", "Heredar métodos", "Ocultar atributos", "Un hilo"], 0, "El overloading distingue por número/tipo de parámetros."],
    ]),
    fase(4, [
      ["¿Qué es la herencia?", ["Una clase adquiere atributos y métodos de otra con extends", "Copiar código", "Un tipo de colección", "Un hilo"], 0, "extends crea una relación 'es-un'."],
      ["¿Qué es una interfaz?", ["Un contrato de métodos a implementar", "Una clase concreta", "Un tipo primitivo", "Un bucle"], 0, "La interfaz declara métodos que las clases deben implementar."],
      ["¿Qué es el polimorfismo?", ["Un objeto responde según su tipo real en tiempo de ejecución", "Duplicar clases", "Ocultar métodos", "Crear constantes"], 0, "Permite tratar subtipos a través de un tipo base."],
      ["¿Qué colección asocia claves a valores?", ["ArrayList", "HashSet", "HashMap", "LinkedList"], 2, "HashMap almacena pares clave-valor."],
      ["¿Qué palabra clave llama al constructor de la superclase?", ["this", "super", "base", "parent"], 1, "super(...) invoca el constructor padre."],
    ]),
    fase(5, [
      ["¿Qué son los genéricos (Generics)?", ["Tipos parametrizados para seguridad en tiempo de compilación", "Métodos estáticos", "Excepciones", "Hilos"], 0, "List<String> evita casts y errores de tipo."],
      ["¿Qué diferencia hay entre == y equals() en objetos?", ["Ninguna", "== compara referencias; equals() compara contenido", "equals compara referencias", "== compara contenido"], 1, "== mira si son el mismo objeto; equals() el valor lógico."],
      ["¿Qué es una excepción checked?", ["Debe declararse o capturarse obligatoriamente", "Se ignora siempre", "Es un warning", "Es un tipo primitivo"], 0, "Las checked exceptions obligan a manejarlas."],
      ["¿Qué hace el bloque finally?", ["Se ejecuta solo si hay error", "Se ejecuta siempre, haya o no excepción", "Nunca se ejecuta", "Reemplaza a catch"], 1, "finally corre pase lo que pase (limpieza de recursos)."],
      ["¿Qué es autoboxing?", ["Conversión automática entre primitivos y sus wrappers", "Crear hilos", "Serializar", "Ordenar listas"], 0, "int <-> Integer automáticamente."],
    ]),
    fase(6, [
      ["¿Qué es una clase abstracta?", ["No se puede instanciar; puede tener métodos abstractos y concretos", "Una interfaz pura", "Un tipo final", "Un hilo"], 0, "Sirve de base parcial para subclases."],
      ["¿Qué introduce una expresión lambda en Java 8?", ["Funciones anónimas para interfaces funcionales", "Hilos", "Genéricos", "Anotaciones"], 0, "Las lambdas implementan interfaces de un solo método."],
      ["¿Qué es el Stream API?", ["Procesamiento funcional de colecciones", "Un tipo de archivo", "Un hilo", "Un ORM"], 0, "Streams permiten map/filter/reduce declarativos."],
      ["¿Qué representa Optional<T>?", ["Un valor que puede estar presente o ausente", "Una lista", "Una excepción", "Un hilo"], 0, "Optional evita NullPointerException explicitando la ausencia."],
      ["¿Qué anotación indica que se sobrescribe un método?", ["@Overload", "@Override", "@Inherit", "@Super"], 1, "@Override documenta y valida la sobrescritura."],
    ]),
    fase(7, [
      ["¿Qué es la JVM?", ["Máquina virtual que ejecuta bytecode Java", "Un compilador de C", "Un IDE", "Un framework web"], 0, "La JVM interpreta/compila el bytecode multiplataforma."],
      ["¿Qué hace el recolector de basura (GC)?", ["Libera memoria de objetos sin referencias", "Compila el código", "Crea hilos", "Ordena listas"], 0, "El GC recupera memoria de objetos inalcanzables."],
      ["¿Qué es un método static?", ["Pertenece a la clase, no a la instancia", "Se ejecuta en un hilo", "Es privado siempre", "Es final"], 0, "Los métodos static se invocan sin crear objetos."],
      ["¿Qué garantiza synchronized?", ["Acceso exclusivo a un bloque por un hilo a la vez", "Más velocidad", "Menos memoria", "Herencia"], 0, "synchronized evita condiciones de carrera con un monitor."],
      ["¿Qué colección está ordenada por sus claves?", ["HashMap", "TreeMap", "ArrayList", "HashSet"], 1, "TreeMap mantiene las claves ordenadas."],
    ]),
    fase(8, [
      ["¿Qué es el borrado de tipos (type erasure) en genéricos?", ["Los tipos genéricos se eliminan en tiempo de ejecución", "Se conservan en runtime", "Es un GC", "Un hilo"], 0, "En runtime List<String> y List<Integer> son iguales."],
      ["¿Qué es un ExecutorService?", ["Un pool de hilos gestionado", "Un ORM", "Una excepción", "Un genérico"], 0, "Administra la ejecución de tareas concurrentes."],
      ["¿Qué hace volatile?", ["Garantiza visibilidad de cambios entre hilos", "Bloquea un método", "Crea un pool", "Serializa"], 0, "volatile asegura lecturas frescas desde memoria principal."],
      ["¿Qué es una referencia a método (::)?", ["Atajo para una lambda que llama a un método existente", "Un puntero", "Un genérico", "Un hilo"], 0, "String::length referencia el método length."],
      ["¿Qué diferencia hay entre ArrayList y LinkedList?", ["Ninguna", "ArrayList: acceso por índice O(1); LinkedList: inserción/borrado O(1) en extremos", "LinkedList indexa más rápido", "ArrayList no admite duplicados"], 1, "Difieren en el costo de acceso vs. inserción."],
    ]),
    fase(9, [
      ["¿Qué es el modelo de memoria de Java (JMM)?", ["Define visibilidad y orden de operaciones entre hilos", "El heap y stack solamente", "Un GC", "Un ORM"], 0, "El JMM especifica happens-before entre hilos."],
      ["¿Qué son las relaciones happens-before?", ["Garantías de orden y visibilidad entre acciones concurrentes", "Un tipo de excepción", "Un genérico", "Un stream"], 0, "Aseguran que un efecto sea visible para otra acción."],
      ["¿Qué ventaja da un CompletableFuture?", ["Composición de tareas asíncronas encadenables", "Serialización", "Ordenar listas", "Reducir memoria"], 0, "Permite orquestar asincronía con thenApply, etc."],
      ["¿Qué hace la palabra clave sealed (Java 17)?", ["Restringe qué clases pueden extender/implementar", "Congela un objeto", "Crea un hilo", "Serializa"], 0, "sealed limita la jerarquía de subtipos permitidos."],
      ["¿Qué es escape analysis en la JIT?", ["Optimización que puede evitar asignar objetos en el heap", "Un GC", "Un test", "Un genérico"], 0, "Si un objeto no 'escapa', puede asignarse en la pila."],
    ]),
    fase(10, [
      ["¿Qué problema resuelven las estructuras de java.util.concurrent frente a synchronized?", ["Nada", "Mayor escalabilidad con locks de grano fino y estructuras lock-free", "Menos memoria siempre", "Eliminan hilos"], 1, "Ofrecen concurrencia más escalable y flexible."],
      ["¿Qué es la memoria off-heap y para qué sirve?", ["Memoria fuera del heap gestionado, útil para grandes buffers sin presión de GC", "Un pool de hilos", "El stack", "Un genérico"], 0, "Reduce pausas del GC en buffers grandes (p.ej. NIO)."],
      ["¿Qué garantiza una variable final para la seguridad de hilos?", ["Nada", "Su valor es visible correctamente tras la construcción (safe publication)", "Bloquea el objeto", "Crea un pool"], 1, "Los campos final se publican de forma segura."],
      ["¿Qué son los Virtual Threads (Project Loom)?", ["Hilos ligeros gestionados por la JVM que escalan a millones", "Procesos del SO", "Un GC nuevo", "Genéricos"], 0, "Los virtual threads reducen el costo de la concurrencia bloqueante."],
      ["¿Qué es un memory leak típico en Java pese al GC?", ["Referencias vivas no usadas (p.ej. en colecciones estáticas o listeners)", "Punteros colgantes", "Desbordamiento de pila", "Falta de free()"], 0, "El GC no libera lo que sigue siendo alcanzable."],
    ]),
  ],
);

const csharp: QuizTema = tema(
  "csharp",
  "C#",
  "Lenguaje de .NET: tipos, LINQ, async/await, propiedades y genéricos.",
  [
    fase(1, [
      ["¿Con qué se imprime en consola?", ["print()", "Console.WriteLine()", "echo", "System.out"], 1, "Console.WriteLine() escribe una línea."],
      ["¿Cómo se declara un entero?", ["int x = 5;", "let x = 5", "integer x = 5", "num x = 5"], 0, "int es el tipo entero de 32 bits."],
      ["¿Qué palabra infiere el tipo de una variable local?", ["auto", "var", "dynamic", "let"], 1, "var infiere el tipo en tiempo de compilación."],
      ["¿Cómo termina una sentencia?", ["Salto de línea", "Punto y coma ;", "Coma", "Dos puntos"], 1, "Cada sentencia acaba en ;."],
      ["¿Qué tipo representa texto?", ["char", "string", "text", "String[]"], 1, "string almacena cadenas de caracteres."],
    ]),
    fase(2, [
      ["¿Qué es una propiedad (property)?", ["Un miembro con get/set que encapsula un campo", "Un método estático", "Un bucle", "Un evento"], 0, "Las propiedades exponen datos con lógica de acceso."],
      ["¿Qué palabra clave define una constante?", ["final", "const", "readonly only", "static var"], 1, "const define constantes en compilación."],
      ["¿Qué operador comprueba igualdad?", ["=", "==", ":=", "==="], 1, "== compara igualdad de valor."],
      ["¿Cómo se crea un objeto?", ["new Clase()", "Clase.new()", "make Clase", "alloc Clase"], 0, "new invoca el constructor."],
      ["¿Qué es un namespace?", ["Un contenedor lógico de tipos", "Un tipo primitivo", "Un bucle", "Una excepción"], 0, "Los namespaces organizan y evitan colisiones de nombres."],
    ]),
    fase(3, [
      ["¿Qué es LINQ?", ["Lenguaje de consultas integrado sobre colecciones", "Un ORM externo", "Un tipo de hilo", "Un IDE"], 0, "LINQ consulta datos de forma declarativa."],
      ["¿Qué colección genérica es una lista dinámica?", ["Array", "List<T>", "Dictionary<K,V>", "HashSet<T>"], 1, "List<T> es una lista redimensionable tipada."],
      ["¿Qué hace la interpolación $\"{x}\"?", ["Inserta el valor de x en el string", "Convierte a int", "Filtra", "Concatena arrays"], 0, "Los strings interpolados incrustan expresiones."],
      ["¿Qué es un método?", ["Un bloque de código con nombre que realiza una acción", "Un tipo de dato", "Una propiedad", "Un namespace"], 0, "Los métodos encapsulan comportamiento."],
      ["¿Qué palabra permite valores nulos en un tipo de valor, como int?", ["nullable ?", "void", "dynamic", "ref"], 0, "int? admite null (Nullable<int>)."],
    ]),
    fase(4, [
      ["¿Qué operador anula-condicional evita NullReferenceException?", ["??", "?.", "&&", "::"], 1, "?. accede solo si el objeto no es null."],
      ["¿Qué hace el operador ??", ["Devuelve el operando izquierdo si no es null, si no el derecho", "Compara tipos", "Concatena", "Lanza excepción"], 0, "El null-coalescing provee un valor alternativo."],
      ["¿Qué es una interfaz?", ["Un contrato de miembros a implementar", "Una clase concreta", "Un struct", "Un delegado"], 0, "Las interfaces definen capacidades a implementar."],
      ["¿Qué es un struct frente a una class?", ["struct es tipo por valor; class es por referencia", "Son idénticos", "class es por valor", "struct no tiene métodos"], 0, "Los structs se copian por valor."],
      ["¿Qué hace foreach?", ["Itera sobre una colección enumerable", "Ordena", "Filtra", "Crea hilos"], 0, "foreach recorre elementos de un IEnumerable."],
    ]),
    fase(5, [
      ["¿Qué es un delegate?", ["Un tipo que referencia métodos (puntero a función tipado)", "Una clase abstracta", "Un genérico", "Un namespace"], 0, "Los delegados encapsulan referencias a métodos."],
      ["¿Qué es un evento (event)?", ["Un delegado con publicación/suscripción controlada", "Un bucle", "Un struct", "Una excepción"], 0, "Los events implementan el patrón observador."],
      ["¿Qué retorna un método async?", ["void siempre", "Task o Task<T>", "un delegate", "un struct"], 1, "Los métodos async retornan Task/Task<T> (o void en handlers)."],
      ["¿Qué hace await?", ["Bloquea el hilo", "Suspende el método hasta completar la tarea sin bloquear el hilo", "Crea un hilo", "Lanza excepción"], 1, "await libera el hilo mientras espera."],
      ["¿Qué es un método de extensión?", ["Agrega métodos a un tipo existente sin modificarlo", "Un constructor", "Un evento", "Un genérico"], 0, "Los extension methods amplían tipos con this en el primer parámetro."],
    ]),
    fase(6, [
      ["¿Qué es un tipo genérico?", ["Un tipo parametrizado, ej. Repository<T>", "Un delegado", "Un evento", "Un namespace"], 0, "Los genéricos permiten reutilizar con seguridad de tipos."],
      ["¿Qué hace yield return?", ["Construye un iterador perezoso", "Cierra el método", "Crea un hilo", "Lanza excepción"], 0, "yield produce elementos bajo demanda."],
      ["¿Qué diferencia hay entre IEnumerable e IQueryable?", ["Ninguna", "IQueryable traduce la consulta al origen (p.ej. SQL); IEnumerable ejecuta en memoria", "IEnumerable va a SQL", "IQueryable es sincrónico"], 1, "IQueryable difiere y traduce la expresión al proveedor."],
      ["¿Qué es un record (C# 9)?", ["Un tipo inmutable con igualdad por valor", "Una clase mutable", "Un struct sin métodos", "Un delegado"], 0, "Los records facilitan datos inmutables con value equality."],
      ["¿Qué es pattern matching con switch expressions?", ["Coincidencia de patrones concisa que retorna un valor", "Un bucle", "Un evento", "Un namespace"], 0, "Las switch expressions evalúan patrones y devuelven un resultado."],
    ]),
    fase(7, [
      ["¿Qué hace el recolector de basura de .NET?", ["Libera memoria administrada no referenciada por generaciones", "Compila IL", "Crea hilos", "Serializa"], 0, "El GC generacional recupera memoria de objetos inalcanzables."],
      ["¿Qué es IDisposable / using?", ["Libera recursos no administrados de forma determinista", "Crea genéricos", "Un evento", "Un delegado"], 0, "using invoca Dispose() al salir del bloque."],
      ["¿Qué es boxing?", ["Convertir un tipo por valor a object (heap)", "Serializar", "Un genérico", "Un evento"], 0, "El boxing envuelve un value type en un object."],
      ["¿Qué hace ConfigureAwait(false)?", ["Evita capturar el contexto de sincronización al reanudar", "Bloquea el hilo", "Cancela la tarea", "Crea un hilo"], 0, "Útil en librerías para no volver al contexto original."],
      ["¿Qué es CancellationToken?", ["Un mecanismo cooperativo para cancelar operaciones async", "Un GC", "Un evento", "Un struct"], 0, "Permite señalizar y observar cancelaciones."],
    ]),
    fase(8, [
      ["¿Qué es covarianza en genéricos (out T)?", ["Permite usar un subtipo donde se espera el tipo base en salidas", "Un GC", "Un evento", "Boxing"], 0, "out T habilita IEnumerable<Derivada> como IEnumerable<Base>."],
      ["¿Qué es Span<T>?", ["Una vista de memoria contigua sin asignaciones, tipo por valor", "Una lista enlazada", "Un evento", "Un delegado"], 0, "Span<T> permite trabajar memoria sin copiar ni asignar en heap."],
      ["¿Qué diferencia hay entre Task y ValueTask?", ["Ninguna", "ValueTask evita asignaciones cuando el resultado suele estar disponible sincrónicamente", "Task es más rápido siempre", "ValueTask no es async"], 1, "ValueTask reduce presión de GC en rutas calientes."],
      ["¿Qué son los source generators?", ["Generan código en tiempo de compilación", "Un GC", "Un ORM", "Un evento"], 0, "Producen código adicional durante la compilación."],
      ["¿Qué hace lock(obj)?", ["Garantiza exclusión mutua en una sección crítica", "Congela obj", "Crea un hilo", "Serializa"], 0, "lock usa un Monitor para exclusión mutua."],
    ]),
    fase(9, [
      ["¿Por qué ValueTask no debe consumirse dos veces?", ["Puede envolver un IValueTaskSource reutilizable y su estado ser inválido", "Es inmutable", "No aplica", "Bloquea el hilo"], 0, "Consumirla más de una vez es comportamiento indefinido."],
      ["¿Qué ventaja da stackalloc con Span<T>?", ["Reserva en la pila sin presión de GC para buffers pequeños", "Crea hilos", "Serializa", "Congela memoria"], 0, "stackalloc evita el heap para buffers temporales."],
      ["¿Qué es el patrón async streams (IAsyncEnumerable)?", ["Iterar de forma asíncrona con await foreach", "Un GC", "Un delegado", "Boxing"], 0, "Produce y consume secuencias asíncronas perezosamente."],
      ["¿Qué problema resuelve ArrayPool<T>?", ["Reutiliza buffers para reducir asignaciones y GC", "Ordena arrays", "Serializa", "Crea hilos"], 0, "ArrayPool alquila y devuelve arrays reutilizables."],
      ["¿Qué es una struct ref (ref struct)?", ["Un tipo que solo vive en la pila (no puede ir al heap)", "Una clase inmutable", "Un evento", "Un delegado"], 0, "ref struct (como Span<T>) no puede escapar a la heap."],
    ]),
    fase(10, [
      ["¿Qué implica que Span<T> no pueda usarse en métodos async?", ["Como ref struct no puede sobrevivir en el heap entre awaits", "Es demasiado lento", "No es tipado", "Requiere boxing"], 0, "Los awaits pueden mover el estado al heap, prohibido para ref struct."],
      ["¿Qué es 'server GC' frente a 'workstation GC'?", ["server GC usa múltiples heaps/hilos para throughput en servidores", "No hay diferencia", "workstation es para servidores", "server GC no compacta"], 0, "server GC optimiza rendimiento en cargas concurrentes."],
      ["¿Qué garantiza Memory<T> frente a Span<T>?", ["Puede almacenarse en el heap y usarse en código async", "Es más rápido", "Es un delegado", "Requiere boxing"], 0, "Memory<T> no es ref struct, por eso funciona con async."],
      ["¿Qué es el patrón de 'pooling' con ObjectPool?", ["Reutilizar instancias costosas para reducir asignaciones", "Serializar", "Crear hilos", "Ordenar"], 0, "Reduce el costo de crear/destruir objetos frecuentes."],
      ["¿Por qué preferir readonly struct en tipos por valor grandes?", ["Evita copias defensivas y comunica inmutabilidad", "Es obligatorio", "Permite herencia", "Habilita boxing"], 0, "readonly struct impide mutaciones y mejora rendimiento."],
    ]),
  ],
);

const cpp: QuizTema = tema(
  "cpp",
  "C++",
  "Punteros, memoria manual, RAII, plantillas y semántica de movimiento.",
  [
    fase(1, [
      ["¿Qué stream imprime en consola?", ["print", "std::cout", "printf only", "System.out"], 1, "std::cout << envía datos a la salida estándar."],
      ["¿Cómo se declara un entero?", ["int x = 5;", "let x = 5", "var x = 5", "integer x = 5"], 0, "int es el tipo entero básico."],
      ["¿Qué función es el punto de entrada?", ["start()", "main()", "run()", "begin()"], 1, "int main() inicia el programa."],
      ["¿Cómo termina una sentencia?", ["Salto de línea", "Punto y coma ;", "Coma", "Dos puntos"], 1, "Cada sentencia acaba en ;."],
      ["¿Qué directiva incluye una cabecera?", ["#import", "#include", "using", "require"], 1, "#include incorpora archivos de cabecera."],
    ]),
    fase(2, [
      ["¿Qué es un puntero?", ["Una variable que guarda una dirección de memoria", "Un tipo de bucle", "Una clase", "Un valor booleano"], 0, "Un puntero almacena la dirección de otra variable."],
      ["¿Qué operador obtiene la dirección de una variable?", ["*", "&", "->", "#"], 1, "& devuelve la dirección de memoria."],
      ["¿Qué operador desreferencia un puntero?", ["&", "*", "->", "::"], 1, "* accede al valor apuntado."],
      ["¿Qué es una referencia (int&)?", ["Un alias de otra variable", "Un puntero nulo", "Una copia", "Un tipo constante"], 0, "La referencia es un alias que no puede reasignarse."],
      ["¿Qué tipo representa un carácter?", ["char", "String", "text", "byte8"], 0, "char almacena un carácter."],
    ]),
    fase(3, [
      ["¿Qué hace new?", ["Reserva memoria dinámica en el heap", "Crea un hilo", "Copia un objeto", "Ordena"], 0, "new asigna en el heap y devuelve un puntero."],
      ["¿Qué libera la memoria reservada con new?", ["free", "delete", "dispose", "release"], 1, "delete libera memoria asignada con new."],
      ["¿Qué es un struct en C++?", ["Un agregado de datos (con miembros public por defecto)", "Un puntero", "Un bucle", "Una plantilla"], 0, "struct agrupa datos; en C++ puede tener métodos."],
      ["¿Qué es el operador ->?", ["Accede a un miembro a través de un puntero", "Desreferencia", "Suma", "Compara"], 0, "ptr->miembro equivale a (*ptr).miembro."],
      ["¿Qué contenedor es un array dinámico de la STL?", ["std::list", "std::vector", "std::map", "std::set"], 1, "std::vector es un array redimensionable."],
    ]),
    fase(4, [
      ["¿Qué es un constructor?", ["Método que inicializa el objeto al crearse", "Método que lo destruye", "Un puntero", "Una plantilla"], 0, "El constructor establece el estado inicial."],
      ["¿Qué hace un destructor (~Clase)?", ["Libera recursos al destruirse el objeto", "Crea el objeto", "Copia el objeto", "Compara"], 0, "El destructor limpia recursos al final de vida."],
      ["¿Qué es RAII?", ["Adquirir recursos en la construcción y liberarlos en la destrucción", "Un tipo de puntero", "Un bucle", "Una plantilla"], 0, "RAII ata el ciclo de vida del recurso al del objeto."],
      ["¿Qué es std::string?", ["Una clase para cadenas dinámicas", "Un puntero a char const", "Un vector de int", "Un stream"], 0, "std::string gestiona cadenas con memoria automática."],
      ["¿Qué es sobrecarga de operadores?", ["Definir el comportamiento de operadores para tipos propios", "Heredar métodos", "Crear hilos", "Un destructor"], 0, "Permite, p.ej., definir + para una clase Vector."],
    ]),
    fase(5, [
      ["¿Qué es una plantilla (template)?", ["Código genérico parametrizado por tipos", "Un puntero", "Un destructor", "Un stream"], 0, "template<class T> genera código para cualquier tipo."],
      ["¿Qué es std::unique_ptr?", ["Un smart pointer de propiedad exclusiva", "Una referencia", "Un vector", "Un stream"], 0, "unique_ptr libera automáticamente y no se copia."],
      ["¿Qué es std::shared_ptr?", ["Un smart pointer con conteo de referencias compartido", "Un puntero crudo", "Una plantilla", "Un destructor"], 0, "shared_ptr libera cuando el contador llega a cero."],
      ["¿Qué problema previenen los smart pointers?", ["Fugas de memoria y dangling pointers", "Errores de sintaxis", "Condiciones de carrera", "Overflow de pila"], 0, "Automatizan la liberación de memoria dinámica."],
      ["¿Qué es la herencia en C++?", ["Una clase deriva de otra con : public Base", "Copiar código", "Un smart pointer", "Un stream"], 0, "La derivación reutiliza y extiende una clase base."],
    ]),
    fase(6, [
      ["¿Qué es una función virtual?", ["Permite despacho dinámico (polimorfismo) vía la clase base", "Una plantilla", "Un destructor", "Un puntero"], 0, "virtual habilita resolución en tiempo de ejecución."],
      ["¿Qué es la semántica de movimiento (move)?", ["Transferir recursos sin copiar usando rvalue references", "Copiar profundamente", "Un smart pointer", "Un stream"], 0, "std::move evita copias costosas transfiriendo la propiedad."],
      ["¿Qué es std::move?", ["Convierte a rvalue para habilitar el movimiento", "Mueve archivos", "Copia", "Crea un hilo"], 0, "std::move marca un objeto como candidato a moverse."],
      ["¿Qué es la 'regla de los cinco'?", ["Definir destructor, copia/move constructor y copia/move asignación coherentemente", "Cinco plantillas", "Cinco hilos", "Cinco punteros"], 0, "Si gestionas un recurso, define los cinco miembros especiales."],
      ["¿Qué hace const en un método (int f() const)?", ["Garantiza que el método no modifica el objeto", "Lo hace estático", "Lo hace virtual", "Crea un hilo"], 0, "Un método const no altera el estado del objeto."],
    ]),
    fase(7, [
      ["¿Qué es un rvalue reference (T&&)?", ["Una referencia a un temporal, base del move", "Un puntero nulo", "Una plantilla", "Un stream"], 0, "T&& enlaza con objetos temporales (rvalues)."],
      ["¿Qué es perfect forwarding?", ["Reenviar argumentos preservando su categoría (lvalue/rvalue) con std::forward", "Copiar siempre", "Un destructor", "Un puntero"], 0, "std::forward mantiene value category en plantillas."],
      ["¿Qué es una lambda en C++?", ["Una función anónima con captura de contexto", "Una plantilla", "Un puntero", "Un destructor"], 0, "[captura](args){...} define funciones inline."],
      ["¿Qué es constexpr?", ["Evaluación en tiempo de compilación", "Un puntero constante", "Un stream", "Un hilo"], 0, "constexpr permite calcular valores en compilación."],
      ["¿Qué es SFINAE?", ["'Substitution Failure Is Not An Error': descarta sobrecargas inválidas en plantillas", "Un smart pointer", "Un destructor", "Un stream"], 0, "SFINAE guía la resolución de sobrecargas con plantillas."],
    ]),
    fase(8, [
      ["¿Qué garantiza std::unique_ptr sobre el costo?", ["Cero overhead frente a un puntero crudo bien usado", "Duplica memoria", "Usa conteo atómico", "Copia profundamente"], 0, "unique_ptr no añade sobrecarga de conteo."],
      ["¿Por qué shared_ptr tiene más costo que unique_ptr?", ["Mantiene un bloque de control con contador atómico", "Copia el objeto", "Usa RTTI", "Bloquea hilos"], 0, "El conteo atómico de referencias tiene costo."],
      ["¿Qué resuelve std::weak_ptr?", ["Referencias cíclicas rompiendo la propiedad fuerte", "Fugas de pila", "Overflow", "Condiciones de carrera"], 0, "weak_ptr observa sin incrementar el conteo fuerte."],
      ["¿Qué son los conceptos (concepts, C++20)?", ["Restricciones nombradas sobre parámetros de plantilla", "Un smart pointer", "Un stream", "Un hilo"], 0, "Los concepts documentan y validan requisitos de tipos."],
      ["¿Qué es undefined behavior?", ["Comportamiento no definido por el estándar (p.ej. desbordar un puntero)", "Un warning", "Un error de enlace", "Una excepción"], 0, "El UB puede producir cualquier resultado, incluso silencioso."],
    ]),
    fase(9, [
      ["¿Qué es la copy elision / RVO?", ["Omitir copias de valores de retorno construyéndolos en su destino", "Un GC", "Un smart pointer", "Un stream"], 0, "El compilador elide la copia del valor devuelto."],
      ["¿Qué garantiza std::atomic?", ["Operaciones atómicas y visibilidad entre hilos sin locks", "Copias profundas", "RAII de archivos", "RTTI"], 0, "std::atomic evita condiciones de carrera en variables compartidas."],
      ["¿Qué es memory ordering (std::memory_order)?", ["Controla el orden/visibilidad de operaciones atómicas entre hilos", "Un GC", "Un stream", "Una plantilla"], 0, "Define garantías como acquire/release."],
      ["¿Qué ventaja da move semantics en un vector al crecer?", ["Mueve elementos en lugar de copiarlos si el move es noexcept", "Duplica memoria", "Usa hilos", "Nada"], 0, "vector usa move (si es noexcept) al realocar."],
      ["¿Por qué marcar move constructors como noexcept?", ["Permite que contenedores usen move en lugar de copy al realocar", "Es obligatorio", "Evita punteros", "Crea hilos"], 0, "Sin noexcept, std::vector copia por seguridad de excepciones."],
    ]),
    fase(10, [
      ["¿Qué problema evita el idiom 'rule of zero'?", ["Definir miembros especiales manualmente delegando en tipos RAII", "Fugas de pila", "Overflow", "Condiciones de carrera"], 0, "Si usas tipos que gestionan su recurso, no defines los cinco."],
      ["¿Qué es false sharing en concurrencia?", ["Hilos que tocan variables distintas en la misma línea de caché, degradando rendimiento", "Compartir un lock", "Un data race", "Una fuga"], 0, "Se mitiga alineando/rellenando datos por línea de caché."],
      ["¿Qué garantiza el modelo de memoria de C++11 con acquire/release?", ["Sincronización parcial ordenando ciertas lecturas/escrituras entre hilos", "Exclusión mutua total", "GC", "RVO"], 0, "acquire/release establece relaciones de sincronización puntuales."],
      ["¿Qué es una violación estricta de aliasing?", ["Acceder a un objeto mediante un tipo incompatible, provocando UB", "Un warning", "Un error de enlace", "Una excepción"], 0, "El compilador asume que punteros de tipos distintos no se solapan."],
      ["¿Qué ventaja aporta std::pmr (polymorphic memory resources)?", ["Personalizar la estrategia de asignación de contenedores en runtime", "Elimina el heap", "Es un GC", "Un stream"], 0, "pmr permite inyectar asignadores (p.ej. arenas) sin plantillas."],
    ]),
  ],
);

export const TEMAS_LENGUAJES: QuizTema[] = [javascript, python, java, csharp, cpp];
